### ISSUE TITLE
HTTP response code seems wrong

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#101]
## Bug description
While testing `goregrish.com` the browser returns a HTTP code 200
![image](https://user-images.githubusercontent.com/44526987/89197040-6642d000-d5ab-11ea-8f94-83752ba3b9b3.png)

While PyFunceble returns a HTTP code of 301
![image](https://user-images.githubusercontent.com/44526987/89197096-7fe41780-d5ab-11ea-86b8-4b83c8196e9d.png)
`goregrish.com ACTIVE      12-jun-2023       WHOIS      301` 

## Modifications under `.PyFunceble.yaml`

non

## Reproduction

./toolbox/domain-test.sh 
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

Enter any custom test string: -dbr 30 -ex -m -p 2 -h --idna --mining -a --plain -vsc --hierarchical -db --database-type mariadb --dns 127.0.0.1:5302

Source code from https://github.com/Clefspeare13/pornhosts/pull/138

## Expected behavior
I expected the HTTP code was equal each other, and in this case `200`

## Screenshots
See above

## Versions

**OS:** miniconda (https://github.com/PyFunceble-Templates/pyfunceble-miniconda)
**Python Version:** 3.8.2
**PyFunceble Version:** 3.2.10.dev (Teal Blauwbok: Bombardier)

## Additional context
And this is weird

```
goregrish.com    ACTIVE      12-jun-2023       WHOIS      301       
www.goregrish.com    ACTIVE      Unknown           DNSLOOKUP  301
```

If you trying to visit the address from ex tor browser `www.$domain` redirects to `$domain` so the wrong one is right and visa versa and the `www.$domain` shouldn't have HTTP code 301

**Comment by spirillen** [comment]
Found another similar with `m.$subdomain.tumblr.com`

```
m.nadasissy.tumblr.com    ACTIVE      Unknown           DNSLOOKUP  302       
m.nakedundertaker.tumblr.com    ACTIVE      Unknown           DNSLOOKUP  302       
m.nationass.tumblr.com    ACTIVE      Unknown           DNSLOOKUP  302       
m.nerd2extreme.tumblr.com    ACTIVE      Unknown           DNSLOOKUP  302       
m.nevercumalwaysedge.tumblr.com    ACTIVE      Unknown           DNSLOOKUP  302       
m.nonnudeballbusting.tumblr.com    ACTIVE      Unknown           DNSLOOKUP  302       
m.novinhasanonimas.tumblr.com    ACTIVE      Unknown           DNSLOOKUP  302       

```

I would expect 302 to be an `INACTIVE` at least for a site like tumblr under special rules for example

```
m.porngifmania.tumblr.com    INACTIVE    Unknown           SPECIAL    404       
m.pornislikeairimportant.tumblr.com    INACTIVE    Unknown           SPECIAL    404       
m.pornmustbebeautiful.tumblr.com    INACTIVE    Unknown           SPECIAL    404       

```

**Comment by funilrys** [comment]
@spirillen We actually don't follow the redirect. We may add an option for that.

**Comment by spirillen** [comment]
Yeah, but i have a idea to why the HTTP code gives a misleading response...  `http` vs `httpS`

I got the clue here <https://travis-ci.com/github/Import-External-Sources/pornhosts/builds/178282073#L2681-L2692> And about the the tumblr ones this is the case....

![image](https://user-images.githubusercontent.com/44526987/89202490-5202d100-d5b3-11ea-87a4-6373c77642bd.png)

-----

If you run the test on `goregrish.com` `--mining` you'll notice it would remove `goregrish.com` but not `www.goregrish.com` :unamused: despite both actually is active

**Comment by spirillen** [comment]
I believe there might be a lot of FN do to this issue as `http` => `httpS` on any list testing for HTTP code responses

```
curl -I http://goregrish.com
HTTP/1.1 301 Moved Permanently
Date: Mon, 03 Aug 2020 20:25:56 GMT
Content-Type: text/html
Connection: keep-alive
Set-Cookie: __cfduid=d6097f03b94d538ef1690381ef89cd34c1596486356; expires=Wed, 02-Sep-20 20:25:56 GMT; path=/; domain=.goregrish.com; HttpOnly; SameSite=Lax
Location: https://goregrish.com/
CF-Cache-Status: DYNAMIC
cf-request-id: 045799a65600001d02e9b2a200000001
X-Content-Type-Options: nosniff
Server: cloudflare
CF-RAY: 
```

-------

```
curl -I https://goregrish.com
HTTP/2 200 
date: Mon, 03 Aug 2020 20:26:03 GMT
content-type: text/html; charset=utf-8
set-cookie: __cfduid=db20d1254f90d77a2a2e9d9e238d6c0041596486362; expires=Wed, 02-Sep-20 20:26:02 GMT; path=/; domain=.goregrish.com; HttpOnly; SameSite=Lax
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
last-modified: Mon, 03 Aug 2020 20:26:03 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: private, no-cache, max-age=0
vary: Accept-Encoding
set-cookie: xf_csrf=uzqnr5g9nECwjnJu; path=/; secure
x-powered-by: PHP/5.2.13
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
referrer-policy: no-referrer-when-downgrade
content-security-policy: default-src 'self' http: https: data: blob: 'unsafe-inline'
strict-transport-security: max-age=31536000; includeSubDomains; preload
cf-cache-status: DYNAMIC
cf-request-id: 045799bf58000010ad5518f200000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 
```

**Comment by spirillen** [comment]
To make a followup comment on this after giving it some more thoughts.

## About when to follow and when not.

If a HTTP code `30x` redirects from `protocol` => `protocol` (I.E. http to httpS), the default action should be to follow the `30x` as it is quit common to have pages served over SSL these days.

If HTTP code `30x` redirects from one `$domain` to another `$domain` set result inactive, But this can actually leads to a unwanted situation.

-----

### Example:
```
curl -I 'http://www.mypdns.org'
Location: https://mypdns.org/
```

This case would return a `INACTIVE` for the `www.$domain` which is wrong as the httpS is served from `www.$domain`

While the next one, would make the `$domain` `ACTIVE` (wrong as it redirect to `www.mypdns.org`)

```
curl -I 'http://mypdns.org'
Location: https://mypdns.org/
```
-----

So this comes with a bit of a challenge to make this pussle right. However the redirects are all correct to make the CERT HSTS compliant.

Given the example, my first thoughts for how to do this, is to ad the `--mining` feature to the follow redirects to check up the final destination which should be inside the same `$domain.tld` 

The loop would need to run until it obtain a HTTP code `200` for same domain to set ACTIVE, and set other INACTIVE.

-----

When should this "Follow 30x" be used? First thought is it should be along side the `--mining` as I understand it, this is used to determine which of the domain is served by either only one or both of the `www.$domain` or `$domain` variations and only append the one that response with the HTTP code 200 to the ACTIVE lists and the other to the INACTIVE lists.

-----

`30x` codes to follow <https://en.wikipedia.org/wiki/List_of_HTTP_status_codes?wprov=srpw1_1#3xx_Redirection>
* 301 Moved Permanently
* 302 Found (Previously "Moved temporarily")
* 307 Temporary Redirect
* 308 Permanent Redirect ([RFC 7538](https://tools.ietf.org/html/rfc7538))

-----
#### Endnote

I might edit this post, If I later come up with something that could seems smarter!!

**Comment by funilrys** [comment]
Well, @spirillen nice summary. We will need that in the future as we are in a world where certificates are really cheap.

But, just to explain the `--mining` (as of 4.x), what it does is that it follow the redirect history and make sure that the given subject is not given.

For example for domain testing:
If we have `example.org ==> example.net ==> www.example.net ==> example.org` 

The mining subsystem will get `example.net` and `www.example.net` and put them into the testing queue. 
The rest is just a matter of testing.

For example for URL testing:
If we have `http://example.org ==> https://example.net ==> https://example.org` 

The mining subsystem will get `https://example.net` and `https://example.org` and put them into the testing queue.
The rest is just a matter of testing.

What the mining subsystem does, is just HTTP request and keep the tracking of all visited domains in between.

Now, you may have to test it with your own example so that you may get a better feeling of what is maybe a bit different with 4.0.0 but I think that the way I actually do it right now, is good.



----------------

Another point, that is right: We should probably put the `301` and `302` status code into the list of active status code.

**Comment by spirillen** [comment]
> Another point, that is right: We should probably put the `301` and `302` status code into the list of active status code.

Doing this, without testing the the `protocoll://` flow, you might end up with domains that actually is waste of bits.

Example:

if `http://example.org ==> https://example.net` and stops hear, then `http://example.org` is no longer an "ACTIVE" but a "PASSIVE" and for some projects, it might be unnecessary bits for the end-results (Here I'm i.e. thinking of @jawz101 @adaway project, wko like to keep it as small as possible)

I'll give it a spin, and will get back to this one, when the 
```
pyfunceble -h -a -dbr 0 -d mypdns.org --mining

Starting migration (json2csv) of the inactive dataset.
Starting migration (json2csv) of the whois dataset.
```

Is done migrating non existing files :imp: :open_mouth:

**Comment by funilrys** [comment]
@spirillen, those 2 lines are only given if the `inactive_db.json` and/or `whois_db.json` are found in your configuration directory.

**Comment by spirillen** [comment]
> @spirillen, those 2 lines are only given if the `inactive_db.json` and/or `whois_db.json` are found in your configuration directory.

Yep, as mentioned here: keybase://chat/spirillen,funilrys/1969 I was just lost a minutes :)

**Comment by funilrys** [comment]
@spirillen, is this still actual after all those changes?

**Comment by spirillen** [comment]
Well, I have never seen any HTTP reponse code in 4.x :smirk: 

![image](https://user-images.githubusercontent.com/44526987/115967449-fe665800-a532-11eb-8e4c-c232f138e81c.png)

![image](https://user-images.githubusercontent.com/44526987/115967483-25248e80-a533-11eb-9d79-7592e8359174.png)

Test string:
```
pyfunceble -w 20 -a --hierarchical -ex --output-location /tmp/pyfunceble4/adaway -f https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt -c
```

Most admit, I've forgot to follow up on this as we spoke of this some time before Christmas.

Am I doint something wrong??

New test string:
```
pyfunceble -w 1 -a --hierarchical -ex --output-location /tmp/pyfunceble4/adaway -f https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt -c --http --database-type mariadb
```

Result:
(Save for back, neeeeeeeeeeeeeeeeeeeeeeeed to go AFK for a moment)

**Comment by funilrys** [comment]
Nope, you are not doing something wrong. 4.x is different.

In the past, I used to do some unnecessary query and do the evaluation at the end.

In 4.x It's like this (if enabled).

```
WHOIS ==> NSLOOKUP ==> NETINFO ==> REPUTATION ==> HTTP Status code
```

So first, it tries to switch to a positive status with the WHOIS. If not positive it tries with DNSLOOKUP, if not positive it tries with NETINFO. If not positive it tries with REPUTATION. If not positive it tries to communicate through the HTTP protocol.

And of course at the real end (independent of the status in the STDLOOKUP), there the SPECIAL rules handler that can escalate (INACTIVE ==> ACTIVE) or escalate the status (ACTIVE ==> INACTIVE)

In the end-effect, under 4.x, the only place where the HTTP status code plays a big role is when testing URL (not 2nd+ level domain).

Of course we can discuss the test order, but that's how it is right now for the availability check of domain (not URL).

**Comment by spirillen** [comment]
> `WHOIS ==> NSLOOKUP ==> NETINFO ==> REPUTATION ==> HTTP Status code`

This is actually super and saves a lot of lookup, however as i sees it, how should you get an HTTP response if you did not get a DNS response :smirk:  Is this related to the https://www.mypdns.org/T1271?

**Comment by funilrys** [comment]
Indeed @spirillen,  it's the result of weird behaviors in the past.

**Comment by funilrys** [comment]
@spirillen, please read the commit before saying that something is not as you described :wink:

**Comment by spirillen** [comment]
> @spirillen, please read the commit before saying that something is not as you described wink

:rofl: actually did :smirk: see my note in the commit, the code seems fully HSTS compliant (https://mypdns.org/pyfunceble/PyFunceble/-/commit/d4b67bdf971cd57d7ba52bdf26d3dcf0e15233b9#3cb77bda9a41e7e0a31a779f30b7012b487e7314_477_600)

**Comment by spirillen** [comment]
:BUHUU: :bug: 

`requests.exceptions.TooManyRedirects: Exceeded 30 redirects.`

Source:
  - https://github.com/mypdns/porn-records/runs/2924212453?check_suite_focus=true#step:10:5092
  - https://github.com/mypdns/porn-records/runs/2923129154?check_suite_focus=true#step:10:5091
  - https://github.com/mypdns/porn-records/runs/2923340642?check_suite_focus=true#step:10:5091
  - https://github.com/mypdns/porn-records/runs/2923353903?check_suite_focus=true#step:10:5092
  - https://github.com/Clefspeare13/pornhosts/runs/2923719581?check_suite_focus=true#step:7:66
  - https://github.com/Clefspeare13/pornhosts/runs/2924389608?check_suite_focus=true#step:7:66
  - https://github.com/Clefspeare13/pornhosts/runs/2925135558?check_suite_focus=true#step:7:66

**Comment by funilrys** [comment]
That's a new bug ... unrelated to the patch I pushed ...
