### ISSUE TITLE
pip pyfunceble-dev fails

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#111]
## Bug description
Using `pip -q install --no-cache-dir -U pyfunceble-dev` make pyfunceble failing

![image](https://user-images.githubusercontent.com/44526987/91624833-ceb28080-e9a2-11ea-943b-c2bba568ae55.png)

Using `pip -q install --no-cache-dir -U git+https://github.com/funilrys/PyFunceble@dev` is working as expected...

## Modifications under `.PyFunceble.yaml`

None

## Reproduction

See bug description

## Expected behavior
Really :smile: 

## Screenshots

<details><summary>NOT Working</summary>

![image](https://user-images.githubusercontent.com/44526987/91624780-87c48b00-e9a2-11ea-926c-f9dd4b4f8b58.png)

![image](https://user-images.githubusercontent.com/44526987/91624793-94e17a00-e9a2-11ea-8e17-e80c6d2c2652.png)

</description>

<details><summary>Working</summary>

![image](https://user-images.githubusercontent.com/44526987/91624762-68c5f900-e9a2-11ea-93f4-1d4f12ef3951.png)

</description>

## Versions

**OS:** MiniConda
**Python Version:** for example 3.8.5
**PyFunceble Version:** 3.2.11-dev

## Additional context
See Ci logs at 

1. <https://travis-ci.com/github/Import-External-Sources/pornhosts/builds/181874447>

2. <https://travis-ci.com/github/Import-External-Sources/pornhosts/builds/181874061>

**Comment by funilrys** [comment]
I can't reproduce @spirillen.

**Comment by spirillen** [comment]
Hmm will give it a try tomorrow, it can had been a cache issue from pip as it was close to the release

**Comment by spirillen** [comment]
Closing this as a pip cache issue, as we have seen before...
You version bump from .11 to .12 also seems to have done it :smiley:
