### ISSUE TITLE
SQL pyfunceble_mined (@dev)

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#121]
## Bug description
`pyfunceble_mined` isn't storing full source in the `path`

IE: testing `https://raw.githubusercontent.com/Clefspeare13/pornhosts/868bb510004902d6df1d4b7d32b009c56a7cb984/0.0.0.0/hosts` is stored as `hosts`

## Modifications under `.PyFunceble.yaml`

None

## Reproduction

```
pyfunceble -h --plain -db --database-type mariadb -f https://raw.githubusercontent.com/Clefspeare13/pornhosts/868bb510004902d6df1d4b7d32b009c56a7cb984/0.0.0.0/hosts --dns 127.0.0.1:53 192.168.1.105 --mining
```

View the table from above

|id|created|modified|path|test_completed|
|--|-------|--------|----|--------------|
|1|2020-09-19 20:02:48|2020-09-19 20:44:26|/some/local/file/path/wildcard.list|1|
|2|2020-09-19 21:57:36|2020-09-19 21:57:36|hosts|0|

## Expected behavior
Expected that the full source of tested file would store in the `path` as either file-path (it does) or full url (does not)

If we only store the file name of a source, then all `protocoll://some/path/hosts` would be linked as one source

## Versions

**OS:** MiniConda
**Python Version:** 3.8.5
**PyFunceble Version:** 3.3.3.dev (Teal Blauwbok: Tick)

## Additional context
This also touches my previous thought on how to link several sources as same source. IE: file path 1 = file path 2 and urls

**Comment by funilrys** [comment]
The table in question is completely deleted as mentioned at https://github.com/funilrys/PyFunceble/issues/118#issuecomment-748593568
