### ISSUE TITLE
PYFUNCEBLE_DEBUG_ON_SCREEN: true|false

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#130]
## Bug description
If you append `PYFUNCEBLE_DEBUG_ON_SCREEN: false` to `.travis.yml` it is still picked up as `PYFUNCEBLE_DEBUG_ON_SCREEN: true`

With Conda locally enabled `PYFUNCEBLE_DEBUG_ON_SCREEN` isn't picked up

## Modifications under `.PyFunceble.yaml`
None

## Reproduction
See error description

Local focal+ conda
```
(pyfunceble-dev) :~$ PYFUNCEBLE_DEBUG_ON_SCREEN=true
(pyfunceble-dev) :~$ pyfunceble -d mypdns.org mypdns.com
^C
Thanks for using PyFunceble!
Share your experience on Twitter with #PyFunceble!
Have a feedback, an issue or an improvement idea?
Let us know on GitHub!
(pyfunceble-dev) :~$ pyfunceble -d mypdns.org mypdns.com -db --database-type mariadb

Subject                                                                                              Status      HTTP Code 
---------------------------------------------------------------------------------------------------- ----------- ----------
mypdns.org                                                                                           ACTIVE      XXX       
mypdns.com                                                                                           ACTIVE      XXX       


## Expected behavior
`PYFUNCEBLE_DEBUG_ON_SCREEN:` would have been disabled

## Screenshots
<https://travis-ci.com/github/dns-test/PyFunceble-Sandboxed/jobs/406360280/config>

## Versions

**OS:** Ubuntu 20.04 Focal + Conda
**Python Version:** 3.9.0
**PyFunceble Version:** 3.3.7.dev

## Additional context
Nope

**Comment by funilrys** [comment]
Note to self: Verify if this still happens with 4.x.

**Comment by funilrys** [comment]
Note to self: Because 4.0.0 includes a logging level filter, we should also add the environment variable for it.

**Comment by spirillen** [comment]
Can you exposes the syntax?

**Comment by funilrys** [comment]
There is the already known `--debug` argument (or it's environment variable counterpart)  to activate the logging globally.
But as of 4.0 it will only print all `INFO` logging. If you want to change it you need to do add:

- `--logging-level info` ==> INFO (default)
- `--logging-level debug` ==> DEBUG
- `--logging-level warning` ==> WARNING
- `--logging-level error` ==> ERROR
- `--logging-level critical` ==> CRITICAL

**Comment by spirillen** [comment]
Super, will add to my todo list for testing

**Comment by spirillen** [comment]
Appendix:

The `--logging-level` are not shown within the `--help` let consider if this should be the case!!

**Comment by funilrys** [comment]
This is done on purpose @spirillen. If you search `argparse.SUPPRESS` (from a clone of the `4.0.0-dev` branch), you will get the list of arguments that are hidden.

**Comment by spirillen** [comment]
That's OK, but as the docs not yet is public available, I was putting it into the think-tank :smiley: 

Just tested the logging vs the central DB

```
--logging-level info ==> INFO (default)
--logging-level debug ==> DEBUG
```

The do not produce any output for the following actions

```
[2020-12-21 13:43:47,259::INFO::/$home/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/threads/migrator.py:279@target](PID139903070435072:pyfunceble_migrator): Submitted 'mining_file_cleanup_target'
Starting migration of the pyfunceble_file and pyfunceble_status tables.
Starting completion of NULL idna_subject(s) into the whois dataset.
```

Which I would have expected to actually see what is happening...

**Comment by funilrys** [comment]
Should be now fixed.

**Comment by funilrys** [comment]
Closing. Feel free to test and reopen if not fixed or if necessary.

**Comment by spirillen** [comment]
Please put to the retest project I suggested.... all engines are busy

**Comment by funilrys** [comment]
@spirillen Done.

**Comment by spirillen** [comment]
Super, thanks

**Comment by spirillen** [comment]
Completed

TEST: OK
