### ISSUE TITLE
`-db` `--database-type`

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#131]
**Describe the solution you'd like**
1. Strip the `--databse-type` as when you uses `-db` you are already telling the system to use a DB connector.
2. Replace `mariadb | mysq l json` with `sql|json` as the sqlachademy make the choice

**Comment by funilrys** [comment]
@spirillen, if we want to add  PostgreSQL or other connector, your solution make it hard to dispatch.

**Comment by funilrys** [comment]
I added a restriction to the `--database-type` argument. So, as per 4.0 you can only choose from one of the given one. 

Note: `json` is now gone and should be replaced with `csv` (as per 4.0).

**Comment by spirillen** [comment]
What about changing it to

`mysql | csv`

and then later IF

`csv | mysql | pgsql`

??

It not a big thing, it just seems ort to specify the same SQL syntaxing

**Comment by funilrys** [comment]
You are right, but I don't want to create a rather biased discussion as soon as `mysql` will be removed.

In fact, under the hood, all the MySQL related code are just an extension (with nothing more) of the MariaDB related source code. For me, the discussion between `mariadb` over `mysql` for unification or vice-versa is rather more a "display" issue than something else. 

The reason, it is still explicitly in the source through, that I have to plan ahead. Therefore, as we don't know if we are going to have a special issue related to MySQL, I chose to just keep it ready for expansion (in a corner of the source code). 😄

**Comment by spirillen** [comment]
The question would then be, should proletarian software be supported in the future?

But as you say, it mostly for the eye and it could be misleading for newbies

**Comment by funilrys** [comment]
Well, millions of people use MySQL as it is one `apt install` away for your machine. I'm not ready yet to pay a license for another DB engine so that we can implement it. But, if one day someone has the resource, I'll be glad to accept and review their PR. But it won't come from me (at least not with my current resources and time). 

Let's just keep it. It won't harm anybody.
