### ISSUE TITLE
Chalanging HTTP status code 403

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#133]
**Is your feature request related to a problem? Please describe.**
When you are doing the http code status test, it have come to my attention, that if we uses the 403 (access denied) as 403 is only saying the ip address from x.x.x.x is not allowed here

https://github.com/funilrys/PyFunceble/blob/3ee3b1701c22e3289c19a03224e4b73bf1e7be62/.PyFunceble_production.yaml#L249-L254

I therefore believe it default only should be in the `potentially_up:` section

https://github.com/funilrys/PyFunceble/blob/3ee3b1701c22e3289c19a03224e4b73bf1e7be62/.PyFunceble_production.yaml#L260-L270

**Comment by funilrys** [comment]
Good to me too.
