### ISSUE TITLE
ModuleNotFoundError: No module named 'PyFunceble.cli.continuous_integration.funilrys_dev'

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#137]
First issue goes to the `sqlalchemy` connection error.

Error log: <https://travis-ci.com/github/dns-test/PyFunceble-Sandboxed/builds/209863452>

The second error goes to the http test, same log as above

**Comment by funilrys** [comment]
@spirillen:

```
$ pyfunceble --version
pyfunceble 3.3.7.dev (Teal Blauwbok: Gander)
```

Source: https://travis-ci.com/github/dns-test/PyFunceble-Sandboxed/builds/209863452#L2388

**Comment by spirillen** [comment]
LOL didn't see that :smile: :laughing: 

But why did it install version 3 and not 4????

**Comment by spirillen** [comment]
Found... 

https://github.com/dns-test/PyFunceble-Sandboxed/blob/542b5e7b6243b7540cc1591d93d22ca5ffacde38/.travis.yml#L44

**Comment by spirillen** [comment]
Seeing the same issue in conda on both my local machines

https://travis-ci.com/github/dns-test/PyFunceble-Sandboxed/builds/209935807#L2395

```
Traceback (most recent call last):

  File "/home/travis/miniconda/envs/test-environment/bin/pyfunceble", line 5, in <module>

    from PyFunceble.cli.entry_points.pyfunceble.cli import tool

  File "/home/travis/miniconda/envs/test-environment/lib/python3.9/site-packages/PyFunceble/cli/entry_points/pyfunceble/cli.py", line 64, in <module>

    from PyFunceble.cli.system.launcher import SystemLauncher

  File "/home/travis/miniconda/envs/test-environment/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py", line 75, in <module>

    from PyFunceble.cli.continuous_integration.utils import ci_object

  File "/home/travis/miniconda/envs/test-environment/lib/python3.9/site-packages/PyFunceble/cli/continuous_integration/utils.py", line 54, in <module>

    from PyFunceble.cli.continuous_integration.funilrys_dev import FunilrysDevCI

ModuleNotFoundError: No module named 'PyFunceble.cli.continuous_integration.funilrys_dev'

The command "pyfunceble --version" failed and exited with 1 during .
```

**Comment by funilrys** [comment]
Okay, that one is a real issue :-)

**Comment by funilrys** [comment]
Please restart the job. It should be fixed now.

**Comment by spirillen** [comment]
On ubu

pyfunceble --version
pyfunceble 4.0.0a6.dev (Blue Duckling)

**Comment by spirillen** [comment]
New issue arised :unamused: https://travis-ci.com/github/dns-test/PyFunceble-Sandboxed/builds/209947384#L2396-L2417

**Comment by funilrys** [comment]
@spirillen where is your `DB_CHARSET` variable declared? I can't find any 🤔

**Comment by funilrys** [comment]
Source: https://travis-ci.com/github/dns-test/PyFunceble-Sandboxed/builds/209947384#L185

**Comment by spirillen** [comment]
> @spirillen where is your `DB_CHARSET` variable declared? I can't find any thinking

https://github.com/dns-test/PyFunceble-Sandboxed/blob/718de91f59fbb6bf1208182757bd35ddc66f8f2a/.travis.yml#L21

**Comment by funilrys** [comment]
What I meant:

You have:
https://github.com/dns-test/PyFunceble-Sandboxed/blob/718de91f59fbb6bf1208182757bd35ddc66f8f2a/.travis.yml#L21

```
PYFUNCEBLE_DB_CHARSET="${DB_CHARSET}"
```

But the `DB_CHARSET` variable is missing somehow...

**Comment by spirillen** [comment]
You are actually right.... just weird where it had gone wrong... but I somehow managed to get it renamed between previously runs :thinking: 

So let's see in https://travis-ci.com/github/dns-test/PyFunceble-Sandboxed/builds/210062094

**Comment by funilrys** [comment]
@spirillen, no I don't have access.

**Comment by funilrys** [comment]
Please review and accept my PR to your repository @spirillen.

**Comment by funilrys** [comment]
Closing. I suppose that everything will be fixed in your next test.

Feel free to test and reopen if it's not fixed or if necessary.

**Comment by spirillen** [comment]
:rofl: 

https://travis-ci.com/github/dns-test/PyFunceble-Sandboxed/builds/210346284#L1709 :speak_no_evil:

**Comment by funilrys** [comment]
My bad.

**Comment by funilrys** [comment]
@spirillen Fixed. Thanks for the Sandbox.

**Comment by spirillen** [comment]
Your welcome :wave:
