### ISSUE TITLE
No ouput after x Minutes under CI.

### ISSUE THREAD

**Issue by funilrys** [funilrys/PyFunceble#138]
Under Travis-ci there is a common error which I'm wondering about where is happening.

Using the central  DB to store the test results, however, on several CI's the following error occur

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
```

Links to a couple of the affected CI's:
  - https://travis-ci.com/github/dns-test/rpz.mypdns.cloud
  - https://travis-ci.com/github/dns-test/adult.mypdns.org
  - https://travis-ci.com/github/dns-test-26-30
  - https://travis-ci.com/github/DNS-test-01-05
  - https://travis-ci.com/github/DNS-test-36-40
  - https://travis-ci.com/github/dns-test-31-35

I have tried to activate the `- PYFUNCEBLE_DEBUG_ON_SCREEN: true` but log lines became to many, and the build failed before reviling the eventual error.

_Originally posted by @spirillen in https://github.com/funilrys/PyFunceble/issues/123#issuecomment-699479186_

**Comment by funilrys** [comment]
We should keep an eye on this. @spirillen: Please let me know here if this is happening again with any non-3.x versions.

**Comment by spirillen** [comment]
Could you add me to the `assigned` for updates?

**Comment by funilrys** [comment]
Unfortunately not because you are not the author of this. Will be done once I moved this repository to @PyFunceble.

**Comment by funilrys** [comment]
Closing. Because I assume that this is solved.  Feel free to reopen or create a new issue.
