### ISSUE TITLE
PyFunceble does not support the `\032` spearator.

### ISSUE THREAD

**Issue by funilrys** [funilrys/PyFunceble#139]
Another bug:

PyFunceble does not find all bad entries in a file.

Example for not found invalid entries: 

```js
0.0.0.0 140.82.32.54\032discord.actinium.org
0.0.0.0 140.82.32.54\032fastpool.actinium.org
0.0.0.0 140.82.32.54\032explorer.actinium.org
0.0.0.0 140.82.32.54\032faucet.actinium.org
0.0.0.0 140.82.32.54\032ln-explorer.actinium.org
0.0.0.0 140.82.32.54\032test-explorer.actinium.org
0.0.0.0 140.82.32.54\032transfer.actinium.org
0.0.0.0 140.82.32.54\032www.discord.actinium.org
```

_Originally posted by @ZeroDot1 in https://github.com/funilrys/PyFunceble/issues/123#issuecomment-722642763_

**Comment by funilrys** [comment]
Thanks for reporting this  @ZeroDot1.

**Comment by funilrys** [comment]
Note to self: More to read about `\032` in the [RFC6763](https://tools.ietf.org/html/rfc6763).

**Comment by funilrys** [comment]
Closing. Feel free to test and let me know if it is not working.

cc @spirillen @ZeroDot1

**Comment by spirillen** [comment]
Please add to a re-test project.. CPU's still tied up

**Comment by funilrys** [comment]
@spirillen done.

**Comment by spirillen** [comment]
Completed

TEST: OK
