### ISSUE TITLE
4.0.0a7 --no-file + --dbr

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#142]
## Bug description
Adding the `--no-file` still produces output files, this is unexpected behaviour

 ```bash
/tmp/pyfunceble4/1238
└── /tmp/pyfunceble4/1238/output
    └── /tmp/pyfunceble4/1238/output/test.list
        ├── /tmp/pyfunceble4/1238/output/test.list/counter.json
        └── /tmp/pyfunceble4/1238/output/test.list/logs
            └── /tmp/pyfunceble4/1238/output/test.list/logs/percentage
                └── /tmp/pyfunceble4/1238/output/test.list/logs/percentage/percentage.txt
```

The `--dbr 0` was not respected and the test failed to retest NON-ACTIVE records, See dump + <https://github.com/PyFunceble/ci_test/blob/master/test.list>

I would have expected a full retest of ALL records from source with the `0` set

## Modifications under `.PyFunceble.yaml`

None

## Reproduction

1. Use <https://github.com/PyFunceble-Templates/pyfunceble-miniconda/blob/master/pyfunceble4.sh>
2. Run with `./pyfunceble4.sh 'https://raw.githubusercontent.com/spirillen/ci_test/patch-2/test.list'`
3. With the following variable: `-dbr 0 -ex --dns 192.168.1.104:53 127.0.0.1 192.168.1.53:5302 -w 6 -h --plain -a --hierarchical --database-type mariadb --no-file`

## Expected behavior
No output files, what so ever, as it is running with the `--datase-type` directive

## Screenshots
![image](https://user-images.githubusercontent.com/44526987/102776584-43b12800-438f-11eb-82fc-8b89477ee802.png)

## Versions

**OS:** Ubuntu 20.04 + Conda
**Python Version:** 3.9.0
**PyFunceble Version:** 4.0.0a7

**Comment by spirillen** [comment]
APPENDIX 1:

As I was working on #130 It strikes me at we should leave a exeption to no output at all... the logging IF = TRUE should of curse always generate it's log files...

**Comment by funilrys** [comment]
I like your script output hahaha. Will be fixed.

**Comment by funilrys** [comment]
Just a notice about this. The `counter.json` file is needed to generate the `percentage.txt` file at the real end. 

Meaning that if one will use the `--no-file`, no percentage will be generated either.

**Comment by funilrys** [comment]
Closing so that I can get an overview of what is fixed. 

Please test and reopen if still not fixed.

**Comment by spirillen** [comment]
Please add to a re-test project.. CPU's still tied up

**Comment by spirillen** [comment]
if `--dbr` > `0` all ACTIVE records gets retested straight up

> `-dbr` "something" | --days-between-db-retest "something"
>
>    Sets the numbers of days since the introduction of a subject into the inactive dataset before it gets retested.

![image](https://user-images.githubusercontent.com/44526987/102996603-ae936800-4523-11eb-9532-265f74d86560.png)

Unless I have misunderstood the purpose of the dbr, then `--dbr 6` should have nothing to test on this second run as dbr = 6 (days)

**Comment by spirillen** [comment]
> Just a notice about this. The `counter.json` file is needed to generate the `percentage.txt` file at the real end.
> 
> Meaning that if one will use the `--no-file`, no percentage will be generated either.

:thought_balloon: :thinking: maybe throw the `counter.json` in `$TEMP`  it is usual nice to see it, maybe combine it with `--percentage` = `--percentage --no-file` ? :thought_balloon: 

Note to self + funilrys, remember to add this to <https://pyfunceble.readthedocs.io/en/4.0.0-dev/usage/from-a-terminal.html?highlight=dbr#no-files>

**Comment by spirillen** [comment]
DBR > 0 still retest all, the following records was last successfully tested 4 days ago.

```bash
--share-logs -dbr 6 -ex --dns 192.168.1.104:53 -w 6 --database-type mariadb --no-files --wildcard   
Would you like to use your default pyfunceble enviroment
  /$HOME/miniconda/envs/pyfunceble4?: [Y/n] Y
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

pyfunceble 4.0.0a33.dev (Blue Duckling)
uhb-whitelist 3.25.0
pyfunceble 4.0.0a33.dev (Blue Duckling)

.

Subject                                                                                              Status      Source    
---------------------------------------------------------------------------------------------------- ----------- ----------
0.0.0.0.0.0.0.0.0.y.free.fr                                                                          ACTIVE      DNSLOOKUP 
0.0.0.0.001.free.fr                                                                                  ACTIVE      DNSLOOKUP 
0.0.0.0.0.0.0.0.0.x.free.fr                                                                          ACTIVE      DNSLOOKUP 
0.0.0.0.0.0.0.0.0z1.free.fr                                                                          ACTIVE      DNSLOOKUP 
0.0.0.0.0.0.0.0.chat.free.fr                                                                         ACTIVE      DNSLOOKUP 
0.0.0.0.002.free.fr                                                                                  ACTIVE      DNSLOOKUP 
0.0.0.006.free.fr                                                                                    ACTIVE      DNSLOOKUP 
0.0.0.0.00.free.fr                                                                                   ACTIVE      DNSLOOKUP 
0.0.0.005.free.fr                                                                                    ACTIVE      DNSLOOKUP 
0.0.0.0071.free.fr                                                                                   ACTIVE      DNSLOOKUP 
0.0.0.0.09.free.fr                                                                                   ACTIVE      DNSLOOKUP 
0.0.0.008.free.fr                                                                                    ACTIVE      DNSLOOKUP 
0.0.0.009.free.fr                                                                                    ACTIVE      DNSLOOKUP 
0.0.0.0.0.rencontre.free.fr                                                                          ACTIVE      DNSLOOKUP 
00000nwebcamnow.com                                                                                  ACTIVE      WHOIS     
0.0000sex.com                                                                                        ACTIVE      DNSLOOKUP 
0000.1.free.fr                                                                                       ACTIVE      DNSLOOKUP 
0000114.com                                                                                          ACTIVE      WHOIS     
000069.com                                                                                           ACTIVE      WHOIS     
0001011.com                                                                                          ACTIVE      WHOIS     
0001casino.com                                                                                       ACTIVE      WHOIS     
000111casino.com                                                                                     ACTIVE      WHOIS     
0.0.04.free.fr                                                                                       ACTIVE      DNSLOOKUP 
0005.us                                                                                              ACTIVE      WHOIS     
000adultfantasy.com                                                                                  ACTIVE      WHOIS     
000ahlalorrainesexe.free.fr                                                                          ACTIVE      DNSLOOKUP 
00069maninstockings.over-blog.com                                                                    ACTIVE      DNSLOOKUP 
^C
```

**Comment by funilrys** [comment]
@spirillen Mhh we may have to rename that flag. 

DBR actually means: Retest all non `ACTIVE` (related to the current file and test mode) which are in the database for X days.

**Comment by spirillen** [comment]
Hmm it would be cool if we had one that "stalled" all lately tested. to avoid re-testing what was tested 2 minutes ago

**Comment by spirillen** [comment]
I believe you can close this issue (for now) as I've moved the question to <https://github.com/funilrys/PyFunceble/discussions/168>

**Comment by spirillen** [comment]
Ups, had forgotten <https://github.com/funilrys/PyFunceble/issues/142#issuecomment-750275863>
