### ISSUE TITLE
--display-status choose more than one

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#153]
See https://github.com/funilrys/PyFunceble/issues/43#issuecomment-751241980

**Comment by spirillen** [comment]
The test as such is good, however the one test performed with a comma separated selection failed.

I tested this as it should be considered a widely chosen way to separate multiply selection.

Yes wrong from a bash argument perspective, but yet!

<https://travis-ci.com/github/dns-test/PyFunceble-Sandboxed/builds/210630098>

According to that, we have no more travis for the rest of the year :unamused: 

![image](https://user-images.githubusercontent.com/44526987/103162091-c3a21c80-47eb-11eb-820e-9d30c2a44971.png)

**Comment by funilrys** [comment]
It is documented: Space-separated 😉  But let me reopen this.

-----------------------

@spirillen Look at your setting is "OSS consume credit" activated too by default? I don't have time for their joke but one should ask their support why they are doing that and if there is a way to solve the issue. 

I mean, they are still stating that open source projects will still be free. What they are doing is stupid.
Now I wanted to look to check if the "OSS consume credit" phrase was correct but look:

![2020-12-27_13-31](https://user-images.githubusercontent.com/14127285/103170866-04c81a00-4848-11eb-90e8-e331562a7b0d.png)

**Comment by spirillen** [comment]
I'm into the same, I sick of them, but all credits are gone, just have a look at <https://github.com/spirillen/ublockorigin-rules/commit/7f1e24b123f6836dcac06e35c64997b7dd80a306>, <https://github.com/mypdns/matrix/commit/7d64617c3e4b7db558d94676404df189051856b3> & <https://github.com/mypdns/porn-records/commit/8b0b14038a9f49cbd4c176559a526ebb83355cfe>   They are not processed at all

In short as we spoke of here <https://www.mypdns.org/file/info/PHID-FILE-hkatjos2rusxt676v2mq/> and here <https://www.mypdns.org/file/info/PHID-FILE-grffrmdzicwbayalngju/>

keybase://chat/spirillen,funilrys/2199

**Comment by spirillen** [comment]
Clicking on <https://travis-ci.com/organizations/dns-test/plan?anchor=oss-consumption> =

![image](https://user-images.githubusercontent.com/44526987/103171254-07783e80-484b-11eb-9ef8-213ecf3500f9.png)

But access them directly shows this

![image](https://user-images.githubusercontent.com/44526987/103171267-32fb2900-484b-11eb-8370-5569ced2e480.png)

![image](https://user-images.githubusercontent.com/44526987/103171281-4ad2ad00-484b-11eb-9a81-f53513a607ad.png)
![image](https://user-images.githubusercontent.com/44526987/103171297-60e06d80-484b-11eb-8667-7ac32ca96c1c.png)
![image](https://user-images.githubusercontent.com/44526987/103171304-76ee2e00-484b-11eb-99b3-6acd68eef848.png)

> You can use paid credits both for build jobs run over public and private repositories. You can use ‘OSS only’ credits only for build jobs run over public repositories. If the ‘Consume paid credits for OSS’ is set to OFF, paid credits will not be used for build jobs run over public repositories. ‘OSS only credits’ are available and renewed as per terms of selected plan. 

![image](https://user-images.githubusercontent.com/44526987/103171334-c5033180-484b-11eb-8d13-d46afd2474d9.png)

As you can see we should ditch testing on MacOS and Windows in the future, they are way way way overpriced.

And even if we sticks to linux, we only have 1000 started minutes, or ~16 hours of total testing per month.

Even if someone should sponsor any of there plans, we will save more money setting up out test at hetzner and better of, thanks to there yml config luncher

![image](https://user-images.githubusercontent.com/44526987/103171417-64282900-484c-11eb-818d-bf9f3a1c36a8.png)

**Comment by funilrys** [comment]
"Consume paid credit for OSS" shouldn't be activated by default. What we do is just OSS 🤢

**Comment by spirillen** [comment]
Let me try to disable it....

**Comment by spirillen** [comment]
No changes this month.... :sob:

**Comment by funilrys** [comment]
Not worth the time (supporting `,` separated status). 

Closing. People will have to live with the space separated.

**Comment by spirillen** [comment]
TEST OK

```
-display-status inactive invalid
Would you like to use your default pyfunceble enviroment
  /home/joakim/miniconda/envs/pyfunceble4?: [Y/n] Y
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

pyfunceble 4.0.0a35.dev (Blue Duckling)
uhb-whitelist 3.25.0
pyfunceble 4.0.0a35.dev (Blue Duckling)

██████╗ ██╗   ██╗███████╗██╗   ██╗███╗   ██╗ ██████╗███████╗██████╗ ██╗     ███████╗
██╔══██╗╚██╗ ██╔╝██╔════╝██║   ██║████╗  ██║██╔════╝██╔════╝██╔══██╗██║     ██╔════╝
██████╔╝ ╚████╔╝ █████╗  ██║   ██║██╔██╗ ██║██║     █████╗  ██████╔╝██║     █████╗
██╔═══╝   ╚██╔╝  ██╔══╝  ██║   ██║██║╚██╗██║██║     ██╔══╝  ██╔══██╗██║     ██╔══╝
██║        ██║   ██║     ╚██████╔╝██║ ╚████║╚██████╗███████╗██████╔╝███████╗███████╗
╚═╝        ╚═╝   ╚═╝      ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚══════╝╚═════╝ ╚══════╝╚══════╝



Subject                                                                                              Status      Source    
---------------------------------------------------------------------------------------------------- ----------- ----------
000000000000000sexe.free.fr                                                                          INACTIVE    STDLOOKUP 
000001.skynetblogs.be                                                                                INACTIVE    STDLOOKUP 
0.0.0.0.0.sexeporn.free.fr                                                                           INACTIVE    STDLOOKUP 
0000adultsex.com                                                                                     INACTIVE    STDLOOKUP 
0.0.0.0.amateursexe.free.fr                                                                          INACTIVE    STDLOOKUP 
0.0.0.0.analsexe.free.fr                                                                             INACTIVE    STDLOOKUP 
0.0.0.0.analsex.free.fr                                                                              INACTIVE    STDLOOKUP 
0.0.0.0.sexamateur.free.fr                                                                           INACTIVE    STDLOOKUP 
0000livesex.dk                                                                                       INACTIVE    STDLOOKUP 
0000-sex.dk                                                                                          INACTIVE    STDLOOKUP 
0.0.0.0.sexeamateur.free.fr                                                                          INACTIVE    STDLOOKUP 
0000-sex-pics.com                                                                                    INACTIVE    STDLOOKUP 
000222casino.com                                                                                     INACTIVE    STDLOOKUP 
000abcsex.free.fr                                                                                    INACTIVE    STDLOOKUP 
0-0-0-animalsex.dk                                                                                   INACTIVE    STDLOOKUP 
*.000iblogchix.blogspot.ae.porn.host.srv.                                                            INVALID     SYNTAX    
000iblogchix.blogspot.ae.porn.host.srv.                                                              INVALID     SYNTAX   
```
