### ISSUE TITLE
Very slow --syntax --database-type mariadb

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#154]
## Bug description
If you combine `--syntax --database-type mariadb` the process is very very slow :unamused: 

## Modifications under `.PyFunceble.yaml`

None

## Reproduction

https://travis-ci.com/github/dns-test/PyFunceble-Sandboxed/jobs/464797195

https://travis-ci.com/github/dns-test/PyFunceble-Sandboxed/jobs/464797196

## Expected behavior
Just as fast as `--syntax` without `--database-type` connection

**Comment by funilrys** [comment]
Can you record a short session (without any debug) so that I can see what you mean? I use https://asciinema.org/ for such cases

**Comment by spirillen** [comment]
LOL `https://asciinema.org/` is using a blocked resource, not that I can remember which :unamused: 

But we have a super invention on nix... `time` :laughing: 

Updating this reply once completed a local test

**Comment by funilrys** [comment]
Hey, @spirillen want to play a game? 

Do this:

1. copy this patch into a file in your filesystem:

```
diff --git a/PyFunceble/cli/threads/producer.py b/PyFunceble/cli/threads/producer.py
index 0b5eb75..fb3be29 100644
--- a/PyFunceble/cli/threads/producer.py
+++ b/PyFunceble/cli/threads/producer.py
@@ -370,6 +370,11 @@ class ProducerThread(ThreadsBase):
 
             consumed = self.the_queue.get()
 
+            print(
+                "In the queue (waiting for filter or file+stdout generation):",
+                self.the_queue.qsize(),
+            )
+
             PyFunceble.facility.Logger.debug("Got: %r", consumed)
 
             if consumed == "stop":
```

2. Re-Clone PyFunceble, move to the `4.0.0-dev` branch, switch to the latest commit (as of now), apply the patch, and run PyFunceble against the same dataset 😉 

```
$ git clone [Pyfuncebl]
$ cd [pyfunceble-new-clon-dir]
$ git checkout 4.0.0-dev
$ git reset --hard 6ea2c68366fa069c22d27587417c66e1cc03553f
$ git log -1 # If you want to see the last commit message
$ git apply [path_to_patch]
$ pip install --upgrade -e .  # Install PyFunceble (with our patch)
$ [run pyfunceble (your huge dataset)] + [look at the screen at the same time]
```

What do you see? 😄

**Comment by spirillen** [comment]
Still on first cop of sod soo

speed?

**Comment by funilrys** [comment]
Yes and no. Read how much is waiting in the queue :wink:

**Comment by spirillen** [comment]
Patch format detection failed.

**Comment by funilrys** [comment]
Just to explain for those wondering.: 

![efe](https://raw.githubusercontent.com/PyFunceble/draw.io/master/dist/Thread_Model_PyFunceble_CLI.png)

Right now, when a single test is done, it submits to the producer thread (single thread) which works sequentially. Meaning that right now (for your example) if you apply the patch you will see that the tester is actually so fast that the producer is not following.

The reasons behind:
- The producer threads reads it's queue sequentially, generate the files, and print to stdout. 
- The file generation (IO Bound) is taking a bit of time (a few milliseconds).

My solution: Move the stdout printer into its own thread. Meaning that you won't get the feeling that it is slow but you will still have to wait a bit because the file generation will stay behind. 

I'm willing to split all fo the file generation (auto continue, whois, ...) into their own single thread but is that what we really want @spirillen  ?

**Comment by spirillen** [comment]
I'll give it a deeper though before answering it... 

There are a lot of things that we would need to take into consideration vs the [pyramid top](https://www.mypdns.org/project/view/15/)

**Comment by funilrys** [comment]
Mhh the best will actually be to have one single thread for each job (autocontinue storage, whois storage, etc). 
We will gain in performance. And as the writing (files) is sequential, we will have to wait anyway regarding the drive that is used. That's the problem with I/O bound tasks like writing files or waiting for network resources.

Here is the new structure (as per the last commit mentioned here):

![Thread Model](https://github.com/PyFunceble/draw.io/raw/0988f0c39c8a1dd8450f37bcfcb67d4365dadd77/dist/Thread_Model_PyFunceble_CLI.png)

**Comment by spirillen** [comment]
Oh simply generate file "file" worker who handling the file read/write to mem (this is a fast thought without reading code

**Comment by spirillen** [comment]
## With DB
[![asciicast](https://asciinema.org/a/yA4gvszrelDha9oYS4Rar6Jpd.svg)](https://asciinema.org/a/yA4gvszrelDha9oYS4Rar6Jpd)

## No DB
[![asciicast](https://asciinema.org/a/21qxMsgG49fmmnuLfQe53vuPL.svg)](https://asciinema.org/a/21qxMsgG49fmmnuLfQe53vuPL)

## Note
Have a look at the `output/` :speak_no_evil:

**Comment by spirillen** [comment]
Seems fixed :heavy_check_mark:
