### ISSUE TITLE
adblock not obtaining source from url

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#156]
## Bug description
See title

<https://travis-ci.com/github/dns-test/PyFunceble-Sandboxed/builds/210574987> + 
<https://travis-ci.com/github/dns-test/PyFunceble-Sandboxed/builds/210575157>

## Modifications under `.PyFunceble.yaml`

A clear representation of what you changed.

## Reproduction

```bash
- pyfunceble --ci --syntax -ex -w $(nproc --ignore=2)
          --adblock https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_trackingservers.txt
          --adblock https://raw.githubusercontent.com/easylist/easylist/master/easylist_cookie/easylist_cookie_general_hide.txt
          --adblock https://raw.githubusercontent.com/easylist/easylist/master/fanboy-addon/fanboy_annoyance_specific_block.txt
        - tree --prune -f "${TRAVIS_BUILD_DIR}/.pyfunceble/"
```

## Expected behavior
adblock can fetch directly from url-source as `-f`

## Additional context
<https://github.com/funilrys/PyFunceble/issues/155#issuecomment-751265770>

**Comment by spirillen** [comment]
Closing as I learned `--adblock` is a argument like `--wildcard` not a "source" like `-f` or `-uf`

**Comment by keczuppp** [comment]
I don't want to interrupt the conversation in the another thread so I'm commenting here in a less important and closed thread, so I won't interrupt anything:

> spirillen : `https://github.com/funilrys/PyFunceble/issues/155#issuecomment-751265589`:  
Ping (...) @Fanboynz (...) @ THEtomaso (...)

- did I just spot some typos in your comment as it should be:
`@ryanbr` instead of  `@Fanboynz` and `@THEtomaso` instead of `@ THEtomaso` 
or it was intentional to not ping these two directly

**Comment by spirillen** [comment]
> I don't want to interrupt the conversation in the another thread so I'm commenting here in a less important and closed thread, so I won't interrupt anything:
> 
> > spirillen : `https://github.com/funilrys/PyFunceble/issues/155#issuecomment-751265589`:
> > Ping (...) @Fanboynz (...) @ THEtomaso (...)
> 
>     * did I just spot some typos in your comment as it should be:
>       `@ryanbr` instead of  `@Fanboynz` and `@THEtomaso` instead of `@ THEtomaso`
>       or it was intentional to not ping these two directly

That will be lazy :unamused: as I couldn't remember there exact nicks, I copied them from a commit list :wink:
