### ISSUE TITLE
The json2csv migration takes oddly long or gets stuck entirely

### ISSUE THREAD

**Issue by DandelionSprout** [funilrys/PyFunceble#157]
## Bug description
Having begun testing out PyFunceble 4.0.0a27.dev in the past half-hour, I've encountered one odd problem in particular:

The `Started migration (json2csv) of the inactive dataset.` procedure before running PyFunceble on a file, seems to take considerably longer than it probably should.

Instance 1: Migration took around 5min. I sadly forgot to take a screenshot of this, also because the run failed anyway because I had used an incorrect filepath for the file I was testing with.

Instance 2: It's been 25min at the time of writing... and this is what it shows: 
![image](https://user-images.githubusercontent.com/22780683/103142243-5feef500-4700-11eb-88e0-bca1d125a51e.png)

I had cd'd to different folders in Cygwin in each of those two circumstances. I have yet to encounter any instance of the migration being quick and fast.

## Modifications under `.PyFunceble.yaml`

Nothing at all, to the best of my current knowledge.

## Reproduction

1. Run `pip3 install --user git+https://github.com/funilrys/PyFunceble.git@4.0.0-dev#egg=PyFunceble-dev` in Cygwin.
2. Try to run any file at all through PyFunceble.

## Expected behavior
Migration takes less than a couple minutes; or alternately more expressive error messages for the json2csv module.

## Screenshots
Used above.

## Versions

**OS:** Windows 10 20H2
**Python Version:** 3.7.7-1
**PyFunceble Version:** 4.0.0a27.dev

## Additional context
None that I'm currently aware of.

**Comment by spirillen** [comment]
Hey @DandelionSprout 

I can inform you that converting the Central DB (local copy) with about 266.000 records took about 10 hours, so yes, here should be room for improvement.

Secondly, try run the script with `--logging-leve` See https://github.com/funilrys/PyFunceble/issues/130#issuecomment-748605858 as it have yet to be documented

**Comment by DandelionSprout** [comment]
I actually did found a fix now, as the error turned out to (by all earmarks) be related to https://github.com/funilrys/PyFunceble/issues/134#issuecomment-751292658:

PyFunceble did not accept and/or acknowledge `domain2idna` if it had been installed through PyPi with pip3; and is only acknowledging it if it was installed through PyFunceble's installation process. Since `json2csv` tries to import `domain2idna`, this seemingly caused it to hang.

The fix was to delete PyFunceble and domain2idna, then running the PyFunceble installation process again.

**Comment by spirillen** [comment]
Super :+1: 

PS. You should copy https://github.com/funilrys/PyFunceble/issues/134#issuecomment-751292658 to it's own issue, then we can better add it to the fix & retest rutines, and thanks a lot for posting your finds and solution.

**Comment by funilrys** [comment]
Closing as it should be better now. 

Actually, it was not "slow" or "oddly long". It was running a background job and just to keep CI awake, I chose to print a dot every 5 seconds (assuming you are using the default timeout).

**Comment by spirillen** [comment]
@DandelionSprout can you confirm this have been solved?

**Comment by DandelionSprout** [comment]
I can at the very least confirm that I have no problems with this after updating to 4.0.0b1.dev, using the same work-environment and dependencies as I used with success when writing https://github.com/funilrys/PyFunceble/issues/157#issuecomment-751294264

**Comment by funilrys** [comment]
Awesome! Thanks for the feedback @DandelionSprout.
