### ISSUE TITLE
cygwin + domain2idna fails to upgrade

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#159]
Originally posted by @DandelionSprout in https://github.com/funilrys/PyFunceble/issues/134#issuecomment-751292658

## Bug description
Minor bug I came across that I presume doesn't warrant its own issue report:

Installing 4.0.0 through the procedure further above in this thread, fails to upgrade the `domain2idna-1.9.1-py3.7.egg` package to `domain2idna-1.12.0`, leading to the error Fatal Error: module 'domain2idna' has no attribute 'domain2idna' when running any file through PyFunceble. pip3 and pip also claimed that `domain2idna-1.9.1-py3.7.egg` was up to date, which was incorrect according to a glance at PyPi.

The fix was to open Voidtools Everything and delete all files with the filename term domain2idna that also had the terms 37 or 3.7 in them. Afterwards, pip3 install --user domain2idna was able to correctly detect and install domain2idna-1.12.0.

Screenshot from before I found the fix:
![image](https://user-images.githubusercontent.com/44526987/103143068-d0e9d900-470f-11eb-9227-2d7675575a9d.png)

## Additional context
Related to https://github.com/funilrys/PyFunceble/issues/157 where the issue was solved by upgrading `domain2idna>=1.12.0`

By merging https://github.com/funilrys/PyFunceble/pull/158 we should be forcing pipy/cygwin etc to upgrade domain2idna to latest version

**Comment by spirillen** [comment]
@DandelionSprout

Can you retest this one for us, non of us have Windows to test on and all out Travis time is up :unamused:

**Comment by DandelionSprout** [comment]
This one is not easy to simply test in a hurry, because it'd require me to reinstall an older version of domain2idna again prior to such a test, which I'm not 100% sure is even possible.

**Comment by spirillen** [comment]
You can alter the `requirement.txt` before installing and change

```
domain2idna to domain2idna==1.9.1
```

Det du skal gjøre er at nedladden pyfunceble fra kilden og så installere i `venv`
guide: <https://pyfunceble.readthedocs.io/en/4.0.0-dev/installation/index.html#for-development>

På denne måde for du pyfunceble til at installere med den nedgraderede version.

Herefter installere du med den almindelide metode od du skulle være tilbage ed den seneste version, om alt går vel.
