### ISSUE TITLE
Adblock Failed extration

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#161]
> 
> What file are you using? is it a public one I can test with?
> 

For example, foreign.txt in AdGuard Base filter (formerly English filter). This is the actual error message:
<details>
<summary>Screenshot</summary>

![cp932](https://user-images.githubusercontent.com/58900598/103146422-6dea5780-478c-11eb-8184-c70b3a3d910f.png)

</details>

_Originally posted by @Yuki2718 in https://github.com/funilrys/PyFunceble/issues/155#issuecomment-751323033_

```
document.readyState==="interactive")func()                                                           INVALID     SYNTAX     Unknown           Unknown    SYNTAX
```

https://travis-ci.com/github/dns-test/PyFunceble-Sandboxed/builds/210612262

**Comment by funilrys** [comment]
The exception assumes that it was because of the `shadow_file` which does not exist anymore (at least at the time I'm writing this) into the `4.0.0a41` version of PyFunceble.

Therefore, I'm closing this.

**Comment by spirillen** [comment]
TEST: :heavy_check_mark:
