### ISSUE TITLE
SpecialRule 24.eu (Needs confirmation)

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#171]
**Is your feature request related to a problem? Please describe.**
Add special rule for 24.eu with 503 as the marker for `INACTIVE`

```
curl -I samsung.24.eu
HTTP/1.1 503 Service Unavailable
Date: Wed, 06 Jan 2021 23:49:49 GMT
Server: Apache/2.4.10 (Debian)
Retry-After: 604800
Content-Type: text/html; charset=UTF-8
```

![image](https://user-images.githubusercontent.com/44526987/103834160-fddcab00-5082-11eb-9ce8-888f90a4a358.png)

SelfAssign as need external test outbond the Proxy

The thirdlvl domain is tested from <https://www.mypdns.org/T1194> (GoodbyeAds Samsung Adblock)

![image](https://user-images.githubusercontent.com/44526987/103834101-d1289380-5082-11eb-826a-1160aa68a9a6.png)

**Comment by spirillen** [comment]
Ran the test from hetzner.de network, same results (503)

```bash
curl -I samsung.24.eu -I 'samsung-produkcja.24.eu' -I 'samsung-stop.24.eu'
HTTP/1.0 503 Service Unavailable
Date: Thu, 07 Jan 2021 18:52:11 GMT
Server: Apache/2.4.10 (Debian)
Retry-After: 604800
Connection: close
Content-Type: text/html; charset=UTF-8

HTTP/1.0 503 Service Unavailable
Date: Thu, 07 Jan 2021 18:52:11 GMT
Server: Apache/2.4.10 (Debian)
Retry-After: 604800
Connection: close
Content-Type: text/html; charset=UTF-8

HTTP/1.0 503 Service Unavailable
Date: Thu, 07 Jan 2021 18:52:11 GMT
Server: Apache/2.4.10 (Debian)
Retry-After: 604800
Connection: close
Content-Type: text/html; charset=UTF-8
```

If other can confirm this, i'll move forward to add this into the special rules

**Comment by funilrys** [comment]
Waiting for confirmation from people that are not me before adding this into one milestone.

**Comment by funilrys** [comment]
Introduced with https://github.com/funilrys/PyFunceble/commit/90039a5899164fcb6ae0100221b2e953b56b5461.
