### ISSUE TITLE
If not syntax test, lowercase all domain path

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#172]
## Bug description
This is actually a VALID record

```python
coordinator-Production-28516768.us-east-1.elb.amazonaws.com
```

```shell
drill coordinator-Production-28516768.us-east-1.elb.amazonaws.com
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 13183
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0 
;; QUESTION SECTION:
;; coordinator-Production-28516768.us-east-1.elb.amazonaws.com. IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:
us-east-1.elb.amazonaws.com.    900     IN      SOA     ns-1119.awsdns-11.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 60

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 192.168.1.5
```

## Modifications under `.PyFunceble.yaml`

None

## Reproduction

```
pyfunceble --database-type mariadb --no-files -a \
  -f https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Samsung-AdBlock.txt
```
## Expected behavior
Let's see :smirk: 

## Screenshots
![image](https://user-images.githubusercontent.com/44526987/103834551-02ee2a00-5084-11eb-8995-b320c05b3d06.png)

## Versions

**OS:** Ubuntu 20 + Conda
**Python Version:** 3.9.1
**PyFunceble Version:** pyfunceble 4.0.0b1.dev (Blue Duckling)

## Additional context
Nope

**Comment by funilrys** [comment]
The upper case is not accepted as VALID. But I think that converting to lowercase may help everybody including lists maintainers.

**Comment by spirillen** [comment]
> The upper case is not accepted as VALID. But I think that converting to lowercase may help everybody including lists maintainers.

:laughing: Well spotted, I haven't noticed the upper `P` probably because I've got used to the default to lowercase handling :open_mouth:

**Comment by funilrys** [comment]
Into `b3` which is under deployment.

GHA: https://github.com/funilrys/PyFunceble/actions/runs/470055186

**Comment by spirillen** [comment]
Test results: :heavy_check_mark:
