### ISSUE TITLE
plain not generated

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#179]
## Bug description
`--plain`not generating any results files

## Modifications under `.PyFunceble.yaml`

None

## Reproduction

`pyfunceble -f /tmp/gstatic.com --dns 91.239.100.100 89.233.43.71 -a --plain -dbr 0 --output-location /tmp/`

## Expected behavior
Generation of output for plain/domain list

`/tmp/output/gstatic.com/domain/$status/`

## Screenshots

![image](https://user-images.githubusercontent.com/44526987/104093354-66e23f80-528a-11eb-96c4-49851e13ecf0.png)

## Versions

**OS:** Ubuntu 20.04 - (minus) conda
**Python Version:**  3.9
**PyFunceble Version:** v4.0.0b3.dev

**Comment by funilrys** [comment]
As per https://github.com/funilrys/PyFunceble/blob/2b12f88e69d549e52de681c1fd490c6f4c54ec04/PyFunceble/data/infrastructure/.PyFunceble_production.yaml#L172

`plain` is activated by default, meaning that `--plain` negates it.

In practice what is done (extremely simplified):

```python
$ python3
>>> default_plain = True
>>> 
>>> # Let's assume the arg is not given.
>>> plain_given_by_arg = False
>>> used_plain = not(default_plain) if plain_given_by_arg else default_plain
>>> used_plain
True
>>> 
>>> # Let's assume the arg is given.
>>> plain_given_by_arg = True
>>> used_plain = not(default_plain) if plain_given_by_arg else default_plain
>>> used_plain
False
>>>
>>> # Let's now assume the default value is False
>>> default_plain = False
>>> 
>>> # Let's assume the arg is not given.
>>> plain_given_by_arg = False
>>> used_plain = not(default_plain) if plain_given_by_arg else default_plain
>>> used_plain
False
>>> 
>>> # Let's assume the arg is given.
>>> plain_given_by_arg = True
>>> used_plain = not(default_plain) if plain_given_by_arg else default_plain
>>> used_plain
True
>>>
```

**Comment by spirillen** [comment]
Oki.... I'll change that in the docs

<https://pyfunceble.readthedocs.io/en/dev/usage/index.html#plain>

**Comment by funilrys** [comment]
Is the default value not okay for you ? We can discuss that 🤔
