### ISSUE TITLE
SQL New DB fails

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#180]
## Bug description
```python
Fatal Error: (pymysql.err.OperationalError) (1170, "BLOB/TEXT column 'path' used in key specification without a key length")
[SQL: 
CREATE TABLE pyfunceble_file (
        id INTEGER NOT NULL AUTO_INCREMENT, 
        created DATETIME NOT NULL, 
        modified DATETIME, 
        path TEXT NOT NULL, 
        test_completed BOOL NOT NULL, 
        PRIMARY KEY (id), 
        UNIQUE (path), 
        CHECK (test_completed IN (0, 1))
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

## Reproduction

1. empty DB
2. Run with `--database-type mariadb`

## Expected behavior
:thinking: 

## Screenshots

![image](https://user-images.githubusercontent.com/44526987/104094888-fa6c3e00-5293-11eb-8882-fa301de630be.png)

## Versions

**OS:** Ubuntu 20.04 (minus) conda
**Python Version:** 3.9
**PyFunceble Version:** 4.0.0b3.dev

## Additional context
:de: :denmark: :fr:

**Comment by funilrys** [comment]
I literally have no way to reproduce this 🤔  Is it MariaDB or MySQL?

**Comment by spirillen** [comment]
I believe it's mysql....

keybase://chat/funilrys,spirillen/2581

If you can't setup one true keybase://chat/funilrys,spirillen/2580 let me know and I setup a fresh one for you

**Comment by spirillen** [comment]
From github.com:funilrys/PyFunceble
   0d5e5450..773e5f96  dev        -> origin/dev
Updating 0d5e5450..773e5f96

virtual env, seems to work. 

Test still running.

----------

Straight in Ubuntu, no virtual envs, this happens in less than a second.... :unamused: pythin and Ubuntu just don't like each other #39  

**4.0.0b9.**

```python
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '682990' for key 'PRIMARY'")
[SQL: UPDATE pyfunceble_continue SET id=%(id)s, modified_at=%(modified_at)s, idna_subject=%(idna_subject)s, checker_type=%(checker_type)s, destination=%(destination)s, source=%(source)s, tested_at=%(tested_at)s, session_id=%(session_id)s]
[parameters: {'id': 682990, 'modified_at': datetime.datetime(2021, 1, 13, 14, 52, 11, 468686), 'idna_subject': '000iblogchix.blogspot.ae', 'checker_type': 'SYNTAX', 'destination': 'test.list', 'source': '/var/storage01/repos/github/pyfunceble/test.list', 'tested_at': datetime.datetime(2021, 1, 13, 14, 51, 56, 155441), 'session_id': 'd809cd7dd4dde4f70b8a2b91'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)
```
