### ISSUE TITLE
Fatal Error: fromisoformat: argument must be str

### ISSUE THREAD

**Issue by funilrys** [funilrys/PyFunceble#181]
OK, after a few hours an error occurred and the testing process was stopped.

`Fatal Error: fromisoformat: argument must be str`

![Bildschirmfoto vom 2021-01-09 18-49-18](https://user-images.githubusercontent.com/28985171/104104955-6e661080-52ab-11eb-8770-bdd48dd4d38e.png)

_Originally posted by @ZeroDot1 in https://github.com/funilrys/PyFunceble/issues/134#issuecomment-757342046_

**Comment by spirillen** [comment]
@ZeroDot1 can you remember which test args and file you was using??

Was it `pyfunceble -w 4 -a --syntax -f All.txt` from <https://github.com/funilrys/PyFunceble/issues/134#issuecomment-757172892>

IF == True can I access the `All.txt` somewhere?

**Comment by ZeroDot1** [comment]
`pyfunceble -w 4 -a --syntax -f All.txt`

That was exactly the command I used, I can't make the file available to you because it is currently internal, but the error occurred while checking the follow URLs.

```js
jp03.mofumofu.me
jp04.mofumofu.me
jp05.mofumofu.me
jp06.mofumofu.me
```
The All.txt file contains 115500+ entries.

**Comment by spirillen** [comment]
> The All.txt file contains 115500+ entries.

That's nothing :smiley: it's only a small footnote compared to some of those i tests.....

  - https://github.com/dns-test/porn.host.rpz (1.500.000)
  - https://github.com/dns-test/rpz.mypdns.cloud (650.000)

There is a reason I keep saying speedup :smirk:

**Comment by ZeroDot1** [comment]
If needed, you can find additional information about the IOCs via [Pulsedive](http://pulsedive.com/purchase/pro).

https://pulsedive.com/indicator/?iid=13004843
https://pulsedive.com/indicator/?iid=13004849
https://pulsedive.com/indicator/?iid=13004847
https://pulsedive.com/indicator/?iid=13004848

**Comment by ZeroDot1** [comment]
Hm, when I check this two times I get only 3 results the first time.
![Bildschirmfoto vom 2021-01-09 22-51-56](https://user-images.githubusercontent.com/28985171/104109374-7171f880-52cd-11eb-89cb-5053aca9d6a2.png)

**Comment by spirillen** [comment]
@ZeroDot1 what are your relation / usage of that site? At first review it looks a lot like what we are trying to build matrix.rocks into... but with own source-files test capability

**Comment by spirillen** [comment]
I believe we can move this one to Successfully tested https://github.com/funilrys/PyFunceble/projects/6#card-52499524
