### ISSUE TITLE
Not everything is getting tested systematically while testing for single entries (not files)

### ISSUE THREAD

**Issue by funilrys** [funilrys/PyFunceble#183]
Hm, when I check this two times I get only 3 results the first time.
![Bildschirmfoto vom 2021-01-09 22-51-56](https://user-images.githubusercontent.com/28985171/104109374-7171f880-52cd-11eb-89cb-5053aca9d6a2.png)

_Originally posted by @ZeroDot1 in https://github.com/funilrys/PyFunceble/issues/181#issuecomment-757372823_

**Comment by ZeroDot1** [comment]
OK, after another run with different URLs I can confirm the problem, it always occurs completely randomly.
No difference on what URLs you check.

**Comment by spirillen** [comment]
I actually had the same issue first time i tested the 4 urls yesterday :unamused:

**Comment by ZeroDot1** [comment]
@funilrys Thanks for fixing the bug, I will test everything as soon as possible.

**Comment by spirillen** [comment]
Can't reproduce this error

```shell
for long_tail in {0..9}; do pyfunceble --syntax -d jp03.mofumofu.me jp04.mofumofu.me jp05.mofumofu.me jp06.mofumofu.me; done
```

This should be moving the issue to "Successfully Tested" in https://github.com/funilrys/PyFunceble/projects/6
