### ISSUE TITLE
Special rule: www.example.org & m.example.org redirects to example.org

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#185]
**Is your feature request related to a problem? Please describe.**
There are no such thing as `^(www|m)\..*\.tumblr\.com$`

  - [X] Check response status for these cases, in the past they responded 200

**Describe the solution you'd like**
Wee should append a `302` rule

```
curl -I 'http://www.sensual-kiss.tumblr.com' 'http://m.sensual-kiss.tumblr.com'
HTTP/1.1 302 Found
Server: openresty
Date: Sun, 10 Jan 2021 17:52:39 GMT
Content-Type: text/html; charset=UTF-8
X-Rid: 853406b998b4af2af248c41f442e2565
P3p: CP="Tumblr's privacy policy is available here: https://www.tumblr.com/policy/en/privacy"
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=15552001
Location: https://sensual-kiss.tumblr.com/#_=_
X-UA-Compatible: IE=Edge,chrome=1
X-Cache: MISS from firewall.matrix.lan
X-Cache-Lookup: MISS from firewall.matrix.lan:3128
Via: 1.1 firewall.matrix.lan (squid)
Connection: keep-alive

HTTP/1.1 302 Found
Server: openresty
Date: Sun, 10 Jan 2021 17:52:40 GMT
Content-Type: text/html; charset=UTF-8
X-Rid: 406103b229eb27730826e4000e1c2063
P3p: CP="Tumblr's privacy policy is available here: https://www.tumblr.com/policy/en/privacy"
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=15552001
Location: https://sensual-kiss.tumblr.com/#_=_
X-UA-Compatible: IE=Edge,chrome=1
X-Cache: MISS from firewall.matrix.lan
X-Cache-Lookup: MISS from firewall.matrix.lan:3128
Via: 1.1 firewall.matrix.lan (squid)
Connection: keep-alive
```

**Describe alternatives you've considered**
Even better would be 

```bash
if [ dest == `^(www|m)\..*\.tumblr\.com($|\/.*)` ]
then
    return INVALID
fi
```

**Additional context**

**Comment by funilrys** [comment]
This one is odd ... Who does that ?

**Comment by spirillen** [comment]
user who don't know better: https://github.com/Clefspeare13/pornhosts/issues/60

Have seen that other places as well actually, that why I suggested it in a global "scaled", other times I simply suspect some are using a script to completely headless append the `m.` and `www.` just to make there lists grow

**Comment by spirillen** [comment]
I sometimes think a `HTTP code 302` is down, most cases actually, unless it is part of the HSTS (HTTP Strict Transport Security) as the specified target obviously is moved.

Then the HUGE exception.... redirecting spyware like `t.co` `bit.ly` etc they are all redirecting (Didn't check there response code at they are blocked here)

That's why I suggested this as a special rule, check for a forth level domain and if there is mark it INVALID, in that way we cancircumwent the 302 question and we can't use the `--complements` as that is purely for the `www or not www`

On the other hand if it is a bigger work... and then again, when remembering the exact domain, I've seen the same "rule" could be applied elsewhere.

```
IF domain-level >= 4
then
    rule is INVALID
fi
```

Then question might then become, is this a module we would like to be able to make special rules based on domain level?

**Comment by spirillen** [comment]
> This one is odd ... Who does that ?

Let me take a very fresh examlpe...

> I duplicated the previous list twice, once adding www. subdomains, and once adding cdn.; resulting in two new lists of the formats: www.websitename.abc and cdn.websitename.abc.
> Source: https://github.com/StevenBlack/hosts/issues/1671#issuecomment-970165062 (§2)

**Comment by spirillen** [comment]
Just found this from another import....

https://mypdns.org/my-privacy-dns/porn-records/-/blob/4c5d12ff4f4d72a03e217b05862d3a2f333fc109/submit_here/imported/pornhosts.import-external-sources#L186-308

**Comment by funilrys** [comment]
Note to self: 
The idea is not bad. We should implement this. But subjects should be switched as `INACTIVE` not `INVALID`.

**Comment by funilrys** [comment]
Side notes on the implementation - itself - when URLs are tested:

 1. Follow all redirects.
2. Compare the start domain with the end-domain and switch status accordingly. 
  Example:
    - `m.example.com/hello/world -> example.com/hello/world` | Outcome: `m.example.com/hello/world` as `INACTIVE`.
    - `m.example.com/hello/world -> example.com/world/hello` | Outcome: NO Status switch.
    - `m.example.com/hello/world` -> `example.org/hello/world` | Outcome: NO Status switch.
    - `m.example.com/hello/world` -> `a.example.com/world/hello` -> `example.com/hello/world` | Outcome: `m.example.com/hello/world` as `INACTIVE`.

**Comment by spirillen** [comment]
To continue https://matrix.to/#/!frMIeLrTTlrGiRMLBM:matrix.org/$gHxSAP8rlCIFF40wKybFK6VceyKc7NPmjj_RxLN7kFQ?via=matrix.org&via=anontier.nl

This is a special rule, but should be a global one as it is following the requests to the final destination, all "middlemen" is marked as `potential` dead


> https://github.com/funilrys/PyFunceble/issues/185#issuecomment-877784789
> `^(www|m)\..*\.tumblr\.com$`

We will remove any useless `(m.|www.|www.).domain.ccTLD` and only leave potential ACTIVE records in our `ACTIVE/list`

You can call this `--complements` on steroids as it removes any middlemen from the finished result `ACTIVE/list`


> ```
> IF domain-level >= 4
> then
>     rule is INVALID
> fi
> ```
>
> The question might then become, is this a module we would like to be able to make special rules based on domain level?

The rewrite for this would be:

IF the domain is in file `some internal db file of domains` then we do know; that any records with `^(www|m)\..*\.domain\.ccTLD$` are INVALID, we strip the prefixes and test those records that is left.

Example of such regex compliant file could be

```
tumblr.com = ^(www|m)\..*\. | !^([0-9a-z]{0-255}[.])?
bit.ly = !^bit.ly
```

> https://github.com/funilrys/PyFunceble/issues/185#issuecomment-939477917
>
>  It's actually not INVALID ... It actually redirects to the right domain ... At least that is what the Location header is saying.

Yes, but you have no use of the record in any output list as it is redirecting, you would need the destination as it would help keeping the final lists as small and accurate as possible.

> https://github.com/funilrys/PyFunceble/issues/185#issuecomment-1290400728
>
> The idea is not bad. We should implement this. But subjects should be switched as INACTIVE not INVALID.

That would depend on the domain.... for `bit.ly` and `tumblr.com` INVALID is the correct results while other redirecting devils might be, by default, INACTIIVE

**Comment by funilrys** [comment]
> IF the domain is in file some internal db file of domains then we do know; that any records with ^(www|m)\..*\.domain\.ccTLD$ are INVALID, we strip the prefixes and test those records that is left.

That is actually another improvement for the mining mechanism... 

Here we are only talking about subjects that redirect to their 2ndLD. Example `m.example.org -> example.org` and `www.example.org -> example.org` . And this SPECIAL ruler will only be triggered if the given subject starts with `www.` or `m.`. 


All URL shorteners are never triggered by this feature because the tested domain won't match the expected domain. 

For example: 

- `bit.ly/xyz -> example.org/hello/world` --> Never trigger.
- `m.bit.ly/hello -> bit.ly/hello -> example.org/hello` --> Nothing change.
- `www.bit.ly/hello -> bit.ly/hello -> example.com/hello` --> Nothing change.
- `www.bit.ly/ -> bit.ly/` --> Trigger SPECIAL rule. `www.bit.ly` will be dropped as `INACTIVE`.


Also note: The path will be compared. If it doesn't match, nothing changes.

**Comment by funilrys** [comment]
There is a drawback with flaging a subject as `INVALID` ... A lot of users just drop and definitely delete `INVALID` and leave PyFunceble to retest all `INACTIVE` ... That's also something we have to keep in mind ...

We are only a few people in the issues section but we are a lot more users than we think 😰...

**Comment by spirillen** [comment]
**NOTE**:

Stumbled on this special domain case

1. www.subdomain.skyblog.com = not supported
2. *.skyblog.com = Redirects straight to skyrock.com = we now know `skyblog.com` is invalid

:thought_balloon: :thinking: maybe a new result list? that could also help on your comment in https://github.com/funilrys/PyFunceble/issues/185#issuecomment-1290906472 about the INVALID as they defacto are invalid cases and should be attended by list owner?

**Comment by spirillen** [comment]
UPDATE: About the special rule for tumblr, then they have made a change for which I have NOT investigated, ONLY observed

`teen-make-selfies.tumblr.com` This url is empty and redirects to the default homepage, I have found about 30 of these today and they was marked active against expectation.

Any change you (@funilrys ) could spend a few minutes on this?

**Comment by funilrys** [comment]
@spirillen they actually don't redirect to the home page per-say. It's all javascript. Therefore, the rule should be about the 404 status code.
