### ISSUE TITLE
object 'datetime.datetime' has no attribute 'fromisoformat'

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#192]
## Bug description
Started migration of the pyfunceble_file and pyfunceble_status tables.
Finished migration of the pyfunceble_file and pyfunceble_status tables.
Fatal Error: type object 'datetime.datetime' has no attribute 'fromisoformat'

## Modifications under `.PyFunceble.yaml`

See #191

**Comment by spirillen** [comment]
+ https://github.com/funilrys/PyFunceble/issues/189

**Comment by funilrys** [comment]
This is happening because it was introduced in Python 3.7. I'm going to drop 3.6 for our good sake.

I'm not willing to lose my time with 3.6.

**Comment by funilrys** [comment]
This is one will be good in the known issues I guess.

**Comment by spirillen** [comment]
> This is one will be good in the known issues I guess.

:+1:  will add it to the lsit of ToDo: <https://github.com/spirillen/PyFunceble/issues/38>

Another **_though_** to this.. :thought_balloon:  :thought_balloon:  :thought_balloon:  :thought_balloon:  :thought_balloon: 

That will disarm the possibility to use default raspberry4 32bit OS....

Not even with conda you can go higher than 3.6 on raspberry for time being :unamused:

**Comment by funilrys** [comment]
Closing as it is now documented.
