### ISSUE TITLE
substitute referer with the right word referrer

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#198]
## Bug description
substitute `referer` with the right word `referrer` in all script, including 

https://pyfunceble.funilrys.com/api/
https://pyfunceble.funilrys.com/api/no-referer

https://github.com/funilrys/PyFunceble/blob/95943e96a405fbe9403a72bc1623664539f9ea98/PyFunceble/data/infrastructure/.PyFunceble_production.yaml#L326

**Comment by funilrys** [comment]
@spirillen, you have my OK for a new PR with that change.
