### ISSUE TITLE
end_commit_message: not applied on final commit

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#205]
## Bug description
end_commit_message: not applied on final commit

## Modifications under `.PyFunceble.yaml`

<https://github.com/mypdns/porn-records/blob/4892534293e519cd777c9749b120477b859281a7/.pyfunceble/.PyFunceble.yaml>

## Reproduction

<https://github.com/mypdns/porn-records/blob/4892534293e519cd777c9749b120477b859281a7/.github/workflows/main.yml>

```
................
Execution Time: 00:00:05:57.967906 << tells us there are no follow up, it's the last run in the serie

[master b9d1867] My Privacy DNS Firewall - AutoSave
 2 files changed, 26 insertions(+), 26 deletions(-)
Already on 'master'
From https://github.com/mypdns/porn-records
 * branch            master     -> FETCH_HEAD
Already up to date.
To https://github.com/mypdns/porn-records
   74bf244..b9d1867  master -> master
```

## Expected behavior
To see the `end_commit_message` message, not the `commit_message`

## Screenshots
![image](https://user-images.githubusercontent.com/44526987/105230736-190ce780-5b66-11eb-92c2-22b903338fac.png)
![image](https://user-images.githubusercontent.com/44526987/105230771-275b0380-5b66-11eb-9593-9b3c7029bdb4.png)

## Versions

**OS:** for example Arch Linux (5.0.5-arch1-1-ARCH)
**Python Version:** for example 3.6.5
**PyFunceble Version:** for example 1.2.0

**Comment by funilrys** [comment]
Well, @dead-hosts use the CLI (indirectly) and I can't see this issue 🤔 What am I missing? 

Note: [ci_test](https://github.com/PyFunceble/ci_test) too is working 🤔

**Comment by spirillen** [comment]
I think you are missing that the -ci-minutes in this case is 45m, so when it would do the `git commit -m` the message should be the final commit message, not the auto-continue message as in this particular case

**Comment by funilrys** [comment]
Just to clarify @spirillen, after 45 minutes (in your example), the `commit_message` is used if the test of the file is not complete (yet). And the `end_commit_message` only at the real end of the test - when it's complete. 

What am I missing here?

**Comment by spirillen** [comment]
As you write it your self... If we looks at the results, the actually execution time  before end is about 5 minutes, which to me is a indicator that PyFunceble have finished the test. **_There are no more to test, we are done_**.  Agreed?? As so, I would expect the `end_commit_message` message.

While if the test had been running for the full 45 minutes, then I will expect the `commit_message` to appear in the commit header, as the test isn't finished.

It's all about the running (execution) time here vs what message is expected.

```bash
IF [ $ex >= $max_exec_minutes ]
then
    `commit_message`
else
    `end_commit_message`
fi
```

Does this little IF helps you understand?

**Comment by funilrys** [comment]
You are describing what PyFunceble `4.0.0` actually does...

https://github.com/funilrys/PyFunceble/blob/01ef48c2d02ef92da60bc56f1978699f2c065870/PyFunceble/cli/system/launcher.py#L856-L864

I don't see where the problem is 🤔

**Comment by funilrys** [comment]
Can I get an update from your side - when you get a bit of time? 
@spirillen

**Comment by spirillen** [comment]
yep, just found that the `--ci-max-minutes` actually was set to 5 :unamused: I have no clue when this should have happent...
