### ISSUE TITLE
pyfunceble_CONFIG_DIR

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#213]
## Bug description
The global variables like `pyfunceble_CONFIG_DIR` is not picked of from bash scripts

```bash
export pyfunceble_AUTO_CONFIGURATION=yes
export pyfunceble_CONFIG_DIR="${ROOT_DIR}/.pyfunceble/"
export pyfunceble_OUTPUT_LOCATION="${ROOT_DIR}/"
```

``` console
  $ pyfunceble --ci --database-type mariadb -q -a -f "${SourceFiles[@]}"
```

## Modifications under `.PyFunceble.yaml`

<https://github.com/dns-test/EasyList/blob/a38953a4ff4cdcf9faade1edfb7eed6d2a0933bb/.pyfunceble/.PyFunceble.yaml>

## Expected behavior
I would expect pyfunceble picked up the modifications of `.pyfunceble/.PyFunceble.yaml` and therefor have to invert the `--ci --database-type mariadb -q -a` flags to get expected output in bash/console

## Screenshots
![image](https://user-images.githubusercontent.com/44526987/106283948-d96b8d00-6242-11eb-96b8-150efbb3d8b7.png)

## Versions

**OS:** Ubuntu 20.04.1 + Conda 4.9.2
**Python Version:** for example 3.9.1
**PyFunceble Version:** 4.0.0b18.dev

## Additional context
The same occur if I try to parse the arguments from a variable like 

```bash
pyfuncebleArgs='--database-type mariadb -q -a'
pyfuncebleArgs=("--database-type mariadb" "-q" "-a")

pyfunceble "${pyfuncebleArgs[@]}" -f "${SourceFiles[@]}"

OR

pyfunceble "${pyfuncebleArgs}" -f "${SourceFiles[@]}"

OR

pyfunceble "${pyfuncebleArgs[*]}" -f "${SourceFiles[@]}"
```

The I get this response:
```console
pyfunceble 4.0.0b18.dev (Blue Duckling)
usage: pyfunceble [-d DOMAINS [DOMAINS ...]] [-u URLS [URLS ...]] [-f FILES [FILES ...]] [-uf URL_FILES [URL_FILES ...]] [--adblock] [--complements] [--preload]
                  [--filter CLI_TESTING__FILE_FILTER] [--mining] [--rpz] [--wildcard] [-c] [--cooldown-time CLI_TESTING__COOLDOWN_TIME] [--local] [--dns-lookup] [--http]
                  [--netinfo-lookup] [--special-lookup] [--whois-lookup] [--reputation-lookup] [--reputation] [--syntax] [-t LOOKUP__TIMEOUT] [-ua USER_AGENT__CUSTOM]
                  [-vsc] [--dns DNS__SERVER [DNS__SERVER ...]] [--dns-protocol {UDP,TCP,HTTPS,TLS}] [--inactive-db] [--database-type {csv,mariadb,mysql}]
                  [-dbr CLI_TESTING__DAYS_BETWEEN__DB_RETEST] [-wdb CLI_TESTING__WHOIS_DB] [-a] [-ex] [--colour]
                  [--display-status {all,ACTIVE,INACTIVE,VALID,INVALID,MALICIOUS,SANE} [{all,ACTIVE,INACTIVE,VALID,INVALID,MALICIOUS,SANE} ...]] [--hierarchical] [-h]
                  [-ip CLI_TESTING__HOSTS_IP] [--no-files] [--output-location OUTPUT_LOCATION] [--unified-results] [--percentage] [--plain] [--dots] [-q] [-s]
                  [-w CLI_TESTING__MAX_WORKERS] [--ci-max-minutes CLI_TESTING__CI__MAX_EXEC_MINUTES] [--ci] [--ci-branch CLI_TESTING__CI__BRANCH]
                  [--ci-distribution-branch CLI_TESTING__CI__DISTRIBUTION_BRANCH] [--cmd CLI_TESTING__CI__COMMAND] [--cmd-before-end CLI_TESTING__CI__END_COMMAND]
                  [--ci-commit-message CLI_TESTING__CI__COMMIT_MESSAGE] [--ci-end-commit-message CLI_TESTING__CI__END_COMMIT_MESSAGE] [--help] [-v]
pyfunceble: error: unrecognized arguments: --database-type mariadb -q -a

```

**Comment by funilrys** [comment]
I won't play with all variations. Please update your variable to be in UPPER CASE.

**Comment by spirillen** [comment]
I'm going to link these two issues: https://github.com/funilrys/PyFunceble/issues/207

The thing is, it looks like `.PyFunceble.yaml` in the `PYFUNCEBLE_CONFIG_DIR(=|:)` isn't picked up at all Try to have a look at https://github.com/dns-test/rpz.mypdns.cloud/actions/runs/527891765 There is the https://github.com/dns-test/rpz.mypdns.cloud/blob/7d2b3e2507d72328215a9b20d214f1fbb53c8464/.pyfunceble/.PyFunceble.yaml#L4 You'll see that `rpz: true`

However it is first picked up in https://github.com/dns-test/rpz.mypdns.cloud/actions/runs/527902191 when I actually puts the `          --rpz` into https://github.com/dns-test/rpz.mypdns.cloud/blob/7d2b3e2507d72328215a9b20d214f1fbb53c8464/.github/workflows/main.yml#L82

Hence the same issue occurs in #207 especially about the reversing the values set in the `PYFUNCEBLE_CONFIG_DIR=$path/.PyFunceble.yaml`

**Comment by spirillen** [comment]
/Closed as solved.... Thank you Microshit for messing with linux not knowing what you are doing.....
