### ISSUE TITLE
MySql Tested_at twenty years ago :thinking: 

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#220]
## Bug description
Found this in cdb.matrix.rocks

|id|created_at|modified_at|idna_subject|checker_type|destination|source|tested_at|session_id|
|--|----------|-----------|------------|------------|-----------|------|---------|----------|
|762095|2021-02-15 00:15:53|2021-02-15 00:15:53|cdn.shopify.com|AVAILABILITY|strict.domains.list|/home/runner/work/porn-records/porn-records/strict.domains.list|2001-02-15 00:15:51|b7d5da808198b1d84d2b2557|
|762104|2021-02-15 00:16:10|2021-02-15 00:16:10|cdn.shopify.com|AVAILABILITY|strict.hosts.list|/home/runner/work/porn-records/porn-records/strict.hosts.list|2001-02-15 00:16:09|db704af2ba6ab9685c78f7e2|

Is this just me, or where you coding in a significant young age :rofl: 

`cdn.shopify.com` was just test 2 minutes earlier here: https://github.com/mypdns/porn-records/runs/1899769393?check_suite_focus=true#step:10:82

**Comment by funilrys** [comment]
This is normal behavior if you are using the `--preload` thing. 
A dataset is considered as "pre-loaded" and "to-be tested" if the `tested_at` column is at least 20 years ago.

![](https://media.giphy.com/media/ZqlvCTNHpqrio/giphy.gif)

**Comment by spirillen** [comment]
Yeah, but as said

> was just test 2 minutes earlier

So it should not be 20 years ago.... it should be 2 minutes ago....

**Comment by funilrys** [comment]
@spirillen Patch is on its way. Thanks for getting back.
