### ISSUE TITLE
[Documentation] Queries to pyfunceble-XXXXXXXXXXXX.com

### ISSUE THREAD

**Issue by funilrys** [funilrys/PyFunceble#224]
Please help me document the queries made to `pyfunceble-XXXXXXXXXXXX.com`. I'd love to get this somehow documented in either a new component or in one of the existing ones. PR are welcome.

Let me explain the how and why.

# Origin

It all started with #45 which ended with this patch: https://github.com/funilrys/PyFunceble/commit/5398233e149b93c34343a387bfffeab68294c069

In short, all HTTP queries were following the systemwide DNS server instead of the one created by PyFunceble. I had to come with a solution which forces all our HTTP query to follow the IP given by the custom DNS server provided by the end-user of PyFunceble.

# The long version

Because PyFunceble will create its own DNS resolver and we want everything to work accordingly, I wrote some custom adapter in order to follow the provided DNS server instead of the systemwide one. 

In other words: I "tricked" the `requests` module by replacing the domain with the IP and setting the `Host` header with the sub-domain we are testing.

It is done here for an HTTP request:

https://github.com/funilrys/PyFunceble/blob/bd6262a25af55f052bd721da83bf4c94f45c8965/PyFunceble/query/requests/adapter/http.py#L101-L109

and here for an HTTPS request:

https://github.com/funilrys/PyFunceble/blob/bd6262a25af55f052bd721da83bf4c94f45c8965/PyFunceble/query/requests/adapter/https.py#L101-L117

Indeed, while using the `requests` module to get the HTTP status code or the mined dataset, our implementation of the requests module will do the DNS resolution with our very own resolver.

But, if the resolver failed (cf: no `A` or `AAAA`), I use to use to (`v3.x`) the `pyfunceble-not-resolved` "domain" as a placeholder. That will make requests look for that domain, but it won't find it because it is something nobody knows. 

That's why; if someone is monitoring their network; they can see a request/lookup of  `pyfunceble-not-resolved` domain in any version before `v4.0.0`. Somehow, it was falsely flagged as an error because I didn't handle all exceptions properly. 

In all version since `v4.0.0a1`, things are a bit different. Because I don't that placeholder do be obviously predictable, on each session , PyFunceble will generate something like ([see here](https://github.com/funilrys/PyFunceble/blob/b18b220d283b4cfdcb92eb70cdb1f3d37d2f9b61/PyFunceble/storage.py#L90)):

```python
>>> import secrets
>>> f"pyfunceble-{secrets.token_hex(12)}.com"
'pyfunceble-fcf0ab7db58a4cfdfd17204f.com'
>>> f"pyfunceble-{secrets.token_hex(12)}.com"
'pyfunceble-ab2b9257292958e4041a5f4c.com'
```

# Facit

If you happen to monitor your network, please consider any HTTP query for/from/to `pyfunceble-XXXXXXXXXXXX.com` as a placeholder which is there just to keep thing as smooth as possible.

**Comment by funilrys** [comment]
@spirillen, some may wonder if they see a "pyfunceble-xxxxxxxx.com" in their logs .... If you have time, can you try to document this behavior based on what I wrote?

**Comment by spirillen** [comment]
I'll give it a look later.... trying to optimize the mypdns.org server at this moment...

But from the top of my head, which log are we talking about, Translated is it the dns/web/???

**Comment by spirillen** [comment]
Not shown in my dns log...

`sudo rec_control trace-regex "^pyfunceble.*\.com"`

```
journalctl -fu pdns-recursor -n 100 -g pyfun
-- Logs begin at Wed 2021-09-01 15:04:42 CEST. --
Sep 21 18:58:38 vision pdns_recursor[63010]: Received rec_control command 'trace-regex ^pyfunceble.*\.com' from control socket
```


![image](https://user-images.githubusercontent.com/44526987/134215574-52ddda19-ec0a-45e2-991e-e0a75badeed0.png)


Or did I misunderstand something ??
