### ISSUE TITLE
New read-in format of DLEF (json)

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#228]
**Is your feature request related to a problem? Please describe.**
As of @Somebodyisnobody `Domain list exchange format.`([T3776](https://www.mypdns.org/T3776)) already have seen the first real implementation by ChongLuaDao.Vn in there phishing blacklist <https://api.chongluadao.vn/v1/blacklist>, I'll like to suggest that PyFunceble can handle the DLEF format as well. example: <https://www.mypdns.org/P39>

**Describe the solution you'd like**
A feature to read and test DLEF `--dlef` 

**Describe alternatives you've considered**
A lot of individual coding to decode into plain format

**Additional context**
I like to thanks @Somebodyisnobody and @7onez for making the new format public and put it into good use for sharing knowledge across projects.

**Comment by Somebodyisnobody** [comment]
The XML Style sheet can be shown here: https://www.mypdns.org/P38 The categories are not fixed at the moment because of less time on my side

**Comment by funilrys** [comment]
Is there a definitive SPEC for this ?

**Comment by Somebodyisnobody** [comment]
what do you mean?

**Comment by funilrys** [comment]
Is there an official SPEC document for the DELF format ?

**Comment by Somebodyisnobody** [comment]
No at the moment there's a XML Schema file which specifies the fields and the format only. A document which explains the handling of the DLEF-format like an RFC has not yet been created. I got positive feedback about the format structure as it enables tracking of who wanted to block or allow a website for hat reason in which category. Unfortunally I don't have the capacities to continue developing.
I thought that I would find more time to develop a system which makes users able to manage domains like a wiki and export a personaized hosts file by clicking DLEF sources together.
With @spirillen I planned this system to manage the domain lists not via github with commits etc. but with a nice web interface. the system would provide a DLEF file for other communities and read DLEF files from other communities. With github i saw the needs that sometimes we don't know from where a domain came and why it was blocked. So you would have searched the domain name in the webinterface and got all sources where stands which organization blocked the domain in his DLEF file with author contact, description and place for evidences that it's a bad site. It's a really nice idea but after one year I think it's simply too big for me.

**Comment by spirillen** [comment]
Should it be considered dead?

**Comment by Somebodyisnobody** [comment]
I would find that a pity. I would like to convince others of my idea, who have time and desire to implement it. And I don't want to reap the benefits later when it's finished just because I had the idea. The idea came to me through the maintenance of blacklists via git. I think that others also have these problems. I don't want to abuse the issue here to discuss the procedural processes of blacklist maintenance. Can we move this to another, openly space?

**Comment by spirillen** [comment]
How about the relocated original issue https://mypdns.org/infrastructure/workboard/-/issues/19 :smile:

**Comment by funilrys** [comment]
Great, come back here where you are ready with a spec that I can implement.

Right now, I don't really know which field I should use to extract the subject that needs to be tested ... Alone that will be useful ...

**Comment by funilrys** [comment]
Closing. Please reopen if you have more information for me.
