### ISSUE TITLE
Autocontinue subsystem do not work as expected in some rare cases

### ISSUE THREAD

**Issue by funilrys** [funilrys/PyFunceble#23]
Thanks to @dnmTX (https://github.com/Ultimate-Hosts-Blacklist/dev-center/issues/18 and all @Ultimate-Hosts-Blacklist issues he reported),

I was able to find out that in some rare cases the autocontinue subsystem may not work proprelly.

A patch to fix it is highly required.

**Comment by dnmTX** [comment]
Appreciate the recognition. Glad to help. Now...let's see how this gonna go,will keep monitoring.

**Comment by funilrys** [comment]
@dnmTX I'm one of those who release to prod on Friday night or Sunday 🤣

So it will be out there next week 😉
