### ISSUE TITLE
[Bug]: Fatal Error: [Errno 17] File exists: '/home/user/output/test.txt' 

### ISSUE THREAD

**Issue by ZeroDot1** [funilrys/PyFunceble#232]
## Bug description
It is not possible to test a file if the input file is located in the output directory.

## Modifications under `.PyFunceble.yaml`

DNS-Server

## Reproduction

`$ pyfunceble -w 12 --plain -a -f '/home/user/output/test.txt'`

## Expected behavior
That the test goes through normally.

## Screenshots
![Bildschirmfoto vom 2021-04-01 13-15-29](https://user-images.githubusercontent.com/28985171/113286348-5c18d300-92ec-11eb-882c-42ab7e653382.png)

## Versions

**OS:** for example Arch Linux (5.0.5-arch1-1-ARCH)
**Python Version:**  Latest
**PyFunceble Version:** Latest AUR Version 4 Beta X

## Additional context
```
[user@work ~]$ pyfunceble -w 12 --plain -a -f '/home/user/output/test.txt' 
/home/user/.local/lib/python3.9/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.25.11) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

██████╗ ██╗   ██╗███████╗██╗   ██╗███╗   ██╗ ██████╗███████╗██████╗ ██╗     ███████╗
██╔══██╗╚██╗ ██╔╝██╔════╝██║   ██║████╗  ██║██╔════╝██╔════╝██╔══██╗██║     ██╔════╝
██████╔╝ ╚████╔╝ █████╗  ██║   ██║██╔██╗ ██║██║     █████╗  ██████╔╝██║     █████╗
██╔═══╝   ╚██╔╝  ██╔══╝  ██║   ██║██║╚██╗██║██║     ██╔══╝  ██╔══██╗██║     ██╔══╝
██║        ██║   ██║     ╚██████╔╝██║ ╚████║╚██████╗███████╗██████╔╝███████╗███████╗
╚═╝        ╚═╝   ╚═╝      ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚══════╝╚═════╝ ╚══════╝╚══════╝

You are using the Beta version of PyFunceble 4.0.0!
Please take the time to communicate with us when you notice
something unusual.


Fatal Error: [Errno 17] File exists: '/home/user/output/test.txt'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py", line 866, in start
    self.fill_to_test_queue_from_protocol()
  File "/usr/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py", line 595, in fill_to_test_queue_from_protocol
    handle_file(protocol)
  File "/usr/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py", line 457, in handle_file
    cleanup_if_necessary(protocol["destination"])
  File "/usr/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py", line 429, in cleanup_if_necessary
    running_file_helper.write(
  File "/usr/lib/python3.9/site-packages/PyFunceble/helpers/file.py", line 159, in write
    DirectoryHelper(os.path.dirname(self.path)).create()
  File "/usr/lib/python3.9/site-packages/PyFunceble/helpers/directory.py", line 153, in create
    os.makedirs(self.path)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/user/output/test.txt'

[user@work ~]$ 

```

**Comment by funilrys** [comment]
Hey @ZeroDot1, thanks for the feedback.

With 4.x people should avoid to have their files located at the same location as the defined (per environment variable) or pre-defined (as per docs) output directory.

I'm not sure that this is a real issue because my solution to that will be to delete the `/home/user/output/test.txt` so that I can create the output directory. I'm not sure that it is in our interest to delete the input file (`-f`).

What do you think of this ?

**Comment by ZeroDot1** [comment]
I suggest to move the test file automatically to the document directory if the file is in the output directory and then start the test automatically with the new path.

**Comment by funilrys** [comment]
Hey @spirillen @mitchellkrogza @DandelionSprout,

what's your POV on this?

**Comment by spirillen** [comment]
:laughing: I kind a suggested this myself earlier and i had a broad smile on my face as I was reading this one yesterday. :+1: 

But a lesson learned is this actually is bad as default, but I would for sure welcome a switch for it. I reason example is my test of the [AdAway](https://github.com/AdAway/adaway.github.io/issues/246) list. where a second and third retest would be in best practice for verification before suggesting deletions (Do to my sad connection)

The pitfalls by doing this by default, is if you make a mistake, your first run would be gone as in gone and for huge lists this means days of testing.

**Comment by funilrys** [comment]
@ZeroDot1, sorry but I'm closing this. @spirillen explained why this is a bad idea.
