### ISSUE TITLE
Assign filetype suffixes to output files to make them faster to open in Windows

### ISSUE THREAD

**Issue by DandelionSprout** [funilrys/PyFunceble#235]
**Is your feature request related to a problem? Please describe.**
Currently, in the generated `output` folders, the files are named e.g. `list`, `INACTIVE`, `INVALID`, with no suffix. This means that Windows' "Which app do you want to open this file with?" dialogue shows up every time I want to open such files, losing about 2sec each time.

**Describe the solution you'd like**
Append `.txt` to the `list`/`ACTIVE`/`INACTIVE`/`INVALID`-named output files.

**Describe alternatives you've considered**
None that I'm aware of at the time of writing.

**Additional context**
Tested with `4.0.0b41.dev`

**Comment by funilrys** [comment]
Deployment completed. It should be available for testing.

Closing, but feel free to reopen or commenting after testing.
