### ISSUE TITLE
Odd error: "Fatal Error: A DNS query response does not respond to the question asked."

### ISSUE THREAD

**Issue by DandelionSprout** [funilrys/PyFunceble#236]
## Bug description

When running https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts through PyFunceble, I received the titular error near the end of the run.

## Modifications under `.PyFunceble.yaml`

None that I'm aware of.

## Reproduction

1. Download `https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts` locally.
2. Remove `127.0.0.1 ` from all entries (I seem to have forgot how to get PyFunceble to run through hosts files natively. 😅), then save it as `yhosts.txt`
3. Run `PyFunceble -f yhosts.txt`
4. Wait for approx. 50min to let it go through circa 8,000~9,000 entries.
5. Receive the error.

## Expected behavior

That PyFunceble goes through all their domains correctly.

## Screenshots

![image](https://user-images.githubusercontent.com/22780683/119433227-1e499100-bd16-11eb-9333-dabafc99c8bf.png)

## Versions

**OS:** Windows 10 21H1
**Python Version:** 3.7.7
**PyFunceble Version:** 4.0.0b48.dev (Blue Duckling)
**Command line:** Cygwin 3.1.7
**PyFunceble installation method:** pip3

## Additional context

None that I'm currently aware of.

**Comment by funilrys** [comment]
Closing as 4.0.0b49 has been deployed. It should contain the patch that fixes this issue. 

Thank you for the feedback @DandelionSprout 🎉
