### ISSUE TITLE
PyFunceble 4 fails to recognise "!" lines as comments that should not be included in the search

### ISSUE THREAD

**Issue by DandelionSprout** [funilrys/PyFunceble#237]
## Bug description

When running https://raw.githubusercontent.com/DandelionSprout/adfilt/master/GDPR%20451%20List.txt through PyFunceble 4.0.0b48dev, PF incorrectly interprets every single individual word in `!`-type commented-out lines as domains.

## Modifications under `.PyFunceble.yaml`

None that I'm aware of.

## Reproduction

1. Save `https://raw.githubusercontent.com/DandelionSprout/adfilt/master/GDPR%20451%20List.txt` locally on your PC.
2. Run `PyFunceble -f 'GDPR 451 List.txt'`
3. See the faulty processing

## Expected behavior

`!`-type comments are ignored by PyFunceble, similarly to what I presume that `#`-type comments are.

## Screenshots

![image](https://user-images.githubusercontent.com/22780683/120894062-d29cbe80-c616-11eb-81fb-5f68b21d88e1.png)

## Versions

**OS:** Windows 10 21H1
**Python Version:** 3.7
**PyFunceble Version:** 4.0.0b48dev

## Additional context

None that I'm currently aware of.

**Comment by spirillen** [comment]
Nice catch, but I thought we had this one fixed :unamused: 

From your dump, I'll suggest that all lines starting with a special character is considered a comment line to hit as broad as possible & that any such lines anyway always would be a INVALID.

Characters in question to be added as comment line

```
!"#¤%&/()=?'*~"^
```

**Comment by funilrys** [comment]
Hello there, I'm not ready to accept all possible comments characters. The most common ones are `#` and `!`. 

I'm not going to follow the `!"#¤%&/()=?'*~"^` suggestion. But I'll implement extend the source code to support the `!` character. 

Stay safe and healthy.

**Comment by funilrys** [comment]
Closing as `b50` should be able to handle this. 

Feel free to reopen or comment if something is not clear after your test of `b50`.

**Comment by spirillen** [comment]
> Hello there, I'm not ready to accept all possible comments characters. The most common ones are `#` and `!`.

Hey @funilrys You should at least append `//` as they are supported by ICS Bind9 <https://downloads.isc.org/isc/bind9/9.16.16/doc/arm/html/configuration.html#a-caching-only-name-server>

**Comment by funilrys** [comment]
Hey @spirillen, this issue is all about the decoding of plain text and host files.

The decoding of your RPZ format is handled differently. If you look at the source code, it's already supported:

CF:

https://github.com/funilrys/PyFunceble/blob/bf704a852424cc0f4238467b614e882a19943f1a/PyFunceble/converter/rpz_input_line2subject.py#L65

Cheers!

**Comment by spirillen** [comment]
It wasn't about RPZ :smirk: it is about trying to predict what might be extracted from various sources before they got into pyfunceble :wink: 

I know they are fixed for RPZ decoding, also why I actually was surprised it wasn't added to the "plain text" decoding :wave:
