### ISSUE TITLE
FR: List test file in status area

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#238]
**Is your feature request related to a problem? Please describe.**
As you can see on the screenshot below, I've tested for sources. But witch printed status applies to which sources??

**Describe the solution you'd like**
Have a "title" for each status print telling which source the status belongs to.

Why imagine the status for my [dead-hosts](https://github.com/mypdns/dead-hosts) if you ran that in a terminal. You will be lost.

**Describe alternatives you've considered**
Non for now

**Additional context**
![image](https://user-images.githubusercontent.com/44526987/121675810-2e05fb00-cab4-11eb-90e3-7add45037795.png)

**Comment by funilrys** [comment]
Hi @spirillen, they are in the same order you declared them.

**Comment by spirillen** [comment]
Moved "issue" to https://github.com/spirillen/PyFunceble/issues/45 for adding this to the docs.
