### ISSUE TITLE
bug: requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#241]
:BUHUU: :bug: 

`requests.exceptions.TooManyRedirects: Exceeded 30 redirects.`

Source:
  - https://github.com/mypdns/porn-records/runs/2924212453?check_suite_focus=true#step:10:5092
  - https://github.com/mypdns/porn-records/runs/2923129154?check_suite_focus=true#step:10:5091
  - https://github.com/mypdns/porn-records/runs/2923340642?check_suite_focus=true#step:10:5091
  - https://github.com/mypdns/porn-records/runs/2923353903?check_suite_focus=true#step:10:5092
  - https://github.com/Clefspeare13/pornhosts/runs/2923719581?check_suite_focus=true#step:7:66
  - https://github.com/Clefspeare13/pornhosts/runs/2924389608?check_suite_focus=true#step:7:66
  - https://github.com/Clefspeare13/pornhosts/runs/2925135558?check_suite_focus=true#step:7:66

_Originally posted by @spirillen in https://github.com/funilrys/PyFunceble/issues/101#issuecomment-869158475_

**Comment by funilrys** [comment]
What the hell are you testing ... That's something new ... Who redirects more than 30 times !??

**Comment by spirillen** [comment]
> What the hell are you testing ... That's something new ... Who redirects more than 30 times !??

:rofl: 

google?? maybe!! I don't know, can't see the record in question :smirk:
