### ISSUE TITLE
BUG?:  hint: (e.g., 'git pull ...') before pushing again.

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#242]
## Description

This is my first seeing, of this error in a while, which makes me kind a believe it can be related to https://github.com/funilrys/PyFunceble/issues/241

## Configuration
See: https://mypdns.org/my-privacy-dns/matrix/-/blob/3ccc8d5e00709caedd0b6b6e171584e45584f8c7/.pyfunceble/.PyFunceble.overwrite.yaml

## Reproduction

1. https://github.com/mypdns/matrix/runs/2925022834?check_suite_focus=true#step:9:17

## Expected behavior

Let's see...

## Versions

**OS:**, **Python Version:**, **PyFunceble Version**:
  - https://mypdns.org/my-privacy-dns/matrix/-/blob/3ccc8d5e00709caedd0b6b6e171584e45584f8c7/.github/workflows/main.yml

**Comment by funilrys** [comment]
That's weird, I think I do everything correctly:

https://github.com/funilrys/PyFunceble/blob/a2244be80fdfd847864770655563a0a524428017/PyFunceble/cli/continuous_integration/base.py#L1119-L1128

**Comment by spirillen** [comment]
> That's weird, I think I do everything correctly:
> 
> https://github.com/funilrys/PyFunceble/blob/a2244be80fdfd847864770655563a0a524428017/PyFunceble/cli/continuous_integration/base.py#L1119-L1128

True

If we dig a bit deeper, well also notice the error concerns 


https://mypdns.org/my-privacy-dns/matrix/-/blob/3ccc8d5e00709caedd0b6b6e171584e45584f8c7/.github/workflows/main.yml#L75
