### ISSUE TITLE
FEATURE: Headsup that future versions of PyFunceble must not require cryptography ≥3.4, because its use of Rust makes it impossible to install or handle in Cygwin

### ISSUE THREAD

**Issue by DandelionSprout** [funilrys/PyFunceble#249]
## Description

Okay, so after 6 hours of looking into why Cygwin didn't want to install PyFunceble 4.0.0b62, there appears to be multiple major problems with the "cryptography" package in PyFunceble's dependency list, at least one of which is fatal:

PyFunceble currently requires `cryptography 3.3.2` or higher. By default, all PyFunceble installation methods I've tried, currently tries to install 3.4.7.

Cryptography 3.4.0 and higher, require a working Rust compiler on one's system, which causes a whole lot of problems. On Windows, this requires installing Visual Code 2019's "Build Environment for C++", which takes up a disproportionally massive 6 GB of HDD space. Moreover, for reasons that confuse me to the point I'm having problems reciting them properly, Cygwin and/or `pyo3` are unable to detect installed Rust compilers properly, instead falsely claiming it can't find `usr/bin/python3.8` in PATH (as the Rust compiler was clearly designed for PowerShell only), while also complaining about being unable to handle PEP 517 encryption without `cryptography`.

I did eventually learn that I could install `pip install cryptography==3.3.2` (which I successfully did), which means it's not the end of the world for me at the moment, but it does make me worried for future versions of PyFunceble.

This gives 3 possible options for how to handle this on you guys' (funilrys and spirillen) end:

## Possible Solution

1) Make `requirements.txt` stay on `cryptography>=3.3.2` for as long as physically possible.
2) Remove the dependency on the `cryptography` package.
3) I've seen vague claims that adding info on `pyo3` to `Cargo.toml` could fix it, although PyFunceble has no such file.

## Considered Alternative

One semi-plausible possibility could be to change the dependency into `python38-cryptography` and its equivalents for older Python versions.

It must be stated very strongly: Requiring `cryptography` 3.4 would mean that I can no longer use PyFunceble.

## Additional context

Python version: 3.8.10

**Comment by funilrys** [comment]
For the story follow `https://github.com/pyca/cryptography/issues/5771`. A special dependency file for windows will be provided.

**Comment by funilrys** [comment]
I will do it because PyFunceble is running in highly automated environments.

But, please keep in mind, that you should really try to install it correctly: https://cryptography.io/en/3.4.5/installation.html#building-cryptography-on-windows

**Comment by DandelionSprout** [comment]
Shy of anyone figuring out a way to compile Rust itself for Cygwin, it is sadly impossible for me to correctly install cryptography 3.4 for use in my work environment, from what I read up on about the matter 2 weeks ago.

**Comment by funilrys** [comment]
@DandelionSprout, @spirillen is working on documenting this #247. But let's consider this a non-issue as https://github.com/funilrys/PyFunceble/commit/6051c636473606fa95a2d4b011dab9384b536db5 works around this.

**Comment by spirillen** [comment]
Ping @spirillen to follow the workaround, to see if a note is needed......

**Comment by DandelionSprout** [comment]
Given that requiring Rust (or working around it with older packages) can be a make-or-break for some categories of potential users, this does sound like it'd qualify as a known issue.

**Comment by spirillen** [comment]
Hey @DandelionSprout 

Did the patch in commit https://github.com/funilrys/PyFunceble/commit/6051c636473606fa95a2d4b011dab9384b536db5 workaround this issue properly??

https://github.com/funilrys/PyFunceble/commit/6051c636473606fa95a2d4b011dab9384b536db5#diff-14138d007c8c5ea96638c34a39ab76db7139da485b98fb598f2a012da21b37a4R3

**Comment by funilrys** [comment]
WARNING: The patch only touches people/machines that are going to install PyFunceble under Windows.

**Comment by spirillen** [comment]
> WARNING: The patch only touches people/machines that are going to install PyFunceble under Windows.

That is also what all this is about, for what I understand. 

My question solely concerns whether a "known bug" is to be written or not, but as @DandelionSprout confirms you (@funilrys) have solved this in https://github.com/funilrys/PyFunceble/commit/6051c636473606fa95a2d4b011dab9384b536db5 I do not see any reasons for making any further text about this for know.

The only reason I can see this should be relevant, is IF, any fresh install of version 4.x should experience this issue again.

Correct me if I misunderstood something here.

**Comment by funilrys** [comment]
Fresh installation of 4.x within windows shouldn't meet this issue ever again. But I would still recommend people to upgrade their cryptography package if they can ...
