### ISSUE TITLE
FEATURE: Autocompletion of args

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#251]
## Description
It burring, you makes mistakes, we should have though of this a long time ago...

We are on Linux right? so why is it we haven't studied how we can make the args to become autocomplete with our most beloved :heart: TAB :heart_eyes: 

## Possible Solution
Do some scripting....

## Considered Alternative
Have someone else to type for you.... :laughing:

**Comment by funilrys** [comment]
I like the idea. But it may take some time. I want to roll out 4.0.0 first (it's about time!?)

**Comment by spirillen** [comment]
I don't understand you haven't merged @dev with @master after the fix last knight it for sure solved the issue and I have been running the script on every single Ubuntu I have with success. So we did find the right issue.

**Comment by spirillen** [comment]
I think we have... I haven't noticed that we should be missing anything :smile:
