### ISSUE TITLE
BUG: GitLab-CI

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#256]
## Description
As GHA is killing all our test jobs I decided to move on an install my own Gitlab-runners on mypdns. The thing is now that we have released the long time beta to stable I find this bug...

As setting up the pyfunceble  runner on gitlab is new, I take the risk of posting a Homer "DDOOH"

As mentioned before this is rather new so I started out with the template from the [docs](https://pyfunceble.readthedocs.io/en/dev/usage/index.html#gitlab-runner-ci-cd) made a few tweeks and thing seems to be fine until I added a real file (bigger) the `--ci-max-minutes` started to trouble as it appears it is not respected in either the Command Line or in `.pyfunceble/.PyFunceble.overwrite.yaml`

## Reproduction
See the follow collection for the complete image

The CI job: https://mypdns.org/my-privacy-dns/matrix/-/jobs/1389#L881
The commit with the alternation of `.gitlab-ci.yml` https://mypdns.org/my-privacy-dns/matrix/-/commit/8625d9bd9cd90fd898b5a7dc55889910d26e3273
Merge request: https://mypdns.org/my-privacy-dns/matrix/-/merge_requests/4

## Expected behavior
The job ran for 1 hour and got killed while the `--ci-max-minutes 5`

## Versions

**OS:** python:latest

**Python Version:** python:latest

**PyFunceble Version:** 4.0.0

**Comment by spirillen** [comment]
Not really, it's all on the docs.gitlab.com, but the variables keeps changing so it is my best advice to look there

a search https://duckduckgo.com/?q=site%3Adocs.gitlab.com+gitlab-runner+variables&t=ffab&ia=web gives me these feedback's

https://docs.gitlab.com/ee/ci/variables/

https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

As usual I've left it as default as possible, to keep it simple stu*** (KISS)

**Comment by funilrys** [comment]
I mean, maybe some environment are there on https://gitlab.com but not on self-hosted nodes ...

**Comment by spirillen** [comment]
> I mean, maybe some environment are there on https://gitlab.com but not on self-hosted nodes ...

I counted on that within my reply, but i can't find any docs on that.

**Comment by funilrys** [comment]
@spirillen, I just tested within mydns.org and it's working. Meaning that you are missing at least one of the following environment variables.

- `GIT_EMAIL` (Commit Author Email)
- `GIT_NAME` (Commit Author Name)
- `GL_TOKEN` (GitLab Token to use to push changes)
