### ISSUE TITLE
[Feature request]: Generate WWW list

### ISSUE THREAD

**Issue by ZeroDot1** [funilrys/PyFunceble#26]
**Describe the solution you'd like**
Generate an additional list with WWW subdomains.
Some lists have subdomains with WWW.BEISPIEL.COM
And with many missing these WWW subdomains simply, therefore I suggest for each repository an additional WWW list to the Active Invalid etc. to generate.
This is very helpful for many people.

**Additional context**	
The folder structure should then look like this.
ACTIVE
INACTIVE
INVALID
VALID
WWW
.keep

**Comment by funilrys** [comment]
Hallo @ZeroDot1 ich hoffe das du ein schönen Woche hattest,

Thanks for this feature request. Are you coming from @dead-hosts, @ultimate-hosts-blacklist or it is an idea out of nowhere? :smile_cat: 

Indeed, @ultimate-hosts-blacklist generate all `www` on its side but yes I follow your point.

For the context, we actually do not generate all `www` (under @dead-hosts or when running from the CLI) but I will integrate the generation of all `www.` in the future. 

May I ask how can a `WWW` directory be helpful?

Do you mean helpful in the way that it will let you get a list of all `www.` to include in your list or in the way that it helps differences the `bare` from the `www.bare` one?

Thanks again for your time.

Cheers,
Nissar

**Comment by ZeroDot1** [comment]
Hallo @funilrys, Ich habe niemals Wochenende, bei mir wird dauergearbeitet, auch wenn ich dafür kein Geld bekomme, Irgend wer muss ja die (BöseN BöseN Coinminer) ärgern :D
@funilrys Ich wünsche dir ein schöne Wochenende.

[GERMAN]:
Ich habe eine Liste mit Sachen die unbedingt in einigen Opensource Projekten ergänzt werden müssten :dagger: 

Eine WWW liste würde mir in dem Speziellen Fall der CoinBlockerLists sehr helfen das ich diese dann direkt übernehmen könnte.
Weiterhin würde eine Extra WWW Liste den Entwicklern der Blacklisten helfen die Listen effektiver machen zu können.
Leider habe ich nicht die Möglichkeit das von meinem Heimnetzwerk aus zu machen, daher würde sich die Generierung der WWW Listen mit deiner Software anbieten.

[ENGLISH]:
I have a list of things that need to be added in some open source projects

A WWW list would help me a lot in the special case of CoinBlockerLists that I could use it directly.
Additionally an extra WWW list would help the developers of the blacklists to make the lists more effective.
Unfortunately I don't have the possibility to do this from my home network, so generating the WWW lists with your software would be a good idea.

Translated with www.DeepL.com/Translator
