### ISSUE TITLE
Maintenance idea: A way to automate live CLI demos

### ISSUE THREAD

**Issue by veracioux** [funilrys/PyFunceble#260]
Disclaimer: This is shameless self-promotion, but I think this project could benefit from my suggestion.

## Description

Hi, I have noticed you use asciinema to create live demos, like [on your official website](https://pyfunceble.github.io/#/). I have created CLI demos for a few projects of mine, and I know how frustrating it can be when you make mistakes and have to do it all over again (or maybe I'm doing something wrong).  In any case, I think that automating the CLI demos is not a bad idea. In your demos, I have noticed that sometimes you make typos and correct yourselves in the demo, so I'm assuming you aren't already using a program to automate them.

## Possible Solution

I have created a small bash program just for that: [tuterm](https://github.com/veracioux/tuterm). You write a script that contains all the commands that should be demonstrated. Then you run one simple command with that script as its argument. And the program replays the demo in the terminal in real time.

This way:
- You don't have to worry about mistakes while typing
- If your program's CLI interface changes, you can update the demo without any manual work
- You can upload to asciinema with just one simple command

**Another benefit of tuterm**
You can use the exact same script (or with modifications, optionally) to run an interactive tutorial that prompts the user with commands and the user has to type them out. This is a great way IMO for users to learn CLI programs!

## Considered Alternative

I've never encountered a program that automates the creation of live CLI demos. After all, that is the reason why I created tuterm. Granted, I am not a very experienced user of CLI/open source/etc.

## I can do the work

I'll be happy to recreate the demos on your website using tuterm, so you don't have to learn it yourself. Or I can additionally improve the demos according to your feedback.

**Comment by spirillen** [comment]
> I'll be happy to recreate the demos on your website

As one of the docs maintainer, I think it could be a very good idea to have the asciinema clips updated to match the new PyFunceble 4.x as there are many new feature, and some of the arguments simply are [deprecated](https://github.com/funilrys/PyFunceble/blob/dev/docs/usage/deprecated-arguments.rst)

I could also be a idea to make a few "videos" demonstrating, you can use PyFunceble in relation to more "advanced" use cases like like chose in the [Show and Tell](https://github.com/funilrys/PyFunceble/discussions/categories/show-and-tell)

Just a reply with a couple of first thoughts :thought_balloon:
