### ISSUE TITLE
FEATURE: Have Adblock, Adguard, and uBlock syntax all be "SPECIAL" or even "ADBLOCK" rules instead of having a separate "adblock" mode.

### ISSUE THREAD

**Issue by T145** [funilrys/PyFunceble#266]
This will allow the `--adblock` parameter to be removed, and any list with adblock rules can be processed alongside other lists.

**Comment by spirillen** [comment]
I (personally) would not vote for this, as all the regex and other code explicitly used for the `--adblock` code, would add to much extra and unnecessary system load doing test and the inpacting system load is already more than high enough.

And the `--adblock` and SPECIAL rules are 2 very different things
  1. The `--adblock` handles uBlock like rules, by first decoding the rules and then test what might be urls **and** domains
  2. The SPECIAL rules https://mypdns.org/spirillen/PyFunceble/blob/master/docs/components/special-rules.rst is a set of rules which solely react to the `HTTP status return code`

This is my _**personal**_ opinion.
