### ISSUE TITLE
FEATURE: Showing Domain registrar info

### ISSUE THREAD

**Issue by ryanbr** [funilrys/PyFunceble#272]
Not sure if this is an option, But when scanning Easylist/Easyprivacy, it could output domain providers also. Maybe have stats at the end showing the top 10/20 domain registrars used by various ad servers

**Comment by funilrys** [comment]
Hi @ryanbr, can you extend "it could output domain providers also."?

Stats at the end with the top provider shouldn't be an issue - though.

**Comment by funilrys** [comment]
Hey @ryanbr have you tested the feature ?

I would love to get your feedback.

Merry Christmas 🎅 🎄
