### ISSUE TITLE
BUG: KeyError: 'collection'

### ISSUE THREAD

**Issue by ZeroDot1** [funilrys/PyFunceble#273]
`yay -S pyfunceble-dev ` Everything was installed properly and new.

`pyfunceble -w 32 --plain -a -f  deine Datei hier...`

```py
/home/user/.local/lib/python3.9/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.25.11) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
/usr/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/x509.py:15: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/bin/pyfunceble", line 33, in <module>
    sys.exit(load_entry_point('PyFunceble-dev==4.0.2b2', 'console_scripts', 'pyfunceble')())
  File "/usr/lib/python3.9/site-packages/PyFunceble/cli/entry_points/pyfunceble/cli.py", line 1086, in tool
    PyFunceble.facility.ConfigLoader.start()
  File "/usr/lib/python3.9/site-packages/PyFunceble/config/loader.py", line 402, in start
    PyFunceble.storage.COLLECTION = Box(copy.deepcopy(config["collection"]))
KeyError: 'collection'

```

**Comment by spirillen** [comment]
Just info sharing:

> Yet another Yogurt - An AUR Helper written in Google go

**Comment by ZeroDot1** [comment]
> Just info sharing about `yay`:

It is completely irrelevant with which AUR helper I build the package, the result is unfortunately the same.

**Comment by spirillen** [comment]
> It is completely irrelevant with which AUR helper I build the package, the result is unfortunately the same.

That's not good, I'll leave it to @funilrys , I was just pasting the info on what yay was as it was new to me, it might be it for others as well :smiley: 

I have also over the past week had some issues similar to this, but they seems to have been solved outside this here, so it can have some relation to other packages like python ie I had to install python 3.1 from the source to have it working. (ubuntu).

**Comment by DandelionSprout** [comment]
I'm receiving a very similar error as the OP, with PyFunceble-dev-4.0.2b2, Python3.8, and installing with pip:
```
$ PyFunceble -v
Traceback (most recent call last):
  File "/usr/local/bin/PyFunceble", line 8, in <module>
    sys.exit(tool())
  File "/usr/local/lib/python3.8/site-packages/PyFunceble/cli/entry_points/pyfunceble/cli.py", line 1086, in tool
    PyFunceble.facility.ConfigLoader.start()
  File "/usr/local/lib/python3.8/site-packages/PyFunceble/config/loader.py", line 402, in start
    PyFunceble.storage.COLLECTION = Box(copy.deepcopy(config["collection"]))
KeyError: 'collection'
```
