### ISSUE TITLE
FEATURE: argument *-only

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#276]
## Description
I often have to test input source before adding them or before altering any data by testing them against only one or two of the test options @Pyfunceble provides ie usual whois or dns.

When I then have to test with only `--dns` and/or `--whois-lookup`, then we need to flip every other fixed values from standard pyfunceble config files. If we now had the ability to append a `-only` switch which could do this, by setting all other test to `false` that isn't explicitly given as `-only` argument

## Possible Solution
In the following example only the `--dns-lookup` and `--whois-lookup` module used for testing
```shell
pyfunceble -f ../live.txt --dns-lookup-only --whois-lookup-only
```

In the following example only the `--whois-lookup` module used for testing
```shell
pyfunceble -f ../live.txt --whois-lookup-only
```

In the following example only the `--dns-lookup` module used for testing
```shell
pyfunceble -f ../live.txt --dns-lookup-only
```

## Considered Alternative
A hole lot of typing even when activating the [tab autocompletion](https://github.com/funilrys/PyFunceble/issues/251)

## Additional context
Read more about the new autocompletion and how to se it in the docs: https://pyfunceble.readthedocs.io/en/master/usage/index.html

**Comment by funilrys** [comment]
Does anyone want this (too) ?

Asking for help: @ZeroDot1 @mitchellkrogza @DandelionSprout and others.
