### ISSUE TITLE
BUG: INAVALID marked as INACTIVE

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#278]
## Description

From [output/merged_results/domains/INACTIVE/list](https://mypdns.org/my-privacy-dns/porn-records/-/blob/b905db9ff6397dc86366b7aff99c1c19f39bd489/active_domains/output/merged_results/domains/INACTIVE/list#L5-28)

AND Do also notice the CIDR notated IP adresses where the CIDR is prepended accortding to DNS RPZ 

```
# Generated by PyFunceble (v4.0.2b7.dev) / https://git.io/vpZoI
# Date of generation: 2021-12-03T04:30:59.977213


1
32.43.150.158.51
32.174.136.140.78
32.175.136.140.78
32.183.136.140.78
32.134.184.98.87
32.55.66.199.128
32.174.108.251.162
32.242.182.208.173
32.179.40.170.178
32.18.213.23.185
32.19.213.23.185
32.20.213.23.185
32.236.95.217.185
32.220.99.187.194
32.221.99.187.194
32.222.99.187.194
32.223.99.187.194
32.224.99.187.194
32.189.51.95.209
32.223.105.126.209
32.184.4.239.222
1821
cdn7.xxnx.bike
```

## Configuration
https://mypdns.org/my-privacy-dns/porn-records/-/blob/b905db9ff6397dc86366b7aff99c1c19f39bd489/.pyfunceble/.PyFunceble.overwrite.yaml

## Reproduction
https://mypdns.org/my-privacy-dns/porn-records/-/blob/b905db9ff6397dc86366b7aff99c1c19f39bd489/scripts/DataTesting.bash#L83-107

## Versions

**OS:** Ubuntu 20.04.3

**Python Version:** 3.10

**PyFunceble Version:** v4.0.2b7.dev

**Comment by funilrys** [comment]
Hi @spirillen,

this one is expected - as of now - because you are using the `local_network` thing. 

Cheers!

**Comment by spirillen** [comment]
Mostly to @spirillen & @funilrys DOC improvement: https://mypdns.org/spirillen/PyFunceble/-/issues/50
