### ISSUE TITLE
BUG: VALID domains marked INVALID

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#282]
## Description

https://mypdns.org/my-privacy-dns/porn-records/blob/f16754525807bca2ef5f44ade66774b3d47f7b28/active_domains/output/domains.matrix/domains/INVALID/list#L5

https://mypdns.org/my-privacy-dns/porn-records/-/blob/4c5d12ff4f4d72a03e217b05862d3a2f333fc109/active_domains/output/domains.matrix/domains/INVALID/list#L5

## Configuration
https://mypdns.org/my-privacy-dns/porn-records/-/blob/master/.pyfunceble/.PyFunceble.overwrite.yaml

## Reproduction

1. https://mypdns.org/my-privacy-dns/porn-records/-/blob/master/scripts/DataTesting.bash

## Expected behavior

That PyFunceble know what a domain valid domain is

## Screenshots

![image](https://user-images.githubusercontent.com/44526987/145009068-f391da6c-0dc2-402f-8fae-e5f98de5e247.png)

## Versions

**OS:** ubu 20

**Python Version:** 3.10

**PyFunceble Version:** 4.0.2

**Comment by funilrys** [comment]
Was/Is the DNS lookup activated ?

**Comment by spirillen** [comment]
> Was/Is the DNS lookup activated ?

https://mypdns.org/my-privacy-dns/porn-records/-/blob/7a61fd8c79481b6a8dcd554d93a745e4502535f9/.pyfunceble/.PyFunceble.overwrite.yaml#L34

**Comment by funilrys** [comment]
Yup! Exactly what I thought. The patches referenced here should fix that.
