### ISSUE TITLE
HELP: Configuration file .PyFunceble.overwrite.yaml not working

### ISSUE THREAD

**Issue by bigdargon** [funilrys/PyFunceble#299]
From issue https://github.com/dead-hosts/dev-center/issues/25

## Description

Hi,

I need to bother you a bit about configuring the `.PyFunceble.overwrite.yaml` file, it doesn't seem to work. 

I have edited the file according to the instructions https://github.com/bigdargon/hostsVN-dead-hosts/blob/master/.pyfunceble/.PyFunceble.overwrite.yaml, but sometimes the Action still does not continue when the default .PyFunceble.yaml file is overwritten https://github.com/bigdargon/hostsVN-dead-hosts/commits/master/.pyfunceble/.PyFunceble.yaml.

For now, I still manually delete the `.PyFunceble.yaml` file to keep the Action running. Thanks again for your project!

**Comment by funilrys** [comment]
That's because it's should follow the yaml format of the initial configuration file...

**Comment by bigdargon** [comment]
I used to edit in yaml format https://github.com/bigdargon/hostsVN-dead-hosts/commit/8f1ec62d6a9129cb558dacedb2bfb503e4507f93, but the Action still failed so I tried this. Anyway, I fixed the new format and waited to run the Action again. Thank you!

**Comment by bigdargon** [comment]
@funilrys I have discovered some details

When the Action fails, an error is generated at line 162 in the config file https://github.com/bigdargon/hostsVN-dead-hosts/runs/6927935203?check_suite_focus=true

```
  in "/home/runner/work/hostsVN-dead-hosts/hostsVN-dead-hosts/.pyfunceble/.PyFunceble.yaml", line 162, column 6
```

I see line 162 with configuration https://github.com/bigdargon/hostsVN-dead-hosts/blob/d25b34101f17a240bfa10f14e8e1b04436d0179f/.pyfunceble/.PyFunceble.yaml ` http: null`

While the config file on which the Action works is only 161 lines https://github.com/bigdargon/hostsVN-dead-hosts/blob/4b7aa6f49efc68a7f5235851ac96e64aadfb3dad/.pyfunceble/.PyFunceble.yaml

Hope this is helpful to you!

**Comment by bigdargon** [comment]
@funilrys I found, everytime the Action fails due to auto configuration add the following lines https://github.com/bigdargon/hostsVN-dead-hosts/commit/d26a5ec8c28721b1af023f89468c2d4a18460de7

```
 http: null
        https: null
    rules: []
share_logs: false
user_agent:
    browser: chrome
    custom: null
    platform: linux
verify_ssl_certificate: false
```

The added configuration is wrong with the format, resulting in the Action being failed

```
proxy:
    global:
        http: null
        https: null
    rules: []
```

I think this is the cause of the Action not working!

**Comment by funilrys** [comment]
Might be it @bigdargon 😄

**Comment by funilrys** [comment]
Nice catch!

**Comment by funilrys** [comment]
@bigdargon , done.
