### ISSUE TITLE
Proposal logo for PyFunceble

### ISSUE THREAD

**Issue by ybreza** [funilrys/PyFunceble#3]
Hi Sir
If you are interested, I will donate a logo for your project. However, before I start it I need to ask your permission first ;). if I get permission, I need details of the logo like what you want :smile:

**Comment by funilrys** [comment]
Hello Reza @ybreza and welcome here!

Well, you have my permission...

The logo has to reflect the repository description. You can find more information about this repository into the [`README.md`](https://github.com/funilrys/PyFunceble/blob/master/README.md) and on the [Wiki](https://github.com/funilrys/PyFunceble/wiki). 
If you need to see the tool in action you can follow one of the instances of [Ultimate Hosts Blacklist](https://travis-ci.org/Ultimate-Hosts-Blacklist).

**Comment by ybreza** [comment]
![artboard 1](https://user-images.githubusercontent.com/35470865/40316524-c957ab26-5d48-11e8-8cfc-8aadc0bfae4b.png)

That's the logo I created for your app, before I wanted to create a logo by reflecting on the name of PyFunceble.

But when I read the ```wiki``` and ```readme```, I change my mind, and feel your project should have a unique and funny logo, and one day have a separate mascot

So I made a special PyFunceble logo for your project, I hope you like it, and choose what color you need

The good news, I already have an idea for her sister, Funceble;)

**Comment by funilrys** [comment]
Hi @ybreza,
the green versions look great as PyFunceble's logo but we will keep the other colors for other usages in the future as PyFunceble use 3 colors: 

- Green for `ACTIVE`
- Red for `INACTIVE`
- Blue for `INVALID`

Is it possible to have them all with a transparent background? Do you think that they can be converted to Ascii art so we can have it like [there](https://travis-ci.com/funilrys/PyFunceble/jobs/125119720#L524-L529) into the script?

Thanks for your effort.

P.S: The blue one (mascot with `PyFunceble`) does not have a transparent mouth and eyes...

**Comment by ybreza** [comment]
Google Drive Updated

[DOWNLOD](https://drive.google.com/open?id=1HUZqQ8zWJ4xg0BmMyb2uSRpEkJpy1I2W)

**Comment by ybreza** [comment]
Hi Sir, please check #6 ;)

**Comment by funilrys** [comment]
@ybreza Can you add bigger size for everybody to your drive so I can have them somewhere?

**Comment by funilrys** [comment]
@ybreza ^

**Comment by funilrys** [comment]
@ybreza ^

**Comment by ybreza** [comment]
I'am so sorry sir, @funilrys 
sorry I am late to respond sir, I was just on holiday to Papua, looking for something I needed for research :smile_cat: 

I'll make ```bigger size``` logo for you and upload it on my google drive asap

**Comment by ybreza** [comment]
All DONE. Drive Updated

[GOOGLE DRIVE](https://drive.google.com/open?id=1HUZqQ8zWJ4xg0BmMyb2uSRpEkJpy1I2W)
