### ISSUE TITLE
--quiet needs some output to keep Travis-CI awake

### ISSUE THREAD

**Issue by mitchellkrogza** [funilrys/PyFunceble#30]
**Is your feature request related to a problem? Please describe.**
`--quiet` of course gives no output (as expected) :joy_cat:  but it causes Travis-CI to fail due to no input received.

**Describe the solution you'd like**
A one line feedback message to Travis-CI every 30-60 seconds "PyFunceble - Testing in Progress"

**Describe alternatives you've considered**

**Additional context**
With multiprocess some builds can create very big logs so we eventually want PyFunceble to be quiet and not create build logs that are too big for Travis-CI

**Comment by spirillen** [comment]
May I suggest that the output for the combination of --quiet --travis-ci returns a dot "." for each tested domain on 1 line.

Why a new dot for each tested domain, well you have a max number of lines in the log.... where one line with 100.000 dots, well it is still only one line :)

**Comment by funilrys** [comment]
Feature introduced with https://github.com/funilrys/PyFunceble/commit/b194b37a744c78782250b1cf6ee863370cfdef02.

**P.S: Please DO NOT close this issue manually. This issue is going to be closed automatically once https://github.com/funilrys/PyFunceble/commit/b194b37a744c78782250b1cf6ee863370cfdef02 will be merged to master.**

**Comment by spirillen** [comment]
Little note on this ..... Read it with a smile....

My idea with a dot was to make óne loooooooooooong line, not [one dot per line](https://travis-ci.com/spirillen/Dead-Domains/builds/131228017) :grinning: 

```
......................................................................................................................................................
. So somehow you'll have to make it print that dot one the very same line as the previously dot .
......................................................................................................................................................
```

:dango:
