### ISSUE TITLE
FEATURE: Function to check valid IP v6 and v4 addresses.

### ISSUE THREAD

**Issue by ZeroDot1** [funilrys/PyFunceble#305]
I often see lists of invalid IP addresses, including my own lists.
We should have a function to check IPs for correctness like the domains.

**Comment by funilrys** [comment]
Hi @ZeroDot1,
as we use some native IPv4 and IPv6 checkers, I would need some examples .... PyFunceble is already capable of such a thing ... 

Cheers!

**Comment by ZeroDot1** [comment]
OK, I'll give you examples as soon as I can, right now I'm working on 8 things at the same time. Unfortunately, real life is completely crazy for me at the moment.

**Comment by funilrys** [comment]
No problem. Take care!

**Comment by funilrys** [comment]
Closing until an example is delivered. AFAIK PyFunceble is already capable of this.
