### ISSUE TITLE
BUG: Fatal Error: <subject> should be <class 'str'>, type(subject) given.

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#308]
## Description
Related to https://github.com/funilrys/PyFunceble/issues/303

## Configuration

See all details in https://mypdns.org/clefspeare13/pornhosts

## Reproduction

Ruin the availability test script (https://mypdns.org/clefspeare13/pornhosts/-/blob/master/toolbox/availability_test.bash)

## Expected behavior
:thinking: 

## Screenshots
![image](https://user-images.githubusercontent.com/44526987/196180733-2078ab56-bf5b-4fda-b6c3-ced93c30c702.png)

## Versions

**OS:** Ubu 22.04 / Conda

**Python Version:** 3:10

**PyFunceble Version:** 4.1.3a2.dev

**Comment by funilrys** [comment]
`4.1.3a3` should already solve this.

**Comment by spirillen** [comment]
Hang on to this, just noticed you bumped the version

on hold

**Comment by funilrys** [comment]
Closing as the source code that produces this specific fatal error message doesn't exist anymore in the `dev` branch or version. Feel free to reopen if it still somehow happens.
