### ISSUE TITLE
BUG: Fatal Error: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#309]
## Description
```python
Fatal Error: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
File "/home/$USER/.local/lib/python3.10/site-packages/PyFunceble/cli/system/launcher.py", line 990, in start
self.stop_and_wait_for_all_manager()
File "/home/$USER/.local/lib/python3.10/site-packages/PyFunceble/cli/system/launcher.py", line 927, in stop_and_wait_for_all_manager
self.tester_process_manager.wait()
File "/home/$USER/.local/lib/python3.10/site-packages/PyFunceble/cli/processes/base.py", line 330, in wait
raise worker_error
TypeError: argument of type 'NoneType' is not iterable
```

## Configuration

https://mypdns.org/clefspeare13/pornhosts/-/blob/3d76d585b55d841b0a3e4a93b46ade8e892aee24/PyFunceble/.PyFunceble.overwrite.yaml

## Reproduction

1. https://mypdns.org/clefspeare13/pornhosts/-/blob/3d76d585b55d841b0a3e4a93b46ade8e892aee24/toolbox/availability_test.bash
2. wait about a week
3. See error of incomplete work

## Expected behavior
:man_shrugging: 

## Screenshots
![image](https://user-images.githubusercontent.com/44526987/197219822-7e13910a-b662-49cc-b8d2-e9e78e145988.png)

## Versions

**OS:** Ubuntu 22.04.1 => miniconda 

**Python Version:** 3.10

**PyFunceble Version:** 4.1.3a3.dev

## Additional context
Failed build attempt https://mypdns.org/clefspeare13/pornhosts/-/commit/3d76d585b55d841b0a3e4a93b46ade8e892aee24

**Comment by funilrys** [comment]
Should be fixed in `4.1.3a4` 😄

**Comment by funilrys** [comment]
By the way, if you are email/RSS friendly, you can use https://libraries.io/pypi/PyFunceble-dev and https://libraries.io/pypi/PyFunceble to get informed of new releases 😉

**Comment by funilrys** [comment]
Feel Free to reopen if it happens again.

**Comment by spirillen** [comment]
> By the way, if you are email/RSS friendly, you can use https://libraries.io/pypi/PyFunceble-dev and https://libraries.io/pypi/PyFunceble to get informed of new releases wink

Never used RSS or other subscriptions as it tent to just be a bunch of information overflow = bulk delete all :bin:
