### ISSUE TITLE
BUG: Dead-hosts cannot run scheduled Actions

### ISSUE THREAD

**Issue by bigdargon** [funilrys/PyFunceble#324]
## Description

Scheduled trigger action not working https://github.com/bigdargon/hostsVN-dead-hosts/actions/runs/3561953313/jobs/5983659215

```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/hostsVN-dead-hosts/hostsVN-dead-hosts/actions/workflows
```

Link above error not found, I try this link it works https://api.github.com/repos/bigdargon/hostsVN-dead-hosts/actions/workflows

When I read the Github Actions [documentation](https://docs.github.com/en/rest/actions/workflows#list-repository-workflows) for example `/repos/{owner}/{repo}/actions/workflows`

But in the code in the Dead-hosts repo, use this link `https://api.github.com/repos/{repo}/actions/workflows` https://github.com/dead-hosts/infrastructure-launcher/commit/72c2786c833c0301745784ba779dc8d4a8b5c497#diff-c774146694b1184114e1ce49605d0a016bfd6a7c7bfcc041ca5d0110d0e1285cR314

Please check this out. Thank you!

**Comment by funilrys** [comment]
Hi @bigdargon ,

AFAIK this has been fixed in https://github.com/dead-hosts/infrastructure-launcher/commit/a412f1c0404fbb698d0a5daef1504f106ee1e918 which was deployed as `v2.2.6`. 

Can you please confirm that you are running the launcher `v2.2.6` ?

Cheers!

**Comment by bigdargon** [comment]
@funilrys Action cannot run https://github.com/bigdargon/hostsVN-dead-hosts/actions/runs/3607138469/jobs/6078961344#step:7:40

The most recent action added the token itself to the “info.json” file. And github automatically revoked the token https://github.com/bigdargon/hostsVN-dead-hosts/commit/3e019c67cd5bcb303146c9305c8576ff5e73c55d

**Comment by funilrys** [comment]
> @funilrys Action cannot run https://github.com/bigdargon/hostsVN-dead-hosts/actions/runs/3607138469/jobs/6078961344#step:7:40

Issue fixed through: https://github.com/dead-hosts/infrastructure-launcher/commit/44776658fcf4da1b1ae182db929ec6f3d310db90

> P/s: Maybe all your dead-host repos have been automatically revoked all tokens

Yeah, just saw that. I will have a long night ...

**Comment by funilrys** [comment]
@bigdargon Thanks for reporting and sorry for reacting so late. 
This issue should be fixed by the infrastructure-launcher `v2.2.7` which was deployed within the last 10 minutes. 

Stay safe and healthy!

**Comment by funilrys** [comment]
Closing. Feel free to reopen if something is still wrong.

**Comment by funilrys** [comment]
I discovered another issue. Reopening.

**Comment by bigdargon** [comment]
@funilrys Good job! Many thanks for fixing it!

P/s: I tried running it again and the launcher added the github token to the file “info.json”

**Comment by funilrys** [comment]
That's the issue I found.

**Comment by funilrys** [comment]
Solution tested. 
Issue fixed.
