### ISSUE TITLE
DOC: Moving away from restructured text

### ISSUE THREAD

**Issue by funilrys** [funilrys/PyFunceble#340]
For a long time, I adopted the reStructured Text format for the documentation and READMEs. 
I now believe it has been an error and we should fix that. 

I also believe that a `mkdocs` formatted documentation is more appealing for everyone: End-Users, Contributors, and Developers. Therefore, I started a new branch named [switch-to-mkdocs](https://github.com/funilrys/PyFunceble/tree/switch-to-mkdocs) which we should use for the documentation - until it gets merged into the `dev` branch. 

If you want to see, what it looks like - right now, feel free to execute the following:

```shell
git checkout switch-to-mkdocs
pip3 install --user -r requirements.docs.txt
mkdocs serve
```

You are free and welcome to comment on this issue with: 

- everything that you think is missing 
- everything that you think should be rewritten or deleted

from the READMEs or documentation. 

Cheers!

**Comment by funilrys** [comment]
- [ ] https://github.com/funilrys/PyFunceble/issues/265 should be fixed.

**Comment by spirillen** [comment]
Why not just use the gh wiki?? it is the same structure and you only need to transform month of my works once!

**Comment by funilrys** [comment]
It's also a syntax conversion a lot of things won't change.
 
I also want the documentation to be a bit more "modern" looking. Right now, we can't embed any example asciinema videos ... 😞
 
See by yourself how it looks now: 

```
git checkout switch-to-mkdocs
# activate environemt
virtualenv -p python3 venv
. venv/bin/activate
pip install -e .[full]
# Serve documentation locally.
mkdocs serve
# Open Documentation with browser.
palemoon http://127.0.0.1:8000
```

**Comment by spirillen** [comment]
Not spend a lot on this one, but ran into this error

```python
mkdocs serve
Error: MkDocs encountered an error parsing the configuration file: while constructing a Python object
cannot find module 'material.extensions.emoji' (No module named 'material.extensions')
in "$SOME_PATH/funilrys/pyfunceble/mkdocs.yml", line 48, column 20
```

**Comment by funilrys** [comment]
Nice catch. I really need to start testing everything inside a container ...

**Comment by funilrys** [comment]
Patch is on its way.

**Comment by spirillen** [comment]
A short first hand impression... :unamused: The white background is a killer. I would also recommend using a background color in the banner of the same green as your logo.

Browsing structure... not worse, but images are not loaded as you might have expected

![image](https://github.com/funilrys/PyFunceble/assets/44526987/e7aa89f6-c735-42df-b465-4201bd4f6363)

-----------------

These are only first hand impression, and I will spend some time reviewing the code in competition of [JetBrains witerside](https://www.jetbrains.com/writerside/), Yet another markdown tool that allows you to do a lot of cool stuff(config) and controlling the behavior. (Free tool), this again in competition to the [YouTrack](https://www.jetbrains.com/youtrack/)(paid version, but no diff to free version) knowledge base, which includes a [issue](https://kb.mypdns.org/issues/PF?q=project:%20PyFunceble) board that can interact with Github/Gitlab issues. And a [helpdesk](https://kb.mypdns.org/tickets) Requires login, but the submitform is HTML based and is designed to be included in any other html based page.

The preview should be available at https://kb.mypdns.org/articles/PF-A-1/PyFunceble (Once the accessibility have been solved by JetBrains support)

**Comment by spirillen** [comment]
@funilrys You can download https://github.com/spirillen/PyFunceble/tree/spirillen-writerside-v.0.1a and have a preview for the docs written with the writerside tool, the page I have been playing the most with is `lookup.html` where you can see examples of features I'm not aware of should be available to mkdocs.

Next I will fill the gh wiki for comparison https://github.com/spirillen/PyFunceble/wiki

Please let me know what you choose as I might be open for helping transferring the docs into new format

**Comment by spirillen** [comment]
This one is a issue once againt

```bash
mkdocs serve
INFO    -  DeprecationWarning: invalid escape sequence '\s'
File "/home/user/.local/lib/python3.11/site-packages/babel/dates.py", line 26, in <module>
import pytz
File "/usr/lib/python3/dist-packages/pytz/__init__.py", line 31, in
match = re.match("^#\s*version\s*([0-9a-z]*)\s*$", line)
Error: MkDocs encountered an error parsing the configuration file: while constructing a Python object
cannot find module 'material.extensions.emoji' (No module named 'material.extensions')
in "/home/user/Projects/github/foreign-affairs/pyfunceble-docs/mkdocs.yml", line 67, column 20
```
