### ISSUE TITLE
Special Rules, are they working as expected?

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#354]
As I am working on https://github.com/mitchellkrogza/phishing/pull/325/files#diff-365e9f086474958b3c3480c084f5376aa2860b057a5d1fb0cde97e0cf7d495dfR44 I come to look up for https://github.com/mitchellkrogza/Phishing.Database/issues/813 to figure out which files of @mitchellkrogza that would be the source file for VT as I could not find `pichinchamasbeneficios.pe` in my [lookup library](https://github.com/Import-External-Sources/hosts-sources).

Now I stumble on `http://0-i-fdik.000webhostapp.com/` in https://github.com/mitchellkrogza/Phishing.Database/blob/d3d9bfca3f4f524940c2a56b4af8fdeaf39eb800/active-domains.adblock#L7C12-L7C29 and went for testing it with curl/tor. The site returns HTTP code 410 as we have been adding to the rules :arrow_down: Line 80 -> 82

https://github.com/funilrys/PyFunceble/blob/f9f5c03bcf04807597161fb347b1cbfffc6f4a1a/PyFunceble/checker/availability/extras/rules.py#L80-L82

My next thought is then, are the `rules.py` script prepared for handling multiply HTTPS codes as added for `weebly`?

https://github.com/funilrys/PyFunceble/blob/f9f5c03bcf04807597161fb347b1cbfffc6f4a1a/PyFunceble/checker/availability/extras/rules.py#L111-L111

------------------

Alternative though... are the big backend of @pyfunceble test network updated to latest #pyfunceble?

**Comment by funilrys** [comment]
Interesting. I think, this relates to #358 and the fixes I introduced.

**Comment by spirillen** [comment]
We'll find out when the big phishing list is running the next test.
