### ISSUE TITLE
Unstable special rules

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#358]
As I was reporting to @mitchellkrogza in https://github.com/mitchellkrogza/Phishing.Database/issues/840 it comes to my attention that the special rules are inconsequential in the test result.

IE: these two are by visiting the domains HTTP 410, which should have been switched to down by rule, but are marked ACTIVE

```css
broomy-ropes.000webhostapp.com
brush-fire-binders.000webhostapp.com
```

![image](https://github.com/funilrys/PyFunceble/assets/44526987/7b20c74b-da80-4637-9c64-ad8acd9f1fd0)

https://github.com/funilrys/PyFunceble/blob/73e7fe550a34b65e2609c3c030db62075999d074/PyFunceble/checker/availability/extras/rules.py#L80

**Comment by funilrys** [comment]
For those who are not into Python. 

- `[1,2,3]` -> list
- `{1,2,3}` -> set
- `(1,2,3)` -> tuple

cc: @spirillen
