### ISSUE TITLE
[GUIDE] Running PyFunceble in Conda Virtual Environments

### ISSUE THREAD

**Issue by mitchellkrogza** [funilrys/PyFunceble#39]
This is my recommended way of running PyFunceble on just about any distro. 

@funilrys guided me on this some time ago and I would actually never run PyFunceble now in any other way so kudos on this goes to him. 

I in fact don't run anything to with Python now without it running inside a Conda virtual environment. Distributions like Ubuntu are especially troublesome with Python issues which are easily solved by just running Python in Conda environments.

@funilrys feel free to add to improve this in any way.

```
# -------------------------------
# Setup Conda Python Environments
# -------------------------------

# 1. Add Conda Path to .bashrc (add line below to bottom of bashrc)
export PATH="${HOME}/miniconda/bin:${PATH}"

# 2. Reload your bashrc
source .bashrc

# 3. Download Conda
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh

# 4. Install Conda
bash miniconda.sh -b -p ${HOME}/miniconda

# 5. Setup Conda
hash -r
conda config --set always_yes yes --set changeps1 no

# 6. Update Conda
conda update -q conda

# 7. Create an Environment (EXAMPLE: creating an environment called pyfuncebletesting with Python version 3.7.3)
conda create -q -n pyfuncebletesting python="3.7.3"

# 8. Activate this environment you just created
source activate pyfuncebletesting

# 9. Query Python and Pip versions inside this environment
python -VV
pip --version

# 10. Install PyFunceble in this environment (pyfuncebletesting)
pip install PyFunceble

# 11. Create the directory where you are going to run PyFunceble and output results
mkdir /home/myuser/pyfuncebletesting

# 12. Export the Working Path to PyFunceble before running PyFunceble
export PYFUNCEBLE_CONFIG_DIR=/home/myuser/pyfuncebletesting/

# 13. Run PyFunceble Testing
PyFunceble -m -p 50 -ex --plain --idna -f mylist.txt

# 14. When finished - Deactivate the environment
source deactivate pyfuncebletesting

# Your results ?? Exactly where they should be in the folder you created in step 11 - inside the /output folder

# ----------------------------
# Run tests again another day?
# ----------------------------

# 1. First Update Conda
conda update -q conda

# 2. Activate your environment
source activate pyfuncebletesting

# 3. Upgrade your environment
pip install --upgrade pip
pip install PyFunceble --upgrade

# 4. Export the Path to PyFunceble before running PyFunceble
export PYFUNCEBLE_CONFIG_DIR=/home/myuser/pyfuncebletesting/

# 5. Run PyFunceble
PyFunceble -m -p 50 -ex --plain --idna -f mylist.txt

# 6. When finished - Deactivate the environment
source deactivate pyfuncebletesting
```

**Comment by funilrys** [comment]
Nothing to add :+1: Can you make it a PR in the installation section? (As a new installation method of course)

**Comment by maravento** [comment]
conda + pyfunceble + dependencies: 
Package everything in a .deb I think it would be the best

**Comment by mitchellkrogza** [comment]
You really should try Mini(Conda) it takes all of < 1 minute to create an environment with PyFunceble and start testing. I'll never use Python on any Linux distro anymore without using Conda environments as it just works and specifying and changing python versions takes seconds to do. I have mentioned to @funilrys about creating a docker image that people can use which is probably something coming in the near future. For now just try Mini(Conda) we still don't experience any freezing on any of our many projects that use PyFunceble so despite me trying to make it freeze I have not been successful myself in replicating that issue.

**Comment by maravento** [comment]
The only problem is not freezing. I have detected others. Read 'Fix Bugs' in [issue 41](https://github.com/funilrys/PyFunceble/issues/41#issue-468380892)

**Comment by maravento** [comment]
I am trying to determine the cause of the freezing and I want to know if this program conflicts with the following packages in ubuntu 18.04.3 x64:
`python-wnck_2.32.0+dfsg-4_amd64.deb, libwnck22, python-gnomekeyring_2.32.0+dfsg-4_amd64.deb, software-properties-common, python-pip`

**Comment by mitchellkrogza** [comment]
Have you actually tried running it in Mini(Conda) and isolating it as I 
have suggested numerous times?

**Comment by mitchellkrogza** [comment]
Can rule out software-properties-common and python-pip for a start. But I promise you follow my guide I posted and in < 2 minutes you can have it running isolated in its own environment

**Comment by maravento** [comment]
I will try to execute it according to your recommendation, however it is not yet a requirement of the program and is not in the manual (it is a proposal only). That's why I haven't used it yet, and I'm still trying to determine the cause of freezing in a physical environment. But I think I found it: it consumes 100% of the CPU.
So, it doesn't matter if the program runs in a virtual or physical environment, it also consumes all hardware resources.
Therefore I believe that the solution is to create a flag to control the hardware resources assigned when running the program (CPU and RAM)

**Comment by maravento** [comment]
> pip install PyFunceble

why do you use pip if [the manual says pip3](https://pyfunceble.readthedocs.io/en/latest/update/stable.html?highlight=install)?

**Comment by mitchellkrogza** [comment]
Inside Conda you use just pip Your version of python for the environment is specified when you create it thereafter just pip is used

**Comment by mitchellkrogza** [comment]
As for your earlier question about freezing and other packages that may be conflicting. A thought just popped into my head this morning. Have you checked AppArmor is not affecting things on your system? Some of my strangest problems on Ubuntu in the past have led to AppArmor configs

**Comment by maravento** [comment]
Is there an option (flag) to use the processor cores (and balance consumption) and not use the swap so much?
![Captura de pantalla -2019-08-09 13-34-04](https://user-images.githubusercontent.com/14880802/62801133-acee0f00-baaa-11e9-91a9-8694f7712f97.png)
PD: In the image you can see how it is consuming too much a single core (of 4) and the swap (instead of RAM)

**Comment by mitchellkrogza** [comment]
Not at present.

When I run tests it does indeed consume one core for a while but then it jumps to another core and keeps doing this. I think there is probably ways in Python to balance it across the cores better. I am sure multiprocessing will be tweaked as time goes by. I am sure @funilrys can review the way multi uses cores when he next has free time.

I've however never had mine run into using swap at all.

For the majority of my tests I am keeping processes to 50-100 so as not to ever drag the machine down and allow me to happily continue doing other things.

**Comment by maravento** [comment]
Is PyFunceble only for urls/domains/host or also for IPs/CIDR?

**Comment by mitchellkrogza** [comment]
Does test IPs too

**Comment by mitchellkrogza** [comment]
Here is a simply bash script which will create the environment for you, run your test and delete the environment when done. @maravento @funilrys 

```
#!/bin/bash

# ---------------------------------------------------------------------------------------------------
# mini(Conda) PyFunceble Testing Environment
# This will create a new environment every time and delete the environment when finished testing 
# Created By: Mitchell Krog - https://github.com/mitchellkrogza
# PyFunceble Created By: Nissar Chababy - https://guthub.com/funilrys
# ---------------------------------------------------------------------------------------------------

# ---------------------------------------------------------------------------------------------------
# FIRST INSTALL Mini(Conda) - Do this manually, this script will not do it for you
#                             and only needs to be done once
# 1. Add Conda Path to .bashrc (add line below to bottom of bashrc)
#
#    export PATH="${HOME}/miniconda/bin:${PATH}"
#
# 2. Reload your bashrc
#
#    source .bashrc
#
# 3. Download Conda
#
#    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
#
# 4. Install Conda
#
#    bash miniconda.sh -b -p ${HOME}/miniconda
#
# 5. Setup Conda
#
#    hash -r
#    conda config --set always_yes yes --set changeps1 n
# ---------------------------------------------------------------------------------------------------

# --------------------------------------------------
# YOUR SETTINGS - ADJUST THINGS ONLY IN THIS BLOCK
# --------------------------------------------------
TESTFOLDER=/home/username/PyFuncebleTests/DummyDemo/
TESTINGFILE=/home/username/MyTestLists/input.lst
ENVIRONMENTNAME="dummydemo"
PYFUNCEBLEPROCESSES=50
# --------------------------------------------------
# END SETTINGS
# --------------------------------------------------

# -----------
# Setup Conda
# -----------

echo "Setting up Conda"
export PATH="${HOME}/miniconda/bin:${PATH}"

# ------------
# Update Conda
# ------------

echo "Updating Conda"
conda update -q conda

# ------------------------
# Create Conda Environment
# ------------------------

conda create -q -n ${ENVIRONMENTNAME} python="3.7.3"

# --------------------
# Activate Environment
# --------------------

echo "Activating Test Environment"
source activate ${ENVIRONMENTNAME}

# --------------------------------------
# Install / Upgrade Requirements and Pip 
# --------------------------------------

echo "Upgrading Environment"

pip install --upgrade pip
pip install PyFunceble --upgrade
pip install domain2idna --upgrade
pip install ultimate-hosts-blacklist-whitelist --upgrade

# --------------------
# Show Version Numbers
# --------------------

echo "------------"
echo "VERSION INFO"
echo "------------"
python -VV
pip --version
domain2idna -v
ultimate-hosts-blacklist-whitelist -v
PyFunceble -v
echo "------------"

# ----------------
# Setup PyFunceble
# ----------------

cd ${TESTFOLDER}
export PYFUNCEBLE_CONFIG_DIR=${TESTFOLDER}

# --------------------
# Run PyFunceble Tests
# --------------------

# NOTE: Because of the MySQL / Mariabd database selection the first time you run this you need to manually answer the questions for the Database Connection
# PyFunceble will then create the .pyfunceble-env file containing the database connection information and won't ask again when you run this a second time
# Set your database up using PhpMyAdmin 

echo "Starting PyFunceble Tests"

PyFunceble --database-type mysql --idna -ex --multiprocess --processes ${PYFUNCEBLEPROCESSES} --plain -f ${TESTINGFILE}

# This Command Line below is a Simple One Line Test of github.com - useful for testing this script without running a full test
# Disable above line and enable this line below if you want to enable this quick test
#PyFunceble --idna -ex --multiprocess --processes ${PYFUNCEBLEPROCESSES} --plain -d github.com


# --------------------
# Deactive Environment
# --------------------

echo "Deactivating Test Environment"

conda deactivate

# ------------------
# Delete Environment
# ------------------
# Does not Delete any of your Data only the Environment
# This is NOT really necessary but can be used if you want to create a new environment every time

echo "Deleting Test Environment"

conda remove --name ${ENVIRONMENTNAME} --all

# -----------------------
# List Conda Environments
# -----------------------

echo "Listing Conda Environments"

conda env list

# ----------------------
# Exit With Error Number
# ----------------------

exit ${?}

```

**Comment by maravento** [comment]
great¡¡

**Comment by maravento** [comment]
great!!. A couple of questions:
1. I do not understand the purpose of this line:
```
pip install ultimate-hosts-blacklist-whitelist --upgrade
```
PD: If you had already discontinued Central Repo, why re-filter the result of PyFuncyble?

2. Does this script require privileges? (If it is mixed, which commands need sudo and which do not)

**Comment by mitchellkrogza** [comment]
Sorry you can comment out the blacklist-whitelist installation I use that  in my scripts 

No sudo at all this is created as my script.sh in your own user folder everything runs as your user

We centralized whitelisting which is now much more advanced if you go look at the project

**Comment by mitchellkrogza** [comment]
Until one day when a containerised version is produced this simple bash just about does that and perfectly too

**Comment by maravento** [comment]
I have created a project that helps reduce the size of the list to be processed by PyFunceable
If any domain ends in something that is in the list invalidtlds.txt is deleted (because it is not a valid domain). Modify the command according to the format of your list:
wget https://raw.githubusercontent.com/maravento/tlds/master/invalidtlds.txt
grep -vi -f <(sed 's:^\(.*\)$:\\\1\$:' invalidtlds.txt) source_list | sort -u > new_list
The process can also be done in reverse. That is, if a domain does not have a valid tlds (which is in the tlds.txt list) it will be deleted:
wget https://raw.githubusercontent.com/maravento/tlds/master/tlds.txt
I hope it can serve you, as it has served me.

**Comment by mitchellkrogza** [comment]
What is wrong with the environment name? It's merely a placeholder which is meant to be changed. dummydemo is not aimed nor intended to be funny or insulting. By all means rewrite it however you want it was as I stated ... An example, a basic guide and is to be adapted to be used in your own environments 🤔

**Comment by mitchellkrogza** [comment]
I spend time writing an EXAMPLE for you can you can't even give a simple thank you for my time and effort merely pointing at what you perceive as bugs. I never said I was providing a 100% piece of software that is set and forget. You asked for an example script and I provided such.

**Comment by spirillen** [comment]
Hey @mitchellkrogza and @funilrys I think you have closed this a bit prematurely

As @funilrys suggested this in the docs in https://github.com/funilrys/PyFunceble/issues/39#issuecomment-511526067 but the docs still not showing this very very very cool approach 
https://pyfunceble.readthedocs.io/en/dev/search.html?q=conda&check_keywords=yes&area=default#

which have slipped my attention until now, I think a it should have a pin, until it is covered in the docs.

I'm going to test it for sure :smiley:
