### ISSUE TITLE
BUG | closest config folder not picked up

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#397]
### What is the problem you are experiencing?

I have a local `(./)?PyFunceble` in same dir as I execute PyFunceble which contains standard config files. In the past this was costume that Pyfunceble first looked in the project|current folder before searching on https://docs.pyfunceble.com/use/configuration/location.html#linux-macos for what I just experienced and can read in the current documentation, this seem to have been turned upside down.

### How can we reproduce the problem?

Please see above

### Do you have a screenshot?

N/A

### What did you expect to happen?

I expect the searching for config files starts in the current fold `$PWD`, then `~/.PyFunceble`, then `~/.config/PyFunceble` everything else makes it difficult as you are forced to use the `--config-dir` and/or `--config-file` options

### Is there a workaround?

use the `--config-dir` and/or `--config-file` options to control the config dir/file

### How did you configure PyFunceble?

Not relevant

### Which Operating System did you use?

Ubuntu 24.04 LTS, Ubuntu 22.04 LTS, Unix or *BSD like OS

### Which PyFunceble Version did you use?

4.3.0a5.dev

### Additional context

I would like to add...

**Comment by funilrys** [comment]
In the past PyFunceble didn't look at the current folder. It never did. 

Only when you clone the project and work from that folder.

If you want that behavior, you shall ensure that the following files and directories exists: https://github.com/funilrys/PyFunceble/blob/296a613f2e4149f8e790cd92ef4b964694edcac6/PyFunceble/utils/version.py#L246-L259 

I'm not sure I want to change this @spirillen, this will create a lot of files for many.

**Comment by spirillen** [comment]
Super, lets keep it with `--config-dir` and/or `--config-file`

BTW, you should add this to the docs...

https://github.com/funilrys/PyFunceble/blob/296a613f2e4149f8e790cd92ef4b964694edcac6/PyFunceble/utils/version.py#L246-L259
