### ISSUE TITLE
The program freezes every 2 - 5 hours

### ISSUE THREAD

**Issue by maravento** [funilrys/PyFunceble#40]
## Bug description
The program freezes every 2 or 3 hours.

**Data Sheet:**
Hardware / Software: Intel Xeon 2 core, 16 GB RAM, HDD 2 TB, Ubuntu 18.04.2 LTS x64
python -V: 2.7.15+
pip3 --version: pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
pip --version: pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
run: PyFunceble -m -p 150 -f list
Installation method: `pip3 install -r requirements.txt && pip3 install PyFunceble`
File to be processed: Unix/Linux List format (UTF-8 .txt) with 5 M of lines of domains

Measures taken: CTRL + C and run it again
The -p parameter has been changed (-p 200, -p 150, -p 100, -p 50 and -p has been removed), and the result is the same. I have tested on other computers with superior hardware and the result is the same

PD: What is the recommended installation method (error-proof)?
Problem with uninstall with this method:
https://github.com/funilrys/PyFunceble/issues/38#issuecomment-511462392

**Comment by maravento** [comment]
Solved HERE
https://github.com/funilrys/PyFunceble/issues/38#issuecomment-511527582

**Comment by mitchellkrogza** [comment]
Did you find your cause of freezing?

**Comment by maravento** [comment]
Hello @mitchellkrogza. First of all thanks for the help, as well as @funilrys.
The program is good (at least it is faster than the bash it used). I have not yet found the cause of the freeze, but I followed your advice and divided the list into several parts in the file (head -c 10MB file). This does not prevent freezing, but at least each part ends faster. The alternative of @funilrys does not prevent freezing either.
If at least this program had a debug mode or logs it would be easier to determine the cause.
I still think that the most likely cause is:
1. Poor installation
2. Some conflict
This could be avoided if the installation method is changed by AppImage, Snap, Flatpak or some other type of packaging that this program and its dependencies can run in an isolated environment (such as Conda, Hipervisor VM, etc).
But with the current installation system it is necessary to install environment + program + dependencies, and this can break the system or cause instability and is not reliable.

**Comment by mitchellkrogza** [comment]
I hope @funilrys can give you a flag to create a debug log. Highly suggest you try my Mini(Conda) method which ensures it will run on Python 3.7.3 without any external problems. I use Conda exclusively on my Ubuntu servers as it completely obliterated any funny Python errors which Ubuntu is renowned for.
