### ISSUE TITLE
BUG | 4.2.27 stable is impossible to install in Cygwin due to the "Cryptography" dependency relying on Rust

### ISSUE THREAD

**Issue by DandelionSprout** [funilrys/PyFunceble#401]
### What is the problem you are experiencing?

Trying to run `pip3 install PyFunceble==4.2.27` in Cygwin fails, due to failing to install the `cryptography` package.

Then, trying to do `pip install cryptography==43.0.3` to narrow down possible causes, it fails due to `error: can't find Rust compiler`.

Running the installer for Windows at https://www.rust-lang.org/tools/install → "Download rustup-init.exe (64-bit)" does not seem to have any impact within Cygwin.

There are no Rust packages in pip nor in Cygwin's setup tool, and none that I can find with Google searches either that would be intended with Cygwin in mind. Therefore, I can only presume that the `cryptography` dependency must be removed entirely from https://github.com/funilrys/PyFunceble/blob/dev/requirements.win.txt

### How can we reproduce the problem?

To reproduce the problem:

1. Have an existing PyFunceble 4.2.0 installation that had been installed from within Cygwin.
2. Try to update the existing installation with `pip3 install PyFunceble==4.2.27`.
3. See that installation of PyFunceble itself, the `cryptography` dependencies, and a whole lot of `cryptography`'s own dependencies fail due to failing to build wheels, as Cygwin claims `error: can't find Rust compiler`
4. Try to install the dependencies and sub-dependencies individually and seemingly all of them will fail.

### Do you have a screenshot?

<details><summary>Screenshot 1 (Trying to update PyFunceble)</summary>

![image](https://github.com/user-attachments/assets/eed028ab-c1b6-4fa6-bccb-5f26eaf8c9e3)
</details>

<details><summary>Screenshot 2 (Trying to install `cryptography`)</summary>

![image](https://github.com/user-attachments/assets/8906c3df-23a1-4acf-8c39-e26eb517cb17)
</details>

<details><summary>Screenshot 3 (Attempted to use Rust's official download method intended specifically for "Windows Subsystem for Linux", just in case.)</summary>

![image](https://github.com/user-attachments/assets/59245775-1f33-4629-914e-4db7305b00e9)
</details>

<details><summary>Screenshot 4 (I was able to install a package called `setuptools-rust`, but it seemingly didn't help on the missing Rust compiler errors.)</summary>

![image](https://github.com/user-attachments/assets/fea1798e-5d31-42a3-a616-399ba2847751)
</details>

<details><summary>Screenshot 5 (Tried to install the `maturin` package that I saw had something to do with Rust of some sort; soon afterwards I gave up)</summary>

![image](https://github.com/user-attachments/assets/5e7ff610-8caf-4199-ab68-5255527bc298)
</details>

### What did you expect to happen?

That the update to 4.2.27 went successfully.

### Is there a workaround?

PowerShell 7.x with Python 3.10 had no sweat installing 4.2.27 and with running it, though I'd have to find a way to properly configure the colour schemes of the PowerShell version (Programs running in PowerShell usually needs special config changes to display more colours than just white on black), which seems to operate mostly independently from the Cygwin installation, except apparently a semi-conflict on whether to remove or re-add the `collection` value string.

The existing 4.2.0 installation in Cygwin also seems to still work if needed… I think. Hard to tell 100%.

### How did you configure PyFunceble?

Apparently the `.PyFunceble.overwrite.yaml` files on my PC are completely empty.

### Which Operating System did you use?

Windows 11

### Which Python Version did you use?

3.9

### Which PyFunceble Version did you use?

Exact output: "The 'collection.preferred_status_origin' key is missing from your configuration file. Are we authorized to merge it from upstream ? [y/n]"

### Additional context

As with everything in my entire life that have involved command line terminals, despite me having a reasonably decent knowledge of commands, run-parameters (e.g. `--help`), and shortcuts (e.g. `cd`), my tests and the tests' results ended up rather chaotic and blurry, so the exact order I did things in got a bit chaotic and hard to remember properly.

On the occasions where I've tried to set up WSL with Ubuntu stable builds, I usually managed to completely break the Ubuntu OS installs beyond recognition within 48 hours, so replacing Cygwin with WSL is not an option.

**Comment by funilrys** [comment]
Hey @DandelionSprout, 

nice to hear from you. I hope you are doing well. 
I'll downgrade cryptography under windows, ASAP. 

Thank you for taking the time to report the issue. I'm on the road, but will look into this ASAP.

**Comment by funilrys** [comment]
I went another way. I dropped cryptography with the commit above.

**Comment by funilrys** [comment]
pyfunceble-dev is not mature enough to be released as a stable version. Therefore, I'll cherry-pick and deploy a new stable version without any cryptography dependency - ASAP.

**Comment by funilrys** [comment]
Ongoing deployment: https://github.com/funilrys/PyFunceble/actions/runs/11692734609

**Comment by funilrys** [comment]
Version deployed. 
CF: https://pypi.org/project/PyFunceble/4.2.28/

Closing. Feel free to reach out if there are still any issues.
