### ISSUE TITLE
BUG | Whois date in past marked ACTIVE

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#403]
### What is the problem you are experiencing?

Found a couple of cases where the expiring date are in the past, yet, the records are marked active based on whois test

```python
Subject                                                                                              Status      Source     Expiration Date   HTTP Code  Checker
---------------------------------------------------------------------------------------------------- ----------- ---------- ----------------- ---------- -------------
123lnk.xyz                                                                                           ACTIVE      WHOIS      01-oct-2024       Unknown    AVAILABILITY
22pixx.xyz                                                                                           ACTIVE      WHOIS      13-jun-2022       301        AVAILABILITY
```

```
drill 123lnk.xyz -T
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 65418
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
;; QUESTION SECTION:
;; -T.  IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:
.       3334    IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2024111601 1800 900 604800 86400

;; ADDITIONAL SECTION:

;; Query time: 20 msec
```

```
drill 22pixx.xyz -T
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 17018
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
;; QUESTION SECTION:
;; -T.  IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:
.       3334    IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2024111601 1800 900 604800 86400

;; ADDITIONAL SECTION:

;; Query time: 0 msec
```

### How can we reproduce the problem?

To reproduce the problem:

test a expired WHOIS domain

### Do you have a screenshot?

<details><summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/4b898552-7422-45df-a9cb-85d5b10ccc74)

</details>

### What did you expect to happen?

I don't know.. 😭 

### How did you configure PyFunceble?

```yaml
.PyFunceble.overwrite.yaml

# Your configuration here
```

### Which Operating System did you use?

Unix or *BSD like OS

### Which Python Version did you use?

3.11

### Which PyFunceble Version did you use?

4.3.0a9.dev

### Additional context

I would like to add...

**Comment by spirillen** [comment]
Yet another one

![image](https://github.com/user-attachments/assets/41b44881-258c-4098-bc12-12fcefd21822)

**Comment by spirillen** [comment]
![image](https://github.com/user-attachments/assets/d0a5c375-a5e6-4ac7-8ca4-01c57219fa02)

**Comment by spirillen** [comment]
This one is outdated, not updated.

![image](https://github.com/user-attachments/assets/413d252b-b7ce-4aac-be95-b74b2e3ac668)


![image](https://github.com/user-attachments/assets/47779636-c974-4748-a6e2-443108252803)

**Comment by spirillen** [comment]
Here is even are more spookier one, thought Halloween was some American commercialized thing...

Let's play with `100gaoxx.com` and the whois options. First we get the actual whois info

```
Domain Name: 100GAOXX.COM
Registry Domain ID: 2507193664_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.namesilo.com
Registrar URL: http://www.namesilo.com
Updated Date: 2024-10-10T02:42:29Z
Creation Date: 2020-03-25T05:03:46Z
Registry Expiry Date: 2025-03-25T05:03:46Z
```

Now lets use PyFunceble to make some WHOIS tests

```bash
pyfunceble -d 100gaoxx.com

Subject                                                                                            Status      Source
---------------------------------------------------------------------------------------------------- ----------- ----------
100gaoxx.com                                                                                       ACTIVE      DNSLOOKUP
```

```bash
pyfunceble -d 100gaoxx.com --whois-lookup

Subject                                                                                            Status      Source
---------------------------------------------------------------------------------------------------- ----------- ----------
100gaoxx.com                                                                                       ACTIVE      DNSLOOKUP
```

> [!NOTE]  
> We asked for the WHOIS info, got replied with DNSLOOKUP!!!


```bash
pyfunceble -d 100gaoxx.com --whois-lookup-only

Subject                                                                                            Status      Source
---------------------------------------------------------------------------------------------------- ----------- ----------
100gaoxx.com                                                                                       INACTIVE    STDLOOKUP
```

Only one answers was right.... and it had nothing to do with WHOIS

**Comment by funilrys** [comment]
I see where you come from @spirillen, but if the whois entity is not making their part of the job, I'm not sure I want to do that either.

Since the start of PyFunceble, we delegate that part of the work to WHOIS entities. Even in funceble we didn't do that. 
And even though, it's a hard job, sometimes some companies or hoster (probably) have contracts in place with NICs or other WHOIS entities, so that they have a toleration of a few months (sometimes years!!!). Meaning that even if the WHOIS record is "expired", everything will keep running.

In the past, I even saw some ICANN domains that had some WHOIS record who were in the past - and stayed like that for years. That was the logic (back then with funceble) with that design decision.  

> We asked for the WHOIS info, got replied with DNSLOOKUP!!!
> pyfunceble -d 100gaoxx.com --whois-lookup-only

That's not DNSLOOKUP but `STDLOOKUP` which is the standard response when the system went through all checks without success. As you restrict with ` --whois-lookup-only`, it tried to find something else, and couldn't find anything. 
 
That look like you hit the rate limit.
