### ISSUE TITLE
PyFunceble needs some improvements in its adblocker syntax support

### ISSUE THREAD

**Issue by DandelionSprout** [funilrys/PyFunceble#42]
## Bug description

PyFunceble 2.2.0 does not seem to me to parse:
* Domains that precede `#` in hiding rules, e.g. `example.org##.example`.
* Entries formatted like `||example.org$document`.
* An unknown amount of other uBO-specific or AdGuard-specific blocking-rule syntaxes, e.g. `$all` (as seen in https://github.com/uBlockOrigin/uAssets/blob/master/filters/badware.txt#L334).

## Modifications under `.PyFunceble.yaml`

None that I'm aware of.

## Reproduction

1. Run `PyFunceble -ad -f https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt`
2. See that only 19 of the ~180 domains in that list get processed by PyFunceble.

## Expected behavior**

See that ~180 domains get processed by PyFunceble.

## Screenshots

![image](https://user-images.githubusercontent.com/22780683/63230762-78e4bd80-c211-11e9-981c-9143be1e7d7a.png)

## Versions

**OS:** Windows 10 May 2019 Update
**Python Version:** 3.6.8, according to Cygwin
**PyFunceble Version:** 2.2.0

## Additional context

`||example.org$document` is a uBlock Origin-created syntax that remains unsupported in ABP-likes or in AdGuard, and it's considered a very important syntax to use in uBO-specific lists, especially anti-malware ones.

**Comment by funilrys** [comment]
Hi @DandelionSprout and thanks for your feedback.

I'm working on the patch for this issue but first, why would you want for example 
```
facebook.com##.search
``` 
to be in a hosts list for example? 

I'm asking because according to the [Wiki](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#static-extended-filtering):

> The most common type of static extended filters are cosmetic filters, also known as "element hiding filters" in Adblock Plus.

I never took them into consideration because they are "also known as "element hiding filters" in Adblock Plus."... But let's discuss that! What's your opinion?

**Comment by DandelionSprout** [comment]
Essentially, if PyFunceble was able to interpret `facebook.com##.search` as a request to check the availability of `facebook.com`, then I'd be able to see if my (quite often) adblocker-syntaxed list would need to contain any entries for `facebook.com` anymore.

**Comment by funilrys** [comment]
Great to know @DandelionSprout. I didn't think that people will use it like that :thinking: But that's an interesting point.

Until I free it from the aggressive logic, you can access what you want (`facebook.com##.search`) with the `--agressive` switch from the dev branch/version :+1: 

Thanks again for the feedback!
