### ISSUE TITLE
Is it possible to only display "INACTIVE" domains?

### ISSUE THREAD

**Issue by DandelionSprout** [funilrys/PyFunceble#43]
**Is your feature request related to a problem? Please describe.**

Since my use of PyFunceble (as of at the time of writing) relies on me manually editing out domains from my lists that PyFunceble have declared to be inactive, I wonder if there's a way to make the terminal window only display red/inactive domains that it has parsed?

That way I won't have to scroll quite as much through walls of green/active domains as I've had to do so far, and that I won't have to stretch the terminal window to 1400~1500px height in order to spot all the inactive domains.

**Describe the solution you'd like**

A way to only have the invalid domains that PyFunceble have parsed show up in the terminal window, or some quick advice on how to turn on (or use a modifier to achieve) such a function if it already exists.

**Describe alternatives you've considered**

If the above is not possible to implement, then I suppose it could be possible to add an `adblock` subfolder to the `output` foldertree or something like that, or perhaps that I'd look into `PyFunceble\output\splited\invalid` much more often, but it'd feel like a detour in my eyes since it'd not be in PyFunceble's de-facto UI itself.

**Additional context**

None that I'm aware of.

**Comment by mitchellkrogza** [comment]
I'll try help you here @DandelionSprout 
Have you looked in your output folder instead of scrolling through what is in terminal?
Look in output/domains/INACTIVE/list there is the list of all INACTIVE domains as of your last test.

A very simply awk will give you a clean list in seconds.

`awk 'NR==FNR{a[$0];next} !($0 in a)' inactive.txt active.txt > clean-list.txt`

**Comment by DandelionSprout** [comment]
I appreciate the idea, but in my case the output usually seems to end up in `PyFunceble\output\splited` (for instance with [this list](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/DandelionSproutsNorskeFiltreDomains.txt)), which uses a different filetree than the `domains` folder.

Running `awk 'NR==FNR{a[$0];next} !($0 in a)' INACTIVE full-list.txt > clean-list.txt` in Cygwin causes an error (in which it can't find `full-list.txt`), while `awk 'NR==FNR{a[$0];next} !($0 in a)' INACTIVE > clean-list.txt` generates an empty file.

Likewise, using some old output that I still had in `PyFunceble\output\hosts\INACTIVE\hosts`, `awk 'NR==FNR{a[$0];next} !($0 in a)' hosts full-list.txt > clean-list.txt` causes an error, and `awk 'NR==FNR{a[$0];next} !($0 in a)' hosts > clean-list.txt` generates an empty file.

**Comment by mitchellkrogza** [comment]
full-list.txt is just an example file name .... that must be your full list from "which" you want to strip out inactive domains.

Your file formats must also match, so your hosts file you used in example B won't match inactive because a hosts file is not one domain per line it has extra content on each line.

So you are trying to compare

`domain.com` in one file with `0.0.0.0 domain.com` or `127.0.0.1 domain.com` which will not match and of course give you an empty clean.list

**Comment by funilrys** [comment]
Hi @DandelionSprout, 

Sorry for the delay and thanks for your feedback.

My solution will be to use the `--simple|-s` argument of PyFunceble along with a `grep` or `awk`.

Here are some examples 

**(Warning the `INACTIVE`in the following are not accurate as I ran the command in a machine behind @pi-hole).**

```shell
$ PyFunceble -f .travis/lists/simple -s | awk '{if(NF > 0 && $2 == "INVALID" || $2 == "INACTIVE") print $1 " " $2}'
247?realmedia.com INVALID
adblade.com,popup INVALID
adtrackone.eu$document INVALID
allosexe-.myblox.fr INACTIVE
alyssa-.ifrance.com INACTIVE
cdnfile.xyz INACTIVE
durl=px.moatads.com INVALID
free‐celebrity‐tube.com INVALID
hans.pr0gramm.com INACTIVE
host.d-ns.ga INACTIVE
hurensohn.pr0gramm.com INACTIVE
javakiba.org* INVALID
mailto:info@mypornbible.com INVALID
mangas-porno-.has.it INACTIVE
moherland.pl, INVALID
m.pr0gramm.com INACTIVE
public‐sluts.net INVALID
px.moatads.com,z.moatads.com INVALID
securepubads.g.doubleclick.net INACTIVE
sexchat-.startspin.nl INACTIVE
st.kjli.fi INACTIVE
telemetry.appex.bing.net:443 INVALID
web.die-news.pw INACTIVE
websitealive[0-9].com INVALID
www.free‐celebrity‐tube.com INVALID
www.just-anchor.com? INVALID
www.public‐sluts.net INVALID
INACTIVE    18%          12          
INVALID     22%          15
```

```shell
$ PyFunceble -f .travis/lists/simple -s -dbr -1 | grep -E "INACTIVE|INVALID"
247?realmedia.com INVALID
adblade.com,popup INVALID
adtrackone.eu$document INVALID
allosexe-.myblox.fr INACTIVE
alyssa-.ifrance.com INACTIVE
cdnfile.xyz INACTIVE
durl=px.moatads.com INVALID
free‐celebrity‐tube.com INVALID
hans.pr0gramm.com INACTIVE
host.d-ns.ga INACTIVE
hurensohn.pr0gramm.com INACTIVE
javakiba.org* INVALID
mailto:info@mypornbible.com INVALID
mangas-porno-.has.it INACTIVE
moherland.pl, INVALID
m.pr0gramm.com INACTIVE
public‐sluts.net INVALID
px.moatads.com,z.moatads.com INVALID
securepubads.g.doubleclick.net INACTIVE
sexchat-.startspin.nl INACTIVE
st.kjli.fi INACTIVE
telemetry.appex.bing.net:443 INVALID
web.die-news.pw INACTIVE
websitealive[0-9].com INVALID
www.free‐celebrity‐tube.com INVALID
www.just-anchor.com? INVALID
www.public‐sluts.net INVALID
INACTIVE    18%          12          
INVALID     22%          15
```


However, I like the idea of "displaying only `INACTIVE` or `INVALID`. I might implement that in the future. But not yet. If someone wants to write the PR, I'll be glad to review and merge 😊

Thanks again for your feedback.

Cheers,
Nissar

**Comment by funilrys** [comment]
This has been there for a long time. Let's add it into 4.0.0 😄

**Comment by funilrys** [comment]
@DandelionSprout @spirillen  Please test this and reopen if it's not fixed.
 
Closing.

**Comment by spirillen** [comment]
This test will be a part of the same test for #115 + #147

**Comment by spirillen** [comment]
![image](https://user-images.githubusercontent.com/44526987/103134589-88e89900-46b2-11eb-9a28-53113dc42c6c.png)

![image](https://user-images.githubusercontent.com/44526987/103134745-a10ce800-46b3-11eb-838b-217954bdf556.png)


I believe it should be possible to choose more than one output to display <https://pyfunceble.readthedocs.io/en/4.0.0-dev/usage/index.html#display-status>

![image](https://user-images.githubusercontent.com/44526987/103134778-fd700780-46b3-11eb-8da7-a81caab5d195.png)

**Comment by spirillen** [comment]
Success with the note of displaying more than one optional limitation

<https://travis-ci.com/github/dns-test/PyFunceble-Sandboxed/builds/210571650>

<https://travis-ci.com/github/dns-test/PyFunceble-Sandboxed/builds/210568814>
