### ISSUE TITLE
Have PyFunceble prepare Travis-CI for committing

### ISSUE THREAD

**Issue by mitchellkrogza** [funilrys/PyFunceble#44]
Without us having to do this in our repo scripts as below, it would be great if PyFunceble could always prep itself for committing back to the repo by just pulling the environment variables and running this sequence before it runs `--cmd` or `--cmd-before-end`

```
    git remote rm origin
    git remote add origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
    git config --global user.email "${GIT_EMAIL}"
    git config --global user.name "${GIT_NAME}"
    git config --global push.default simple
    git checkout "${GIT_BRANCH}"
```

**Comment by funilrys** [comment]
Feature introduced with https://github.com/funilrys/PyFunceble/commit/fb6b0645a9251616ea600ae3560cacded1252096.

**P.S: Please DO NOT close this issue manually. This issue is going to be closed automatically once https://github.com/funilrys/PyFunceble/commit/fb6b0645a9251616ea600ae3560cacded1252096 will be merged to master.**

**Comment by spirillen** [comment]
I also have a thought on this on...

There is a switch for `--travis-branch` how about a `--travis-final-commit-branch` ?

then you can have `in process` branch and your `master` branch were any new submission to master would be submitted to any running sequence.... and a temp processed source.list wouldn't by error be used as a finished work...

**Comment by funilrys** [comment]
@spirillen, @mitchellkrogza  a similar idea has been implemented with https://github.com/funilrys/PyFunceble/commit/31eff2cab95fb46590fe6fc46413e5dfada42460. 

I could not test it directly so I will probably edit that patch but consider such logic implemented.

It will be deployed in the coming 30 minutes.

Cheers,
Nissar

**Comment by spirillen** [comment]
> @spirillen, @mitchellkrogza a similar idea has been implemented with [31eff2c](https://github.com/funilrys/PyFunceble/commit/31eff2cab95fb46590fe6fc46413e5dfada42460).
> 
> I could not test it directly so I will probably edit that patch but consider such logic implemented.
> 
> It will be deployed in the coming 30 minutes.
> 
> Cheers,
> Nissar

You just abuse the [Dead-Domains](https://github.com/spirillen/Dead-Domains) repo :smiley: it is there for the same reason :+1:

**Comment by funilrys** [comment]
Thanks to that I tested and fixed that commit :wink:

**Comment by spirillen** [comment]
Reopen for v4 Github Actions

examples for two workaround:
  - <https://github.com/mypdns/porn-records/blob/43042284215833a2b982ea0f755f196618932c3a/.github/workflows/main.yml#L79-L90>
  - <https://github.com/mypdns/porn-records/blob/43042284215833a2b982ea0f755f196618932c3a/.github/workflows/main.yml#L63-L65>
  - <https://github.com/PyFunceble/ci_test/blob/3ffb3f0950234fa3d5349520a6f12afb4425eaf0/.github/workflows/scheduler.yml#L26-L46>
