### ISSUE TITLE
public-suffix.json

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#47]
I'm trying to understand the 'public-suffix.json'.

What I can guess from https://pyfunceble.readthedocs.io/en/latest/code/publicsuffix.html it is a kind of whitelist, is that corect?

```bash
if [ a == yes ]
then
  How do I omit it?
else
  if [ a == no ]
  why are domains like blogspot.tld listed there (as those are some I really don't like to be whitelisted in my project...)
  fi
fi
```

**Comment by funilrys** [comment]
Hi @spirillen,

We only use the `public-suffix.json` as a comparison tool which helps us determine if a (public) domain has a valid syntax and is a subdomain. If you remember, we recently talked (elsewhere) about sorting for example. 

To quote [myself](https://github.com/funilrys/PyFunceble/issues/10#issuecomment-450384214):

> But, if `ccc.com` is registered into the [PSL](https://github.com/publicsuffix/list) which we parsed into [`public-suffix.json`](https://github.com/funilrys/PyFunceble/blob/master/public-suffix.json) we sort in the following order.
>
> * `ccc`.`com`
> * `aaa`
> * `bbb`
> 

Of course, it was explained for the sorting routine. But we use it to mainly determine if a domain is a subdomain. Why that? Well, we don't request a WHOIS record for the subdomain.

Let me know if it's not clear.

Cheers,
Nissar

**Comment by spirillen** [comment]
That is a top teen answer :star2:   And yes I do remember the talk on sorting :)

Allow me to add a quete from the PSL link you provided for other readers

> A "public suffix" is one under which Internet users can (or historically could) directly register names. Some examples of public suffixes are .com, .co.uk and pvt.k12.ma.us. The Public Suffix List is a list of all known public suffixes.

And it all make a very good sense to me now, ask fir the reply
