### ISSUE TITLE
Onion addresses are not an invalid URL

### ISSUE THREAD

**Issue by ZeroDot1** [funilrys/PyFunceble#51]
## Bug description
When checking the URLs in a list, .onion addresses are always recognized as invalid. 

## Expected behavior**
I expect that .onion addresses will simply be skipped.

Example of a .onion address from my list.
```bash
# File generated by PyFunceble (v2.17.9.dev) / https://github.com/funilrys/PyFunceble
# Date of generation: Sun 03 Nov 23:11:59 CET 2019 

xrqwig7erykgll4z.onion
```

# System
- Kernel: 5.3.8-arch1-1 x86_64
- Desktop: Cinnamon 4.2.4 
- Distro: Arch Linux
- Shell: bash 5.0.11

**Comment by ZeroDot1** [comment]
I recommend to solve the problem by adding an additional option to skip .onion addresses.

e.g. a switch `--noonion`

**Comment by dnmTX** [comment]
@ZeroDot1 the mentioned domain didn't respond on basic nslookup therefore is automatically rendered invalid(no further checks will be performed). I'm kind of confused here,how is it considered active if any DNS resolver can not find any info about it?

**Comment by funilrys** [comment]
Feature introduced with https://github.com/funilrys/PyFunceble/commit/60d9950fe8c4d2ded57d715b28b4f98609db1316.

https://github.com/funilrys/PyFunceble/commit/60d9950fe8c4d2ded57d715b28b4f98609db1316 is into the `restructuration` branch. It is an isolated branch which contains the base behind the future PyFunceble 3.0. 
This means that this feature will be available for testing/usage in the `dev` branch in the coming days. But only in the `master` branch in the coming weeks. 

**P.S: Help us, DO NOT close this issue manually.**

**Comment by spirillen** [comment]
Could be fixed with conditional proxy <https://github.com/funilrys/PyFunceble/issues/132>
