### ISSUE TITLE
Add the possibility to use DoT

### ISSUE THREAD

**Issue by ZeroDot1** [funilrys/PyFunceble#53]
**Is your feature request related to a problem? Please describe.**
It is not possible to use DoT.

**Describe the solution you'd like**
I would like to use DoT to protect my DNS requests.
Using the DNS of the host system with DoT often leads to problems because some applications simply don't work anymore.

This is why DoT should be implemented in PyFunceble.
I recommend to provide a way to configure the DoT settings in the configuration file, so that you don't have to enter everything manually every time you need to use it.

https://developers.cloudflare.com/1.1.1.1/dns-over-tls/

**Additional context**
It should be possible to specify the URL and server for DoT.

Example:

```bash
#Configfile

DoTurl = Your_ID.dns.nextdns.io
Server 1= ip.ip.ip.ip
Server 2= ip.ip.ip.ip
Server 3= ipv6:ipv6:1pv6:ipv6
Server 4= ipv6:ipv6:1pv6:ipv6
```

**Comment by funilrys** [comment]
@ZeroDot1, if you get a bit of a time for us, can you test 4.0.0 ? It implements this.

Thanks in advance.

**Comment by spirillen** [comment]
What is the syntax he should be using??

**Comment by funilrys** [comment]
@spirillen there is 1 new argument:

```
--dns-protocol {UDP,TCP,HTTPS,TLS}
                        Set the protocol to use for the DNS queries. 
                        Configured value: 'UDP'
```

Setting it to `TLS` and giving your list of servers to the following argument (not changed) should be sufficient.

```
--dns DNS__SERVER [DNS__SERVER ...]
                        Set one or more DNS server(s) to use during testing. Separated by spaces.
                        
                        To specify a port number for the DNS server you append it as :port [ip:port].
                        
                        If no port is specified, the default DNS port (53) is used. 
                        Configured value: None
```

**Comment by funilrys** [comment]
Also forgot: For those playing with the configuration file (`.PyFunceble.yaml`, it is also possible through the `dns -> server` and `dns -> protocol` indexes.

**Comment by spirillen** [comment]
I'm sure looking forward to the new doc branch to start working on it :smiley: :scroll: :page_with_curl:

**Comment by funilrys** [comment]
Also documented.

Closing. Feel free to test and reopen if not fixed or if necessary.
