### ISSUE TITLE
WHOIS servers should be resolved by the custom DNS resolver!

### ISSUE THREAD

**Issue by funilrys** [funilrys/PyFunceble#55]
Indeed, actually (PyFunceble-dev) the whois server for example `example.com` is resolved by the systemwide resolver and not the custom one.

**Comment by ZeroDot1** [comment]
Yes, I can confirm the problem.

**Comment by funilrys** [comment]
Fixed with https://github.com/funilrys/PyFunceble/commit/fd5dc7bce98464cdef26379d04f443d925cf165b.

**Comment by ZeroDot1** [comment]
I'm ready to test a new DEV version tomorrow.
