### ISSUE TITLE
-uf all invalid, buts ok as local file

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#59]
## Bug description
If you use the Pyf with `-uf 'url'` all records is marked as invalid, but if you download the same file and then test it with the `-f`thinks runs as excepted

## Modifications under `.PyFunceble.yaml`

nothing

## Reproduction

```
pyfunceble -m -p 8 -db --database-type mariadb -uf 'https://gitlab.com/my-privacy-dns/external-sources/antipopads/raw/master/hosts'

Subject                                                                                              Status      HTTP Code 
---------------------------------------------------------------------------------------------------- ----------- ----------
jyahmckzsbh.com                                                                                      INVALID     ***       
nuowoczmvits.com                                                                                     INVALID     ***       
dsdiztki.bid                                                                                         INVALID     ***       
lwtsrwwlfd.com                                                                                       INVALID     ***       
wftduglf.com                                                                                         INVALID     ***       
```
```
wget 'https://gitlab.com/my-privacy-dns/external-sources/antipopads/raw/master/hosts'
```
```
pyfunceble -m -p 8 -db --database-type mariadb -f hosts

Subject                                                                                              Status      HTTP Code 
---------------------------------------------------------------------------------------------------- ----------- ----------
xrkfqpbubaq.com                                                                                      ACTIVE      ***       
htabtzmi.bid                                                                                         INACTIVE    ***       
```

## Expected behavior**
Tets running equally

## Versions

**OS:** Ubuntu Bionic
**Python Version:** 3.7
**PyFunceble Version:** pyfunceble 2.2.0. (Green Galago: Skitterbug)

## Additional context
`sudo -H python3 -m pip install --upgrade PyFunceble` prior to the test...

with `sudo -H python3 -m pip install --upgrade PyFunceble-dev`

resolts is:

```
pyfunceble -m -p 8 -db --database-type mariadb -uf 'https://gitlab.com/my-privacy-dns/external-sources/antipopads/raw/master/hosts'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/PyFunceble/cli/__init__.py", line 95, in tool
    PyFunceble.load_config(generate_directory_structure=False)
  File "/usr/local/lib/python3.6/dist-packages/PyFunceble/__init__.py", line 682, in load_config
    cconfig.Load(CONFIG_DIRECTORY, custom)
  File "/usr/local/lib/python3.6/dist-packages/PyFunceble/config/load.py", line 90, in __init__
    self.__load_it()
  File "/usr/local/lib/python3.6/dist-packages/PyFunceble/config/load.py", line 101, in __load_it
    self._load_config_file()
  File "/usr/local/lib/python3.6/dist-packages/PyFunceble/config/load.py", line 300, in _load_config_file
    self._install_iana_config()
  File "/usr/local/lib/python3.6/dist-packages/PyFunceble/config/load.py", line 409, in _install_iana_config
    iana_link = self.data["links"]["iana"]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyfunceble", line 8, in <module>
    sys.exit(tool())
  File "/usr/local/lib/python3.6/dist-packages/PyFunceble/cli/__init__.py", line 1039, in tool
    PyFunceble.LOGGER.exception()
AttributeError: 'NoneType' object has no attribute 'exception'
```

**Comment by funilrys** [comment]
Can you create a PR which fix the description of `-uf` ? :joy_cat:  

I thought I  you will keep me awake a little bit more :joy_cat: ... But yeah `-uf` is meant for a test of file with URL (http{s,}://*) and not domains/IP.

For the IANA issue ... I can't reproduce :thinking:  That one will keep me awake in my dreams I guess :thinking:

**Comment by funilrys** [comment]
Note: You can do `-f https://*` it will work.

**Comment by funilrys** [comment]
Note: Same for `--link https://*` === `-f https://*`

**Comment by funilrys** [comment]
Note: `-uf https://*` == `-uf phishing_database_full_urls`

**Comment by funilrys** [comment]
Note `--upgrade PyFunceble` (master) !=== `--upgrade PyFunceble-dev` (dev)

**Comment by funilrys** [comment]
Sorry I'm kinda tired :joy_cat: Spend my day with my birthday calls and surprises (Yeah It's my cake day) :joy_cat: 

```
  File "/usr/local/lib/python3.6/dist-packages/PyFunceble/config/load.py", line 409, in _install_iana_config
    iana_link = self.data["links"]["iana"]
TypeError: 'NoneType' object is not subscriptable
```

Means  Configuration file not readable/downloadable.

```
 File "/usr/local/lib/python3.6/dist-packages/PyFunceble/cli/__init__.py", line 1039, in tool
    PyFunceble.LOGGER.exception()
AttributeError: 'NoneType' object has no attribute 'exception'
```

I still can't reproduce but it can be fixed tomorrow :+1: It's actually normal to get that one as `PyFunceble.LOGGER` was not initiated yet (Yeah that one is initiated once the configuration file completely loaded)

**Comment by spirillen** [comment]
> Note: Same for `--link https://*` === `-f https://*` === `-f hosts`

guess I most look up you docs source a do some rewrites :smiling_imp: 

Funny, I'm 1/8 german.... and my b-day is in 10 days turning a old tired dude, but becomming a powerfull .45'er    .......... do you feel lucky punk :gun:

**Comment by spirillen** [comment]
PS Happy Birthday :de:

**Comment by funilrys** [comment]
> guess I most look up you docs source a do some rewrites 

Feel free to do :wink: 

> PS Happy Birthday :de:

Vielen Dank!

**Comment by spirillen** [comment]
> Note: Same for `--link https://*` === `-f https://*` === `-f hosts`

What is the actually diff between `-f` and `--link`? 
if it is as I have understood it that they are equal, why keep two commands for one job? It will only add to confusion.

From the syntax naming i would up-front understand `--link` as the command that checked the `HTTP response code` from any given link-url(s)? and set `--link` === `-u` === `-uf`

As more I understand the program, the more confusing do I find the why `--link` is  there.

I know the following would be quite a bit of coding, but from my terminology:

* `-l|--link` you are linking to/from something. ex a hosted file. This command would be used to _link_ to an external resource for std-in
* `-f|--file`you will do something with this local file(s)? for std-in 
* `-u|--url` You switch on the link/Url checker for HTTP response codes
* As default test is the whois elif dns elif http, there wouldt not necessarily be an option to turn on this test
* But **_maybe_** for a future release like 4.x it could be smart to do two tests at once when the option `-u` is given. <- This is a drive-by thought and not been thinking to the end.....

Also added the question [here](https://github.com/funilrys/PyFunceble/pull/62#issuecomment-555518393)

What do you other thinks of this?
Ping for your comments: @mitchellkrogza @ZeroDot1 @DandelionSprout @dnmTX if you dare to stick out your heads from the bush :smile:

**Comment by DandelionSprout** [comment]
To the degree I have anything to say about this, which is actually very little, I was of the belief that `--link` was a clone of the no-parameter domain check and not of `--f`. That being said, I haven't really ever used PyFunceble for anything but local files, online files (with or without `--ad`), and single domains.

Out of PyFunceble's regular users, I'm likely the one who use it the least.

**Comment by funilrys** [comment]
> What is the actually diff between -f and --link?
None ... It was just created to make this "clearer" But I guess we can delete `--link`.

Let's do it like this:

`-f` ==> Accepts local file or remote file ==> excepts domains  (`example.com`)
`-uf` ==> Accepts local file or remote file ==> excepts URLS (`https://example.com`)
`-u` ==> Accept 1 input (will be changed this week) ==> excepts URL (`https://example.com`)
`-d` ==> Accepts 1+ input(s) ==> excepts domain(s) (`example.com`)

I agree I misdescribed them. It's time to fix that.

About having a universal entry point for remote files and another for local file and then setting the type of test with `--url` or `--domain` (or another flag) let's keep that for the future :wink: 

@DandelionSprout `(2-5 times a month on average).` is actually a regular user if it's not behind infrastructure like one of those: @dead-hosts @ultimate-hosts-blacklist @Import-External-Sources 😉

**Comment by spirillen** [comment]
Hmm
Now you confuses me...

```
-f ==> Accepts local file or remote file ==> excepts domains (example.com)
-uf ==> Accepts local file or remote file ==> excepts URLS (https://example.com)
```

`-f` is used for testing domains, and
`-uf`is for testing HTTP respond code of urls right?

**Comment by spirillen** [comment]
Could we rename this one?

`:code:`-n``  to `-nf` for logic? and `-n` on windows is as i recall number-of-loop

ping -n 4 example.org

**Comment by funilrys** [comment]
> `-f` is used for testing domains, and
> `-uf` is for testing HTTP respond code of urls right?

Yes with `expects ...` I meant the content expected to be tested. 

* `example.org` is the content of `local file` or the content of `remote file` 
  * Operation ==> SYNTAX ==> WHOIS ==> DNSLOOKUP ==> HTTP
* `https://example.org` is the content of `local file` or the content of `remote file` 
  * Operation ==> SYNTAX ==> HTTP

**Comment by funilrys** [comment]
> Could we rename this one?
> 
> `:code:`-n`` to `-nf` for logic? and `-n` on windows is as i recall number-of-loop
> 
> ping -n 4 example.org

@spirillen :heavy_check_mark:
