### ISSUE TITLE
New line at end of output

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#63]
I'm missing some new lines in the output!!

```
# File generated by PyFunceble (v2.45.0.dev) / https://github.com/funilrys/PyFunceble
# Date of generation: 2019-11-19T05:43:41.318605

0.0.0.0 bit.ly
0.0.0.0 magdove.xyz
0.0.0.0 magrie.pw
0.0.0.0 mfio.cf
0.0.0.0 nhsrv.cf
0.0.0.0 solarmoviex.to
0.0.0.0 solarmoviex.to0.0.0.0 bit.ly0.0.0.0 bit.ly0.0.0.0 bit.ly0.0.0.0 bit.ly
```

Not that it ever should have been a hosts file, but forgot to add the `--plain` and that was maybe in good luck in this case.

The newline I was going to refer to is in the end of the output files, from my point of view they are lacking the last newline.  
The output makes cat/grep/etc the output looks like this

```
head output/hosts/ACTIVE/hosts 
# File generated by PyFunceble (v2.45.0.dev) / https://github.com/funilrys/PyFunceble
# Date of generation: 2019-11-19T05:43:41.318605

0.0.0.0 bit.ly
0.0.0.0 magdove.xyz
0.0.0.0 magrie.pw
0.0.0.0 mfio.cf
0.0.0.0 nhsrv.cf
0.0.0.0 solarmoviex.to
0.0.0.0 solarmoviex.to0.0.0.0 bit.ly0.0.0.0 bit.ly0.0.0.0 bit.ly0.0.0.0 bit.ly$USER@$:
```

I know there can be two versions of the why/why-not, but personally I strips the empty lines with awk `'/^(#|$)/'; printf(etc)` when the scripts handle the files.

It's not an important thing, but for at least v.3 unless you have a specific reason to not add a ending newline.

Pyf = Version 2.45.0.dev

**Comment by funilrys** [comment]
Fixed by https://github.com/funilrys/PyFunceble/commit/1cef0cb82d9b4d66d8d29dfab5cf0f7a416efc45.

**P.S: Help us, DO NOT close this issue manually. This issue is going to be closed automatically once https://github.com/funilrys/PyFunceble/commit/1cef0cb82d9b4d66d8d29dfab5cf0f7a416efc45 will be merged to master.**

**Comment by funilrys** [comment]
Uhh actually 🤔 This line should fix it: https://github.com/funilrys/PyFunceble/blame/b18b220d283b4cfdcb92eb70cdb1f3d37d2f9b61/PyFunceble/cli/processes/workers/file_sorter.py#L212

**Comment by spirillen** [comment]
Will follow up tomorrow, leaving as unread, you get a screenshot on keybase in 1 sec

**Comment by spirillen** [comment]
@ZeroDot1 is this related to https://gitlab.com/ZeroDot1/CoinBlockerLists/-/issues/65 ??
