### ISSUE TITLE
[SPECIAL] id.google.* may be marked as INACTIVE if 404 is returned.

### ISSUE THREAD

**Issue by funilrys** [funilrys/PyFunceble#64]
**NOTE:** @kowith337 can you confirm this? (Others too)

Prior to https://github.com/dead-hosts/hosts_google_adservice_id_git_kowith337/commit/73a05d1fc6f77f4aa7a4a2a899e234c6b30b6051: 

```
id.google.vg                                                                                         Unknown           HTTP Code  404        2019-11-19T11:03:16.694019
```

`id.google.*` may be added to the list of SPECIAL rules.

**Comment by kowith337** [comment]
Half confirm, but not at all.

Here's a quick test with Desktop Browser under VPN (Browsec SG)
> Use Marmaduke's Chromium and Spoof UA as **Linux Desktop** and **Chrome 71.0.3578.99**
> Still cannot find `id.google.*` connection
![image](https://user-images.githubusercontent.com/16535467/69345823-5e086600-0ca4-11ea-8a0c-b58477ef56a8.png)

Meanwhile, when I've also test with Bromite + pDNSF, the DNS log show it's still trying to connect.
> 
![image](https://user-images.githubusercontent.com/16535467/69347262-bb051b80-0ca6-11ea-82fb-5119efc28e9d.png)

**Comment by kowith337** [comment]
Oops, that's not a main point.

It seems like all of `id.google.*` are hit as `302 Found` and redirecting to `id.google.com`, sometime I can see the connections still made to, but sometime cannot, especially if I've blocked `adservice.google.*`, the `id.google.*` maybe made to.

**Comment by funilrys** [comment]
I can confirm the same behavior.
As the risk of false-positive is high, I'm closing this.

Thanks for your time!
