### ISSUE TITLE
@dev KeyError: 'seconds_before_http_timeout'

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#69]
## Bug description
As I was working on the https://github.com/Import-External-Sources/pornhosts project fixing the renaming of `--options` and trying to get the Sql exported and imported on next run, this error suddenly started to appears.

As you can see, the errors started to occur from build [#161](https://travis-ci.com/Import-External-Sources/pornhosts/builds/140965013), and despises I triet to "reset" changes, the error persisted

## Modifications under `.PyFunceble.yaml`

N/A

## Reproduction

See linked project and https://github.com/spirillen/Dead-Domains

## Expected behavior**
Running as usual

## Screenshots
Travis build link attached

## Versions

**OS:** Ubuntu Bionic
**Python Version:** 3.7
**PyFunceble Version:** @dev 

## Additional context
Merry Christmas :santa:

**Comment by funilrys** [comment]
Fixed by https://github.com/funilrys/PyFunceble/commit/239de644cd997f8352c14532aff04edbe4f49f4f.

**P.S: Help us, DO NOT close this issue manually. This issue is going to be closed automatically once https://github.com/funilrys/PyFunceble/commit/239de644cd997f8352c14532aff04edbe4f49f4f will be merged to master.**

**Comment by spirillen** [comment]
That change broke another set `--option`

https://travis-ci.com/Import-External-Sources/pornhosts/builds/141104994#L5518

:underage:  https://github.com/Import-External-Sources/pornhosts/blob/04cd723a57c8c0e1e7fd46bb23e4c32157b99807/dev-tools/DataTesting.sh#L45

`--autosave-minutes 20` is unset by your latest change :unamused:

**Comment by funilrys** [comment]
So, the first tests result. I tried with https://github.com/spirillen/Dead-Domains and it is now working. 

I'm now trying the `--quiet` argument.

**Comment by funilrys** [comment]
`--quiet` is working back after the fix of #70.
