### ISSUE TITLE
cooldown time ?

### ISSUE THREAD

**Issue by funilrys** [funilrys/PyFunceble#74]
We should implement a way to set a number of second between each tests.

cf: https://github.com/dead-hosts/adaway.github.io_git_AdAway/issues/1 (from @jawz101)

**Comment by spirillen** [comment]
That's not an bad Idea @jawz101 :+1:

**Comment by jawz101** [comment]
well, right now I feel uncomfortable just watching the INACTIVE/hosts file and inactive_db.json because they look like they only grow.  Do they clear themselves out after so many days?

The reason is I like to use PyFunceble scans for list maintenance.

**Comment by spirillen** [comment]
Hey @jawz101 you are already on  the import https://gitlab.com/my-privacy-dns/external-sources/hosts-sources/blob/master/scripts/import.sh#L72 :smiley:
