### ISSUE TITLE
InactiveDB should clean itself after x days

### ISSUE THREAD

**Issue by funilrys** [funilrys/PyFunceble#77]
As @jawz101 [stated](https://github.com/funilrys/PyFunceble/issues/74#issuecomment-574317566)

> well, right now I feel uncomfortable just watching the INACTIVE/hosts file and inactive_db.json because they look like they only grow. Do they clear themselves out after so many days?

Indeed, actually what we do is we constantly retest without cleaning. A cleaning mechanism is highly wanted!

Thanks for the feedback @jawz101!

**Comment by dnmTX** [comment]
The INACTIVE ones needs to be cleared after each filtering,this way one can keep track,do telemetry(very helpful for lists curators) etc. etc. 😉

**Comment by jawz101** [comment]
now the dead hosts project gives really odd results.  Now lists show severely smaller and they all report zero dead hosts.

**Comment by funilrys** [comment]
Globally (not per project as it will be adjusted for @ultimate-hosts-blacklist and each member of @dead-hosts can change this),

what is the best cleaning interval for you?

[![](https://api.gh-polls.com/poll/01E6CM6GNPVX3NVC0WGEXV7ZQN/10%20days)](https://api.gh-polls.com/poll/01E6CM6GNPVX3NVC0WGEXV7ZQN/10%20days/vote)
[![](https://api.gh-polls.com/poll/01E6CM6GNPVX3NVC0WGEXV7ZQN/20%20days)](https://api.gh-polls.com/poll/01E6CM6GNPVX3NVC0WGEXV7ZQN/20%20days/vote)
[![](https://api.gh-polls.com/poll/01E6CM6GNPVX3NVC0WGEXV7ZQN/28%20days)](https://api.gh-polls.com/poll/01E6CM6GNPVX3NVC0WGEXV7ZQN/28%20days/vote)
[![](https://api.gh-polls.com/poll/01E6CM6GNPVX3NVC0WGEXV7ZQN/30%20days)](https://api.gh-polls.com/poll/01E6CM6GNPVX3NVC0WGEXV7ZQN/30%20days/vote)
[![](https://api.gh-polls.com/poll/01E6CM6GNPVX3NVC0WGEXV7ZQN/40%20days)](https://api.gh-polls.com/poll/01E6CM6GNPVX3NVC0WGEXV7ZQN/40%20days/vote) 

_What is meant: After x days (since inclusion in the database) the subject will be deleted from the database._

**Comment by funilrys** [comment]
touch @mitchellkrogza too.

**Comment by funilrys** [comment]
touch @spirillen too.

**Comment by spirillen** [comment]
I think it sound like a good idea to clean out the old entries, but not the whois data before x days after "domain date" is expired.

> That will never be cleaned! It's our acceptance assurance!

> If we start to clean it, the system will start to ask the WHOIS record to the WHOIS servers ... And after some time, your IP will be temporarlly banned from them ..

Exactly the reason i would keep them too 😃
But if the domain expiration data is older than x days, I can't see any reason to keep them... that could be let's say 60 days... as it probably ain't to become reactivated then...

_Note: This is a transcript from keybase._

**Comment by funilrys** [comment]
@spirillen, There probably is some way to do it better too for the WHOIS database. 

I Will look into that @spirillen !
