### ISSUE TITLE
The term "PyFunceble" is not recognized as the name of a cmdlet, ..."

### ISSUE THREAD

**Issue by BlackJack8** [funilrys/PyFunceble#83]
## Bug description

**This code worked as expected:**

> ```
>  $ git clone https://github.com/funilrys/PyFunceble.git
>  $ cd PyFunceble
>  $ python3 setup.py test
>  $ pip3 install --user -e .
> ```

But upon entering 

> `PyFunceble --version`

 Powershell gives the error mentioned in the header.

## Modifications under `.PyFunceble.yaml`
**None**

## Reproduction

**Steps to reproduce the behavior:**
1. Install PyFunceble with the code mentioned above
2. Run `PyFunceble --version`
3. See the error

## Expected behavior
**PyFunceble should now launch**

## Screenshots
**Can add screenshots if needed**

## Versions

**OS:** Windows 10 Pro
**Python Version:** Python 3.8
**PyFunceble Version:** Newest version from https://github.com/funilrys/PyFunceble.git

## Additional context
**What i have tried:** 
Reinstalling pip/pip3 and python
Reinstalling PyFunceble
Adding PyFunceble to the PATH
Running the code in Powershell with and without administrator privileges

**What i have checked:**
Whether pip/pip3 and python was in the path (positive)

**I´d be glad if someone can help me with this issue.**
If there are any questions, feel free to ask me.

**Comment by funilrys** [comment]
@BlackJack8, What about `PyFunceble.exe` ?

**Comment by spirillen** [comment]
This could be related to the problem that python isn't exporting the path argument by default on win, don't recall where I found it as it is in the past I was reading this.

**Comment by funilrys** [comment]
Mhh 🤔 Our GitHub actions jobs under Windows are working .... But I'm willing to find a Windows machine so that we can get through this.

**Comment by spirillen** [comment]
> Mhh thinking Our GitHub actions jobs under Windows are working .... But I'm willing to find a Windows machine so that we can get through this.

Just recall, it is a cygwin related issue <https://github.com/funilrys/PyFunceble/issues?q=is%3Aissue+is%3Aopen+cygwin>

**Comment by funilrys** [comment]
@DandelionSprout  [said](https://github.com/funilrys/PyFunceble/issues/127#issuecomment-846632513):

> From what I remember:
> 
> 1) I used PowerShell 7.1.3, downloaded from Microsoft Store.
> 2) I installed the GUI installer for Python 3.9 for Windows.
> 3) I run `pip install --user --pre PyFunceble-dev`, and PyFunceble is correctly installed.
> 4) Here's comes the most interesting part: Due to having refreshed my Windows 10 installation 2 months ago, `pip` then shows quite a few errors (circa 10) about missing PATH filepaths in Windows, including one for Python fonts.
> 5) I was never able to trigger the missing font filepath warning again, and was only able to take care of adding the Python plugin filepath to PATH.
> 6) It was at this point I tested it and got the results above.

Therefore, I'm closing this issue as it looks like an installation and windows related issue. Feel free to try what @DandelionSprout wrote and give us some feedback.
