### ISSUE TITLE
Distribute with docker

### ISSUE THREAD

**Issue by funilrys** [funilrys/PyFunceble#85]
It might be a good idea to provides PyFunceble inside a docker container.

**Comment by mitchellkrogza** [comment]
A long overdue and much needed solution especially for the Doze users. :grin:

**Comment by spirillen** [comment]
Actually kind of already exist :stuck_out_tongue:  https://gitlab.com/my-privacy-dns/ci-runner

**Comment by funilrys** [comment]
If one wants to test it for us, it's available on the docker hub.

https://hub.docker.com/r/pyfunceble/pyfunceble-dev

Stay safe and healthy!
