### ISSUE TITLE
Potential dependency conflicts between pyfunceble-dev and urllib3

### ISSUE THREAD

**Issue by NeolithEra** [funilrys/PyFunceble#92]
Hi, as shown in the following full dependency graph of  **_pyfunceble-dev_**, **_pyfunceble-dev_** requires _**urllib3**_ (the latest version)， while the installed version of **_requests_**(2.23.0) requires _**urllib3 >=1.21.1,<1.26**_.

According to Pip's “first found wins” installation strategy, _**urllib3 1.25.8**_ is the actually installed version.  

Although the first found package version _**urllib3 1.25.8**_ just satisfies the later dependency constraint （_**urllib3>=1.21.1,<1.26**_), it will lead to a build failure once developers release a newer version of urllib3.

### Dependency tree--------
```
pyfunceble-dev - 3.1.7
| +- colorama(install version:0.4.3 version range:*)
| +- cryptography(install version:2.9 version range:*)
| | +- cffi(install version:1.14.0 version range:>=1.8)
| | +- six (install version:1.14.0 version range:>=1.4.1)
| +- dnspython(install version:1.16.0 version range:*)
| +- domain2idna(install version:1.9.1 version range:>=1.6.1)
| | +- colorama(install version:0.4.3 version range:>=0.4.1)
| | +- setuptools(install version:46.1.3 version range:>=40.8.0)
| +- pymysql(install version:0.9.3 version range:*)
| +- python-box(install version:4.2.2 version range:*)
| | +- ruamel.yaml(install version:0.16.10 version range:*)
| | +- toml(install version:0.10.0 version range:*)
| +- python-dotenv(install version:0.12.0 version range:*)
| | +- typing(install version:3.7.4.1 version range:*)
| +- pyyaml(install version:5.3.1 version range:*)
| +- requests(install version:2.23.0 version range:*)
| | +- certifi(install version:2020.4.5.1 version range:>=2017.4.17)
| | +- chardet(install version:3.0.4 version range:>=3.0.2,<4)
| | +- idna(install version:2.9 version range:>=2.5,<3)
| | +- urllib3(install version:1.25.8 version range:>=1.21.1,<1.26)
| +- setuptools(install version:46.1.3 version range:*)
| +- urllib3(install version:1.25.8 version range:*)
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution
1.	Loosen the version range of **_urllib3_** to be **_<=1.25.8_**.
2.	Remove your direct dependency **_urllib3_**, and use the **_urllib3_** transitively introduced by **_requests_**.


@funilrys Which solution do you prefer, 1 or 2?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by funilrys** [comment]
Hey @NeolithEra! Thanks for your time!

I will prefer the first proposition 🙂

Stay safe and healthy.
Nissar
