### ISSUE TITLE
Syntax validation error

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#93]
## Bug description
`Valid` domain syntax reported as `INVALID` with the `--syntax` string

## Modifications under `.PyFunceble.yaml`

See <https://github.com/PyFunceble-Templates/pyfunceble-miniconda>

## Reproduction

1. Get <https://github.com/PyFunceble-Templates/pyfunceble-miniconda>
2. Run with `bash miniconda_pyfunceble.sh /matrix/source/adware/domains.list`
```
Enter output directory for test results: /tmp/pyfuncebletesting/msecnd_net/
Which version of PyFunceble would you like to use?: pyfunceble or pyfunceble-dev: pyfunceble-dev
Enter any custom test string: --plain --syntax
```
![image](https://user-images.githubusercontent.com/44526987/83527036-8f7dac00-a4e7-11ea-9c42-dc22b6b146e7.png)

## Expected behavior
As already mentioned no FP

## Screenshots
See above

## Versions

**OS:** Ubuntu 19.10 eoan
**Python Version:** 3.8
**PyFunceble Version:** @-dev

**Comment by spirillen** [comment]
In addition to this I found a second bug

from the docs <https://pyfunceble.readthedocs.io/en/dev/usage/from-a-terminal.html?highlight=--syntax#syntax>

> This will disable all other forms of test, will validate the syntax of a given test subject, and output its results in plain format into output/domains/{VALID,INVALID}/list


But when I'm running ls or tree I have no output

```
tree /tmp/pyfuncebletesting/msecnd/
/tmp/pyfuncebletesting/msecnd/
├── dir_structure.json
├── iana-domains-db.json
├── inactive_db.json
├── public-suffix.json
└── user_agents.json

0 directories, 5 files
```

**Comment by spirillen** [comment]
Found the bug.... 

The outdir is placed in the working dir, not within the `outdir`directive

**Comment by funilrys** [comment]
Fix introduced with https://github.com/funilrys/PyFunceble/commit/e69245186e9b3b5fa1ab9e682b35473d8d244d1e.

**P.S: Help us, DO NOT close this issue manually. This issue is going to be closed automatically once https://github.com/funilrys/PyFunceble/commit/e69245186e9b3b5fa1ab9e682b35473d8d244d1e will be merged to master.**
