### ISSUE TITLE
Source/Test files gets delete after testing

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#97]
## Bug description
Lately my test/source file for testing have started to disappear after running @PyFunceble :unamused: 

## Modifications under `.PyFunceble.yaml`
None

## Reproduction
```bash
pyfunceble --dns 192.168.1.105 -h --plain -a -f wildcard.list`
```

```bash
$ ls -lh
total 48K
-rw-rw-r-- 1 joakim joakim 8.5K Jun 17 13:34 combined.txt
-rw-rw-r-- 1 joakim joakim 8.7K Jun 15 15:26 dir_structure.json
-rw-rw-rw- 1 joakim joakim 6.1K Apr 17 04:39 domains.list
-rw-rw-rw- 1 joakim joakim 2.4K Apr 17 17:10 inactive.list
-rw-rw-rw- 1 joakim joakim   21 Feb  4 00:29 inactive_wildcard.list
drwxrwxr-x 9 joakim joakim 4.0K Jun 15 15:25 output
-rw-rw-rw- 1 joakim joakim   38 Apr 17 17:43 README.md
```

This is how I would suppose it should be
```bash
$ ls -lh
total 48K
-rw-rw-r-- 1 joakim joakim 8.5K Jun 17 13:34 combined.txt
-rw-rw-r-- 1 joakim joakim 8.7K Jun 15 15:26 dir_structure.json
-rw-rw-rw- 1 joakim joakim 6.1K Apr 17 04:39 domains.list
-rw-rw-rw- 1 joakim joakim 2.4K Apr 17 17:10 inactive.list
-rw-rw-rw- 1 joakim joakim   21 Feb  4 00:29 inactive_wildcard.list
drwxrwxr-x 9 joakim joakim 4.0K Jun 15 15:25 output
-rw-rw-rw- 1 joakim joakim   38 Apr 17 17:43 README.md
-rw-rw-rw- 1 joakim joakim 6.1K Apr 17 04:39 wildcard.list
```

You can get the diff here:
<https://github.com/mypdns/matrix/commit/4ac9568f7f39f8f10f665ebc7a5fefd00fb803ad#diff-dd083e3d25a8ff5919584e47b8b1e5da>

1. Run pyfunceble
2. check your input folder
4. Your source file is gone

## Expected behavior
Leave the source file where it is

## Screenshots

![image](https://user-images.githubusercontent.com/44526987/84895761-1a8fa200-b0a3-11ea-8ee0-f216f2abd4e7.png)

![image](https://user-images.githubusercontent.com/44526987/84895795-27ac9100-b0a3-11ea-91ad-d4bcf6f05304.png)

## Versions

**OS:** Distributor ID: Ubuntu
Description:    Ubuntu 19.10, eoan
**Python Version:** Python 3.8.3 (default, May 19 2020, 18:47:26)
**PyFunceble Version:** pyfunceble 3.1.20.dev (Teal Blauwbok: Moth)

## Additional context
Severity: **VERY HIGH**, Burning

**Comment by spirillen** [comment]
PS: The same happened when I was setting up the rules for [UHB](https://gitlab.com/my-privacy-dns/rpz-dns-firewall-tools/bind-9/-/blob/master/scripts/uhb.sh)

**Comment by funilrys** [comment]
Note: The fix was deployed to dev and stable.

**Comment by funilrys** [comment]
Note: A global warning message for everyone running PyFunceble between 3.2.0 and 3.2.2 was deployed for the stable version.

**Comment by funilrys** [comment]
Note: The same global warning message for everyone running PyFunceble-dev between 3.2.0 and 3.2.2 was deployed to the dev version.

**Comment by spirillen** [comment]
Note 4: Super thanks :smile:

**Comment by funilrys** [comment]
@spirillen Was in my plan. Please report to https://github.com/funilrys/PyFunceble/issues/98.
