### ISSUE TITLE
Addition to special rules `*.wix.com`

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#99]
**Is your feature request related to a problem? Please describe.**
As this domain is used for hosting free sites with-in a third-level domain to `wix.com` I suggest this domain is added to the [special rules](https://pyfunceble.readthedocs.io/en/dev/responses/index.html)

As it is clear from several sources there could be a good reason to check these third levels for activities

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/44526987/85951908-6a554f80-b966-11ea-9dc8-332615652b34.png)

</details>

From own RPZ zones:

|id|name|type|content|
|--|----|----|-------|
|3495771|vashikaranbaba0.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495772|www.vashikaranbaba0.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495773|luckdinsky6.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495774|serviceportal19.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495775|www.serviceportal19.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495776|ucc.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495777|www.ucc.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495778|mobile.lc.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495779|de.mobile.lc.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495780|fr.mobile.lc.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495781|ru.mobile.lc.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495782|www.dns.lc.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495783|toad.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495784|wixed.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495785|emailmarketingguide.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495786|frog.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495787|www.frog.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495788|trig.i.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495789|www.trig.i.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495790|vk.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495791|l.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495792|onebestwl.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495793|www.onebestwl.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495794|premium.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495795|myexperien.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495796|www.myexperien.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495797|vigodno.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495798|www.vigodno.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495799|10evro.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495800|www.10evro.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495801|acquisition-tracker.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495802|es.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495803|ckummings.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495804|adsense.apps.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495805|premium.aws.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495806|ru.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495807|daihoaly.wix.com.rpz.mypdns.cloud|CNAME|.|
|3495808|www.daihoaly.wix.com.rpz.mypdns.cloud|CNAME|.|

also from EasyList:
https://github.com/easylist/easylist/commit/06b134496db9279bd7063d2f3f57d3f1f2243650#diff-99072d56e3758452bd7b56578fcdd5acR769-R770

And other external sources:
```bash
grep -ri 'wix.com' hosts-sources/data/ | awk -F ":" '{ print $2 }' | sort -u | wc -l
48
```

```python
pyfunceble -d georgiageorgia.wix.com frog.wix.com

Subject                                                  Status      HTTP Code 
--------------------------------------------------- ----------- ----------
georgiageorgia.wix.com                        ACTIVE      404       
frog.wix.com                                          INACTIVE    XXX   ( Note: RPZ filter)
```

<details><summary>Screenshot of georgiageorgia.wix.com</summary>

![image](https://user-images.githubusercontent.com/44526987/85952144-945b4180-b967-11ea-98a9-08d1842b3564.png)

</details>

**Comment by funilrys** [comment]
Fixed with https://github.com/funilrys/PyFunceble/commit/884eda86737c42e483dafd266d47b3ae7baf63ee.

**P.S: Help us, DO NOT close this issue manually. This issue is going to be closed automatically once https://github.com/funilrys/PyFunceble/commit/884eda86737c42e483dafd266d47b3ae7baf63ee will be merged to master.**
